### ISSUE TITLE
`require.context` is not enabled

### ISSUE THREAD

**Issue by nandorojo** [expo/router#10]
<img width="469" alt="Screen Shot 2022-09-27 at 6 43 46 PM" src="https://user-images.githubusercontent.com/13172299/192650535-2eaa9e4d-4fe0-4e8c-8a59-143e4a20f13c.png">

I don't see a special step for this in the docs (other than resolving metro's version). `yarn why metro` resolves `0.72.3` which is correct, so maybe this additional step should be documented?

For context, this is my original metro file:

```ts
// Learn more https://docs.expo.io/guides/customizing-metro
/**
 * @type {import('expo/metro-config')}
 */
const { getDefaultConfig } = require('expo/metro-config')
const path = require('path')

const projectRoot = __dirname
const workspaceRoot = path.resolve(__dirname, '../..')

const config = getDefaultConfig(projectRoot)

config.watchFolders = [workspaceRoot]
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
]

module.exports = config
```

Maybe this would have worked had I not specified a custom config?

**Comment by nandorojo** [comment]
I solved it with the following modification:

```js
// Learn more https://docs.expo.io/guides/customizing-metro
/**
 * @type {import('expo/metro-config')}
 */
const { getDefaultConfig } = require('expo/metro-config')
const path = require('path')

const projectRoot = __dirname
const workspaceRoot = path.resolve(__dirname, '../..')

const config = getDefaultConfig(projectRoot)

config.watchFolders = [workspaceRoot]
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
]

config.transformer.unstable_allowRequireContext = true

module.exports = config
```

However, I now see this error: 

<img width="461" alt="Screen Shot 2022-09-27 at 6 49 35 PM" src="https://user-images.githubusercontent.com/13172299/192651241-d91d2b1b-2607-4354-afa2-e74a6fc85398.png">

I'll upload a repro shortly. I suspect a monorepo could be the cause.

**Comment by nandorojo** [comment]
I now am thinking it is **not** necessarily a monorepo issue. I tried changing the entry point manually like so:

```json
"main": "../../node_modules/expo-router/entry"
```

However, I get the same error. It seems like the issue is `EXPO_ROUTER_APP_ROOT` isn't getting defined for some reason.

**Comment by EvanBacon** [comment]
Expo Router only works with `expo@46.0.13` as it enables context modules and injects `process.env.EXPO_ROUTER_APP_ROOT`

**Comment by nandorojo** [comment]
Ah, got it, that fixed both issues.

**Comment by EvanBacon** [comment]
Adding a troubleshooting guide now, thanks for the report.

**Comment by georgibakken** [comment]
I am trying to setup

**Comment by georgibakken** [comment]
I am trying to setup expo 47 and expo-router with nextjs, Solito and tamagui, taking inspiration from the two following starters:
- https://github.com/nandorojo/solito/tree/master/example-monorepos/with-expo-router
- https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito

However, I get the following two errors when trying to run `yarn native`

```sh
 ERROR  Error: The experimental Metro feature `require.context` is not enabled in your project.
This can be enabled by setting the `transformer.unstable_allowRequireContext` property to `true` in your Metro configuration.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

This is the [repo](https://github.com/georgibakken/expo-router-tamagui-next). Is there anything I am missing?
