### ISSUE TITLE
Unable to resolve "expo-router/entry"

### ISSUE THREAD

**Issue by eivindml** [expo/router#102]
I'm getting the error: `Unable to resolve "expo-router/entry" from "app/index.tsx"`. 

I have looked at #29, and it's not related to that issue it looks like. It's something that happened as soon as I tried to go from `yarn` to `pnpm`. 

<img width="354" alt="Skjermbilde 2022-10-21 kl  08 54 05" src="https://user-images.githubusercontent.com/202450/197131982-4bc47e52-7c87-4deb-92ea-46dd47e44442.png">

**Comment by EvanBacon** [comment]
Please provide a minimum repro

**Comment by jjenzz** [comment]
for `pnpm` support, add the following to an `.npmrc` file

```
strict-peer-dependencies=false
enable-pre-post-scripts=true
shamefully-hoist=true
node-linker=hoisted
prefer-symlinked-executables=false
```

**Comment by EvanBacon** [comment]
I see, Metro doesn't currently
