### ISSUE TITLE
`NativeStack.Screen` doesn't apply `options` inside of dynamic path

### ISSUE THREAD

**Issue by nandorojo** [expo/router#11]
I have the following structure:

- `(root).tsx` → NativeStack
- `(root)`
  - `index.tsx`
  - `users`
    - `[id].tsx`

If I use `NativeStack.Screen` inside of `(root)/index.tsx` to set `options` such as the `title`, it works fine. However, if I do the same inside of `(root)/users/[id].tsx`, the screen options don't apply.

If I apply the screen options inside of the `(root).tsx` file as a child of `NativeStack`, it does in fact work.
[
Reproduction here.](https://github.com/nandorojo/expo-router-bug) The line that doesn't work properly is [here](https://github.com/nandorojo/expo-router-bug/blob/master/app/(root)/users/%5Bid%5D.tsx#L8).

I noticed that options are only being set in an effect, so I'm not sure why it doesn't work.

### Aside

It's probably worth documenting that people should memoize `options` or lift it out of render, since it's a dependency of a hook which calls `setOptions` under the hood.

**Comment by EvanBacon** [comment]
From the [layout routes guide](https://expo.github.io/router/docs/features/layout-routes):

> If a nested route does not have a layout route then a virtual, unstyled navigator will be generated in-memory to accommodate the child route.

Meaning there is a `(root)/users.tsx` generated in memory which is intercepting the navigation options from `(root)/users/[id].tsx`.

This looks like an [upstream limitation](https://reactnavigation.org/docs/screen-options-resolution/) of React Navigation. Perhaps we could implement some context reference where a screen could specify which navigator it wants to modify:

```tsx
function Page() {
  return (<><NativeStack.Screen layout="(root)" options={{}} /></>)
}
```

This would probably use an underlying fork of `useNavigation` which would work like `useNavigation({ layout: '(root)' })`.

Thoughts?

**Comment by nandorojo** [comment]
Interesting. What would it look like to apply a layout route to the nested route? Would I put a `([id]).tsx` file next to it with a `Screen` in there?

**Comment by EvanBacon** [comment]
@nandorojo so I was thinking you could just access a list of navigators by path, so if you wanted to modify the layout at `(root)/users.tsx` you could use `(root)/users` to access it. Would be on the developer to ensure they're requesting a layout that exists.

**Comment by javascripter** [comment]
if we modify the screen props of a parent/ancestor navigator while keeping the virtual layouts, does it mean the screen props will be shared among the nested screens?

for example,

- (root)
  - users
    - about.tsx
    - [id].tsx

if you're in `about` and modify `(root)` screen props like title and then move to `[id]`, will the screen props of `(root)` be kept because `users` contains the virtual navigator and `(root)` itself does not change?

**Comment by EvanBacon** [comment]
@javascripter this makes sense to me. The parent shouldn't have to refresh because a child changed.

**Comment by javascripter** [comment]
I see. With the addition of parent navigator access the removal of virtual layout requirement, this makes sense to me while offering more flexibility.
