### ISSUE TITLE
<Screen /> not redirecting properly when restricting routes

### ISSUE THREAD

**Issue by tsvetann** [expo/router#115]
### Summary

When following the authentication example in the docs I am facing a redirect issue.

I have the following file structure:
![Screenshot 2022-10-27 at 12 51 29](https://user-images.githubusercontent.com/2565891/198253108-45a0bbbe-67e6-4bb8-ad47-ab7798596280.png)

The code for restricting routes:

```javascript
function RootLayout() {
  // Use some global auth context to control the route access.
  // const auth = AuthContext.useToken();
  const auth = true;

  return (
    // Create a basic custom layout to render some children routes.
    <Layout screenOptions={{ showHeader: false }}>
      <Layout.Screen
        name="auth"
        // When the auth is available (user is signed in), restrict access to the sign-in page.
        redirect={auth}
      />
      <Layout.Screen
        name="(app)/home"
        // When the auth is unavailable (no user signed in), restrict access to all the routes in the `(app)` directory.
        redirect={!auth}
      />

      <Layout.Children />
    </Layout>
  );
}
```

When I toggle the auth constant to false it correctly redirects me to `auth/index` but when I toggle the auth constant to true it redirects me to `(auth)/index` instead of `(auth)/home/index`. 

Is this an issue with the router or I messed up something?

Thanks

### Minimal reproducible example

All details are in the summary

**Comment by Albert-Gao** [comment]
If I understand it right, you misunderstood the prop `redirect`, it means `when the condition is true, I redirect away from THIS path`.

For example, `/app` is protected, then when `isAuth === false`, you redirect away all requests to the `/app` page.

This is my working example:

![image](https://user-images.githubusercontent.com/18282328/198335160-bc3b95cd-012d-4a93-bb4b-7d453d7f6794.png)


In your code above, seems you are doing the opposite 😄
You redirect the user away from the `/auth` when `auth === true`

![image](https://user-images.githubusercontent.com/18282328/198335450-32a01ee3-a901-48ee-96a9-f45630b99d81.png)

**Comment by tsvetann** [comment]
Thanks @Albert-Gao. What I am trying to highlight that doesn't work me is not the redirect logic but the rendering. I toggle the auth and when it hits my `(app)/home` it actually renders `(app)/index` and not the home

**Comment by EvanBacon** [comment]
The redirect prop seems to be working as expected, if you need more articulate behavior then I recommend using a hook that redirects using the imperative API. [Example in the auth guide](https://expo.github.io/router/docs/guides/auth/).
