### ISSUE TITLE
EAS Cli build error

### ISSUE THREAD

**Issue by fristyr** [expo/router#116]
### Summary

Hi! I was trying to make a build with EAS cli, and got some errors.
One of them contains expo-router module issue.
I have expo-updates in the project, maybe they have some conflicts (take a look at the screenshot)?

### Minimal reproducible example

<img width="892" alt="image" src="https://user-images.githubusercontent.com/33237937/198867779-9c726096-7b7f-4694-a18b-3adeffda1050.png">

**Comment by louisholley** [comment]
do you have 

```
 "resolutions": {
    "metro": "0.73.2"
  },
```

in your `package.json`?

**Comment by fristyr** [comment]
Yes, I have `"metro": "0.73.3"`

**Comment by EvanBacon** [comment]
Ensure you're using the latest Expo CLI and Expo Router. The env var that needs to be set has two different fallbacks (Expo CLI, and [Babel](https://github.com/expo/router/blob/f090d80cd692a59616bbb9e8b93f9f42083d5737/packages/expo-router/babel.js#L7))and it appears your project is using none of them.
