### ISSUE TITLE
Improve Metro resolution error message

### ISSUE THREAD

**Issue by Albert-Gao** [expo/router#12]
Hi,

I found that adding this 

```javascript
import { StacksProvider } from "@mobily/stacks";
```

would cause this error:

![image](https://user-images.githubusercontent.com/18282328/192669330-b9f76a9f-8a0f-4e75-a821-329b1b28241e.png)

The reproduce repo is here: https://github.com/Albert-Gao/expo-router-web-try-out

remove the usage of `<StacksProvider/>` would solve this problem.

As shown in the screenshot, `@mobily/stacks` is not in the call stack, would be better if we can include this `@mobily/stacks` in the call stack so we can identify this problem easier.

**Comment by Albert-Gao** [comment]
just wonder if @mobily should know this :) in terms of providing a different perspective

**Comment by mobily** [comment]
@Albert-Gao that's certainly interesting! thanks for the repro repo, I will investigate this

**Comment by EvanBacon** [comment]
Would love to know the root import that is breaking the `react-native-web` alias.

**Comment by mobily** [comment]
good news, I was able to find the root of this problem 😉 long story short, I'm using `esbuild` for bundling `stacks`, and when the output format for the generated files is set to `cjs`, `esbuild` transforms imports to:

```js
var ReactNative = __toESM(require("react-native"));
```

apparently, the `react-native-web` babel plugin doesn't know how to handle this ¯\\\_(ツ)\_/¯

I have already fixed it up by changing imports to the following:

```js
var moduleReactNative = require('react-native');
var ReactNative = __toESM(moduleReactNative);
```

and it works eventually 🎉

@Albert-Gao I published `v2.2.2` a few minutes ago, let me know if that works on your end!

**Comment by Albert-Gao** [comment]
Thanks a lot, updated to the latest version of `@mobily/stacks` fixed it !
Appreciate your time! @mobily 

@EvanBacon any improvement we can do further? or i just close this? :D

**Comment by EvanBacon** [comment]
Great! I've also found that setting a yarn resolution on `"metro-resolver": "^0.72.3"` improves the error message. We have a task internally tracking a more robust solution, but these should be good for now.
