### ISSUE TITLE
nested stacks and fragment routes with deeplinks 

### ISSUE THREAD

**Issue by louisholley** [expo/router#121]
### Summary

hello! in our app we have a tab navigator with 3 nested stacks with screens that can be deep linked to.

our home stack uses a layout route so instead of `/home` and `/home/profile` we use `/` and `/profile` to mirror navigation in our web app (we're using solito so routes have to be identical across native and web).

if I deep link to a route in one of the other stacks (`community/questions/123`) then do `router.back()`, i am taken to the `/community` route as expected

however, if i deep link to a route in the home stack (`/profile`) and do `router.back()` I get

```
The action 'GO_BACK' was not handled by any navigator.

Is there any screen to go back to?

This is a development-only warning and won't be shown in production.
```

I've attached a minimal repro with setup that resembles ours as closely as possible

I have tried setting this behaviour up by doing `home/profile` instead of `(home)/profile` and it seems to work as expected - is there any way to achieve this with fragment routes so that doing `router.back()` after navigating to `/profile` takes you to `/`?

thanks so much in advance

### Minimal reproducible example

https://github.com/louisholley/expo-router-issue-repro

1. open the app with `npx uri-scheme open "exp://192.168.0.15:19000/--/community/questions/123" --ios` and see that pressing back in the header works
2. open the app with `npx uri-scheme open "exp://192.168.0.15:19000/--/profile" --ios` and see the error mentioned above

**Comment by EvanBacon** [comment]
You can define initial route names using `unstable_settings` in a Layout Route, this enables you to "go back" arbitrarily. Alternatively, use a named route navigation instead of the generic "go back" functionality. https://expo.github.io/router/docs/features/routing/#layout-settings
