### ISSUE TITLE
[WEB] Attempting to load assets on nested route fails

### ISSUE THREAD

**Issue by ChronSyn** [expo/router#131]
### Summary

Loading assets from a 'base' route (e.g. `/somepath`) works correctly, loading them from `/assets/[path to assets]`.

When attempting to load assets such as fonts from a nested path (e.g. `/nested/123`), the page attempts to load them from `/nested/assets/[path to assets]` which is incorrect and leads to the page not rendering correctly. This only happens if you visit the page URL directly, or refresh the browser while on that page.

This happens with locally-sourced assets (e.g. those hosted inside the `assets` folder) but also with node_modules (e.g. the `expo-google-fonts` packages exhibit the same behaviour).

This test was done on the **web** platform - I haven't explicitly tested on mobile/native as there is no way to refresh the page to trigger the bug.

For clarification, I'm unsure if this is a router-specific issue or a bundler issue. Please move to the appropriate repo if this is not the correct one.

### Minimal reproducible example

https://github.com/ChronSyn/expo-router_bug-report-assetpath

**Comment by wesvance** [comment]
I'm currently experiencing this on expo-router version: 1.0.0-rc5 when using expo-font: 11.0.1

<img width="756" alt="Screenshot 2023-02-05 at 2 49 52 AM" src="https://user-images.githubusercontent.com/25654206/216807769-446ddf49-7f3b-47f7-b23b-59492595cc30.png">
