### ISSUE TITLE
The `redirect` prop on `Stack.screen` doesn't work as described in docs

### ISSUE THREAD

**Issue by jjenzz** [expo/router#132]
### Summary

The docs have [an example for protecting all routes in the `(app)` folder](https://expo.github.io/router/docs/guides/auth) where a code comment reads:

> // When the auth is unavailable (no user signed in), restrict access to all the routes in the `(app)` directory.

During my testing the `redirect` prop will only restrict access to the index page in the app directory here so a sub route within `(app)` will remain active if they click a button to log out on that page.

You can see in the following video that when i click "Sign out" i am not redirected to the sign-up page.

https://user-images.githubusercontent.com/175330/201745971-8cc321a7-66c1-42c4-acb3-10e820c39ec3.mp4

I'm wondering if the cited comment from the docs is incorrect here and whether the expectation is that we would manually add a `<Stack.Screen />` entry for every route? Or perhaps it should be doing what the comment suggests and there is a bug in the router?

Either way, I'd be super grateful of some guidance here on the recommended way to protect routes 🙏 

### Minimal reproducible example

https://github.com/jjenzz/expo-router-bug

**Comment by EvanBacon** [comment]
This property is now deprecated in v3, please use the Redirect component
