### ISSUE TITLE
`useBottomTabBarHeight` doesn't work

### ISSUE THREAD

**Issue by nandorojo** [expo/router#133]
### Summary

```tsx
import {
  useBottomTabBarHeight,
} from '@react-navigation/bottom-tabs'
```

Try calling `useBottomTabBarHeight` in a screen and it'll break, rather than giving you a number.

```ts
Error: Couldn't find the bottom tab bar height. Are you inside a screen in Bottom Tab Navigator?
```

### Minimal reproducible example

Let me know if this is needed.

**Comment by nandorojo** [comment]
I'm embarrassed lol, it was a yarn resolution issue.

**Comment by dani-z** [comment]
@nandorojo, what was the fix? I "started" seeing this too and I am sure it used to work before 😄

**Comment by nandorojo** [comment]
Be sure to remove any references to react navigation from your `package.json` files. You likely have multiple versions installed, resulting in duplicate contexts.

**Comment by dani-z** [comment]
Whoa, that makes sense now. Started seeing this after updating react-navigation to the latest. All works fine if using the expo-router version.
Thanks for pointing this out, @nandorojo! 🙏

**Comment by nandorojo** [comment]
No worries. If you want to upgrade versions, you should use a resolution instead.

**Comment by dani-z** [comment]
Yep, that's exactly what I've just done. Tried first the same version to check if that was the issue in my case too. 👍
