### ISSUE TITLE
3 levels deep nested router inheriting parent layout

### ISSUE THREAD

**Issue by aleedmanath** [expo/router#136]
### Summary

When a `stack` layout is nested inside a parent `tabs` layout, the nested stack screen is showing up under tabs list rather than starting it's own navigation pattern.

### Minimal reproducible example

```
app/ 
   tabs/ 
       stack/ // stack 2
          _layout.js
          index.js
     tab1.js
     tab2.js 
 _layout.js // stack 1
index.js     
```

In above file system, stack 2 is showing up under tabs screen rather than starting its own navigation context.

**Comment by EvanBacon** [comment]
This fs diagram isn't indented correctly so I'm not sure exactly what's going on. Could you provide a more informative description/repro?
