### ISSUE TITLE
IOS Back gesture navigation - Stack

### ISSUE THREAD

**Issue by Remeic** [expo/router#151]
### Summary

Hello! First of all thank you for all the work you do, it's amazing!

I've never developed an app with Expo and React Navigation or Expo Router, I might have made some mistakes, sorry if that's the case.

I was trying to create a shared layout between subcategory pages.
The bug occurs when from the third and last page I try to swipe back, sometimes instead of taking me to the previous screen it takes me directly to the initial one.
I am attaching a demonstration video and a codesanbox, I haven't been able to replicate the problem on the web, but I hope it will still be useful.

I don't know if I'm doing things right, I would mainly like all the screens to have the Stack as a navigator, so that I can take advantage of the gestures and then the header.
Any advice is welcome, even on any errors that don't directly affect the bug

Project structure:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/7298302/205488318-2c9dfa27-2411-437a-8234-de49a73c184a.png">

https://user-images.githubusercontent.com/7298302/205488159-efa29922-b7a6-4ee5-aa60-ff374d7f9665.MP4

I hope I have provided all the necessary information

### Minimal reproducible example

https://codesandbox.io/s/issue-ios-back-gesture-skvp1y

```typescript
// app/_layout.tsx

import { Stack, RootContainer } from 'expo-router'
import { DarkTheme } from '@react-navigation/native'
import { FC } from 'react'

export const Layout: FC = () => {
  return <>
      {/* These props will be applied to the parent NavigationContainer. */}
      <RootContainer theme={DarkTheme} />
      <Stack screenOptions={{ headerShown: false, contentStyle: { paddingTop: 24, paddingBottom: 24, paddingLeft: 8, paddingRight: 8 } }} />
  </>
}
export default Layout
```

```typescript
// app/sub/_layout.tsx

import React, { FC } from 'react'
import { Stack } from 'expo-router'

export const CustomLayout: FC = () => {
  return (<>
      <Stack screenOptions={{
        headerShown: false,
        contentStyle:
        {
          paddingTop: 24,
          paddingBottom: 24,
          paddingLeft: 8,
          paddingRight: 8
        }
      }} />
  </>)
}

export default CustomLayout
```

**Comment by EvanBacon** [comment]
Thanks for the comprehensive issue report. Commenting out the `contentStyle` fixes the behavior, no idea how this is even related to the routing logic. Will investigate more.

**Comment by Remeic** [comment]
@EvanBacon Thank you so much for helping me so quickly.

I hadn't really noticed the double header because I had hidden it, my mistake.

To avoid the antipattern of the two nested stack navigators, could you recommend me an approach to have a shared layout between two screens inside the sub folder that still use the Stack navigator?

I tried to change the layout like this (code below) but going back from screen 3 takes me directly to the first one, I think I misunderstood your advice.

```typescript
import React, { FC } from 'react'
import { Children } from 'expo-router'
import { Typography } from 'src/components'

export const CustomLayout: FC = () => {
  return (<>
      <Typography variant={'button'}>Shared Header</Typography>
      <Children />
    </>)
}

export default CustomLayout
```

Thanks a lot again Evan, and sorry for issue reopening

**Comment by EvanBacon** [comment]
I don't quite understand your issue now. If you update the `app/_layout.js` file to look like this, then there will only be one stack and you should have normal navigation.

```js
import {
  ThemeProvider,
  DarkTheme,
  DefaultTheme,
} from "@react-navigation/native";


import { Slot  } from 'expo-router'


export const Layout = () => {
  return (
    <ThemeProvider value={DarkTheme}>
      <Slot  />
    <ThemeProvider/>
  )
}
export default Layout

```
