### ISSUE TITLE
Expo AuthSession (proxy) sends Android users to 404 route after authenticating

### ISSUE THREAD

**Issue by nderscore** [expo/router#157]
### Summary

When Expo Router is used in conjunction with Expo Auth Session, Android users are sent to the "Unmatched route" (`[...unmatched]`) screen after successfully authenticating.

**Expected Behavior**

Redirection to authentication callback URL schemes triggered by Expo AuthSession should not impact the router.

**Other Notes**

This issue doesn't impact iOS platform.

### Minimal reproducible example

A repository with a minimal reproduction of the bug can be found here:

https://github.com/nderscore/expo-router-auth-demo

To reproduce the issue, follow the instructions in the README, launch the app in an Android emulator, then click on one of the "LOG IN" pressables on any screen, and then complete the authentication flow.

**Comment by EvanBacon** [comment]
The redirect URL wouldn't happen to be [`acme://callback`](https://github.com/nderscore/expo-router-auth-demo/blob/5eec88e9a5d373ddb1e38711a507f17143df225e/components/AuthProvider.tsx#L20) (a nonexistent path) would it? If so, you'll need to add `app/callback.js` or related file which conforms to that path.

**Comment by nderscore** [comment]
The `path` of the redirect URL can be one which resolves to an existing route inside the `app/` directory such as `/a`, set to `/`, a triple-slashed path (`acme:///`), or excluded entirely. In every case, the result seems to be the same.

**Comment by nderscore** [comment]
A bit of a belated, but here's a follow-up on this... :sweat_smile: After upgrading to a newer version of expo-router, I started seeing the unmatched paths, so I have a better idea of what went wrong:

When the `useProxy` setting is enabled, the return path always includes `/expo-auth-session`:

https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/AuthRequest.ts#L165-L168

https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/SessionUrlProvider.ts#L15-L18

I was able to work around it by:

* Using `/` as the path for my redirect URI
* Adding a route for that path (`app/expo-auth.session.tsx`) that renders an empty component
* Then adding it to my custom navigator with a permanent redirect:

```tsx
<Navigator>
  <Navigator.Screen name="expo-auth-session" redirect />
  {/* ... */}
</Navigator>
```

I'm still not sure why I only see this behavior on Android, but I'm also not super familiar with how deep linking works on either platform, using RN or otherwise :stuck_out_tongue:

**Comment by DevYuns** [comment]
I also faced a similar issue. I create `redirectUri `like below.

```ts
const redirectUri = makeRedirectUri({
  scheme: 'doobooexporouter',
  path: '/(auth)/sign-in',
});

// redirectUri : exp://192.168.0.29:19000/--/(auth)/sign-in
```

It works well on `ios` and `web` but not on android. It throw an Unmatched Route 404 error.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/58724686/219610653-c5bbcaf3-b24d-41ae-a325-a8b46922fcd1.png">

**Comment by brahimouindali** [comment]
this happened to me when login using Google it redirects me to /expo-auth-session
I created credentials for a web application in the Google console and I filled in Authorized redirect URIs with the value https://auth.expo.io/@{username}/{slug}

**Comment by EvanBacon** [comment]
auth proxy has been removed in Expo SDK 49 https://blog.expo.dev/expo-sdk-49-c6d398cdf740 the fix would have required changes to the auth proxy service.

**Comment by rajatkantinandi** [comment]
> 



> A bit of a belated, but here's a follow-up on this... 😅 After upgrading to a newer version of expo-router, I started seeing the unmatched paths, so I have a better idea of what went wrong:
> 
> When the `useProxy` setting is enabled, the return path always includes `/expo-auth-session`:
> 
> https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/AuthRequest.ts#L165-L168
> 
> https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/SessionUrlProvider.ts#L15-L18
> 
> I was able to work around it by:
> 
> * Using `/` as the path for my redirect URI
> * Adding a route for that path (`app/expo-auth.session.tsx`) that renders an empty component
> * Then adding it to my custom navigator with a permanent redirect:
> 
> ```tsx
> <Navigator>
>   <Navigator.Screen name="expo-auth-session" redirect />
>   {/* ... */}
> </Navigator>
> ```
> 
> I'm still not sure why I only see this behavior on Android, but I'm also not super familiar with how deep linking works on either platform, using RN or otherwise 😛



> A bit of a belated, but here's a follow-up on this... 😅 After upgrading to a newer version of expo-router, I started seeing the unmatched paths, so I have a better idea of what went wrong:
> 
> When the `useProxy` setting is enabled, the return path always includes `/expo-auth-session`:
> 
> https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/AuthRequest.ts#L165-L168
> 
> https://github.com/expo/expo/blob/5dab530b9485f053841a71351da64e448622e3bb/packages/expo-auth-session/src/SessionUrlProvider.ts#L15-L18
> 
> I was able to work around it by:
> 
> * Using `/` as the path for my redirect URI
> * Adding a route for that path (`app/expo-auth.session.tsx`) that renders an empty component
> * Then adding it to my custom navigator with a permanent redirect:
> 
> ```tsx
> <Navigator>
>   <Navigator.Screen name="expo-auth-session" redirect />
>   {/* ... */}
> </Navigator>
> ```
> 
> I'm still not sure why I only see this behavior on Android, but I'm also not super familiar with how deep linking works on either platform, using RN or otherwise 😛

@nderscore Thanks for the workaround. It works fine. Earlier I was redirecting to `/` route when unmatched route is hit. But is is a better solution.

But I am still wondering how it works fine on iOS without this workaround? Doesn't the iOS return url contain `expo-auth-session`?

@EvanBacon I understand that useProxy is deprecated and recommended way is to use the react native google login library with expo-dev-client. But it is easy to just test on the Expo go app without needing to build a compatible dev client. useProxy makes that simple. Is there a way to still use the Expo go app with the new google login library approach without using useProxy? Otherwise we are slightly hesitant to migrate at this moment.

**Comment by rajatkantinandi** [comment]
Seems like return url = `expo-auth-session` only works on Expo go. But in actual android app the return url can be `oauthredirect` for google and can contain your bundle name in case of Microsoft login.

So, I am putting this code in `[...unmatched]` route to tackle it:
```jsx
// [...unmatched].tsx
import React, { useEffect } from 'react';
import { usePathname, useRouter } from 'expo-router';
import { Platform } from 'react-native';

const AUTH_REDIRECT_PATH_NAMES = ['expo-auth-session', 'oauthredirect', <your-bundle-name>];

export default function Unmatched() {
  const router = useRouter();
  const pathName = usePathname();
  const [isReady, setIsReady] = React.useState(false);

  useEffect(() => {
    if (Platform.OS === 'android' && AUTH_REDIRECT_PATH_NAMES.some((x) => pathName.includes(x))) {
      router.back();
    }
    else {
      setIsReady(true);
    }
  }, [pathName]);

  if (!isReady) {
    return null;
  }

   return (
    // Contents of unmatched page here
    ....
   );
}

```

**Comment by chrisfong** [comment]
> Seems like return url = `expo-auth-session` only works on Expo go. But in actual android app the return url can be `oauthredirect` for google and can contain your bundle name in case of Microsoft login.
> 
> So, I am putting this code in `[...unmatched]` route to tackle it:
> 
> ```js
> // [...unmatched].tsx
> import React, { useEffect } from 'react';
> import { usePathname, useRouter } from 'expo-router';
> import { Platform } from 'react-native';
> 
> const AUTH_REDIRECT_PATH_NAMES = ['expo-auth-session', 'oauthredirect', <your-bundle-name>];
> 
> export default function Unmatched() {
>   const router = useRouter();
>   const pathName = usePathname();
>   const [isReady, setIsReady] = React.useState(false);
> 
>   useEffect(() => {
>     if (Platform.OS === 'android' && AUTH_REDIRECT_PATH_NAMES.some((x) => pathName.includes(x))) {
>       router.back();
>     }
>     else {
>       setIsReady(true);
>     }
>   }, [pathName]);
> 
>   if (!isReady) {
>     return null;
>   }
> 
>    return (
>     // Contents of unmatched page here
>     ....
>    );
> }
> ```

This only redirects back to the previous page, but it doesn't allow the mounted auth-server to inspect the redirect response and exchange the code for an access token. My `useEffect()` on the `response` from `useAuthRequest(...)` never fires with a populated response, only on Android.

Did you ever figure this out? Wondering if @EvanBacon has any insight here?
