### ISSUE TITLE
Document how to test with Jest

### ISSUE THREAD

**Issue by EvanBacon** [expo/router#161]
I haven't gotten around to this yet but we should make a guide for testing with Jest. Perhaps drawing inspiration from other file system-based routers.

- https://github.com/expo/router/discussions/127
- https://github.com/expo/router/issues/155
- https://github.com/expo/router/issues/416

**Comment by ubkh** [comment]
+1 any timescale on this? or any examples to help in the meantime?

**Comment by fddayan** [comment]
+1 🙏

**Comment by nicholasio** [comment]
+1 for this
