### ISSUE TITLE
support deploying to subfolders on web

### ISSUE THREAD

**Issue by erisvaldojunior** [expo/router#165]
### Summary

Our CD serves the website in a subfolder like myurl.com/main/version/.

Before, when using Webpack, we set it on package.json "homepage": "/main/version", as said here https://docs.expo.dev/distribution/publishing-websites/ 

Now, after migrating to Metro Web, seems like this is not read anymore, and when the page is opened console shows an error because it is looking for /bundles/web-...js instead of /main/version/bundles/web-...js.

How should I set the path to metro web?

### Minimal reproducible example

Distribute the website to a subfolder. Opening the page should show a 404 not found error on console when looking for /bundles/web-...js.

**Comment by erisvaldojunior** [comment]
Not serving a webpage to a root url (but to a subfolder instead, like myurl.com/main/version) is also causing issues to Expo Router entry point. cc @EvanBacon

**Comment by erisvaldojunior** [comment]
Hi guys,

Any news regarding this issue? It is quite important for our use case (ability to use Metro Web deploying to subfolders and have expo router working properly).

**Comment by EvanBacon** [comment]
Maybe scheduled for v3. It won't use homepage, opting instead for something like `assetPrefix`. Here's a [work-in-progress](https://github.com/expo/expo/compare/%40evanbacon/cli/assetPrefix?expand=1) branch if you want to pull it and unblock locally.

**Comment by louiechristie** [comment]
Update: 2024

See: https://docs.expo.dev/more/expo-cli/#hosting-with-sub-paths
