### ISSUE TITLE
Allow open modal from tab

### ISSUE THREAD

**Issue by rafael-franca** [expo/router#192]
### Summary

In Tabs.Screen options not has `presentation`, to allow open the screen as Modal. OK, React Navigator not allow this, however, has a tricky can be done (https://stackoverflow.com/questions/68900300/react-navigation-opening-a-modal-from-the-tab-bar), but the `listeners` option not exists in Tabs.Screens.

### Minimal reproducible example

```
<Tabs.Screen
  name="favorites"
  options={{
    headerTitle: "Favorites",
    tabBarLabel: "Favorites",
    tabBarIcon: (props) => <Feather name="heart" {...props} />,
    presentation: 'modal'
  }}
/>
```

**Comment by timoisalive** [comment]
Should opening a modal from `Tabs.Screen` with `presentation: 'modal'` option be working by now?

I can't seem to make it work, and the TSC complains about the non-existing `presentation` prop. 🤷

I'm on `"^1.0.0-rc3"`.

**Comment by darrylyoung** [comment]
@timoisalive Hey. Were you able to make that work? I just started playing around with Expo Router and I'd like to open one of the tabs straight into a modal. I can't seem to figure out how to do it. I'm on `^1.5.3`, by the way. Thanks.

**Comment by timoisalive** [comment]
> 

Yeah, I ended up implementing a custom `TabBar` (https://reactnavigation.org/docs/bottom-tab-navigator#tabbar) with the middle button linking to a modal page. Works no problem, but would still be nice to know how to do it without a custom component!

**Comment by darrylyoung** [comment]
@timoisalive Thanks!
