### ISSUE TITLE
`navigation` prop `undefined` on screens

### ISSUE THREAD

**Issue by GerryWilko** [expo/router#198]
### Summary

Hello,

This project looks fantastic bringing modern web framework conventions to the react-native world love it! Thanks for this Evan and the team.

I have run into an issue when following through the documentation that I'm not sure how to get past. The `navigation` prop on the details screen seems to be `undefined` always for me.

![Screenshot 2023-01-11 at 14 55 43](https://user-images.githubusercontent.com/9151572/211838472-43dbe846-b53f-4f48-80c3-6b13925c618a.png)

I've tried creating a new project from the template to just confirm that it wasnt my project and I am able to recreate it every time. It looks like the prop just isnt being passed through from the Stack layout? I notice that you seem to use `useNavigation('/')` in your demo app and don't seem to use this prop. Is this doc guide just based on an old api version?

Should we use `useNavigation()` to access the navigation controller then?

### Minimal reproducible example

https://github.com/GerryWilko/my-react-app

**Comment by GerryWilko** [comment]
Happy to go through and update the docs if this is indeed just that the docs are out of date 😄

**Comment by EvanBacon** [comment]
Yes, please use `useNavigation()`. Let me know if there are any docs that need updating (probably need to add a note to the migration guide as well). PRs welcome
