### ISSUE TITLE
Access URL search parameters of parent route

### ISSUE THREAD

**Issue by bndkt** [expo/router#203]
### Summary

Given a route `/countries/[countryId]/cities/[cityId]` (as an example), I'd like to access both **countryId** and **cityId** in `[cityId].tsx`. Is this possible? I'm using useSearchParams(), but I can only access **cityId**, the nearest URL segment, not **countryId** from the parent route segment.

### Minimal reproducible example

Create a file `/countries/[countryId]/cities/[cityId].tsx` and include `console.log(useSearchParams())`, it will only output a value for cityId, not for countryId.

**Comment by EvanBacon** [comment]
Cannot repro on the latest:
`/countries/[countryId]/cities/[cityId].tsx`
```
import { useSearchParams } from "expo-router";
import { StyleSheet, Text, View } from "react-native";

export default function Page() {
  const params = useSearchParams();
  console.log("params", params);
  return (
    <View style={styles.container}>
      <View style={styles.main}>
        <Text style={styles.title}>Hello World {JSON.stringify(params)}</Text>
        <Text style={styles.subtitle}>This is the first page of your app.</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    padding: 24,
  },
  main: {
    flex: 1,
    justifyContent: "center",
    maxWidth: 960,
    marginHorizontal: "auto",
  },
  title: {
    fontSize: 64,
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: 36,
    color: "#38434D",
  },
});
```
<img width="1479" alt="Screen Shot 2023-01-16 at 8 54 56 PM" src="https://user-images.githubusercontent.com/9664363/212799724-48cf0ddb-fed2-4e3d-9d47-ea605d13cf75.png">


![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-16 at 20 55 48](https://user-images.githubusercontent.com/9664363/212799815-f5d460cb-aa92-436e-92c9-99ec779143f8.png)

**Comment by bndkt** [comment]
Thanks for checking @EvanBacon ! I'm still investigating and will report back when I solve it. I can confirm that the simple example I wrote in the issue (and that you tested) also works in my setup. But my "real" code still has issues. Currently, it seems to me that when navigating using a direct link to the child route, all seems well, but when I navigate via the navigators (e.g. clicking a tab and then clicking a link in a list), it fails. What made the debugging even harder is that hot reloading and console.log stopped working for me. I traced it back to the upgrade from metro 0.73.2 to 0.73.3, there is an open issue in the metro repo (https://github.com/facebook/metro/issues/877). Don't you experience this problem, since you're already using metro 0.73.7 (or even 0.74.0)?

**Comment by bndkt** [comment]
OK, formulating the above answer helped me to figure it out 🤦‍♂️  The "culprit" was the tab navigator, which doesn't include any parameters which might be set in parent navigation elements. So to stay in the above example, I have a tab navigator within `/countries/[countryId]/` (e.g. to switch between `/countries/[countryId]/cities` and `/countries/[countryId]/rivers`. If I now navigate to `/countries/[countryId]/` and select a tab, within this tab, `countryId` will be lost unless I explicitly specify a `href` within the Tabs.Screen options. I'm going to close this issue but I'd raise the question of whether this works as intended or whether it would be possible (and make sense) to keep the current navigation state intact (e.g. keep the country when switching between "cities" and "rivers" tabs within the country) without the need to explicitly handle the "href" option?

**Comment by Braden1996** [comment]
I ran into this also; intuitively, I'd expect _all_ the params from the URL to be accessible via `useSearchParams()` without intervention. However, as @bndkt pointed out, this doesn't seem to work when a `_layout.tsx` introduces some navigator  (`Stack` or `Tab` for me).

I got around this by adding the following:
```
export default function BottomBarLayout() {
    const params = useSearchParams()

    return (
        <Tabs>
            <Tabs.Screen name="home" initialParams={params} />
            <Tabs.Screen name="search" initialParams={params} />
        </Tabs>
    )
}
```

**Comment by EvanBacon** [comment]
There does appear to be a couple unexpected behaviors that occur when combining tab navigators with dynamic routes (slugs).
