### ISSUE TITLE
Issue with Link component / useRouter() hook

### ISSUE THREAD

**Issue by dani-z** [expo/router#205]
### Summary

Hi,

Just updated my project to the latest `expo-router` and noticed 2 weird things happening when using the `<Link>` component or the `useRouter()` hook:

My example:
```js
<Link
    key={item.id}
    href={{ params: { item }, pathname: "./[license]" }}
  >
```
1. I am getting a TS error 

```Type '{ params: { item: { id: string; title: string; text: string; url: string; }; }; pathname: string; }' is not assignable to type 'string | (HrefObject & string)'.```

Params should allow passing any object afaik.

3. When reading the `params` on the next page using
```js
const params = useSearchParams();
```
I am getting the encoded value.

Example
```js
href={{ params: { title: "Hello world" }, pathname: "./[license]" }}

// Next page
const params = useSearchParams();

// No TS inference; not sure if this is also expected.
console.log(params.title) // Hello%20world
```

### Minimal reproducible example

As explained in the code above. Please let me know if you would need a repo.
Thanks 🙏

**Comment by EvanBacon** [comment]
fixed in 0.0.44
