### ISSUE TITLE
Using `<SplashScreen />` doesn't prevent it from hiding

### ISSUE THREAD

**Issue by jjenzz** [expo/router#212]
### Summary

The `SplashScreen` component doesn't prevent the splash screen from hiding.

I have just tried this with a brand new expo router project (`v1.0.0-rc1`) but it is also not working using `v0.0.45`.

### Video demonstrating issue

https://user-images.githubusercontent.com/175330/213757127-11c35dcc-3edd-4864-94ec-754dcd32e6ce.mp4

### Expected result

I expected the splash screen to remain open forever.

### Actual result

The splash screen closes.

### Minimal reproducible example

```sh
npx create-react-native-app -t with-router
```

### app.json

```json
{
  "expo": {
    "scheme": "acme",
    "web": { "bundler": "metro" },
    "icon": "https://github.com/expo/expo/blob/master/templates/expo-template-blank/assets/icon.png?raw=true",
    "splash": {
      "image": "https://github.com/expo/expo/blob/master/templates/expo-template-blank/assets/splash.png?raw=true",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    }
  }
}
```

### app/index.js

```jsx
import { View } from "react-native";
import { SplashScreen } from "expo-router";

export default function Home() {
  return (
    <>
      <SplashScreen />
      <View style={{ flex: 1, backgroundColor: "red" }} />
    </>
  );
}
```

**Comment by jjenzz** [comment]
i've narrowed it down to this line https://github.com/expo/router/blob/main/packages/expo-router/src/views/Splash.tsx#L49

so i presume this is a dev mode double render issue?

**Comment by Braden1996** [comment]
@EvanBacon With an app that has a nested hierarchy, I've found the ancestor's `<SplashScreen />` unmount happens before the descendant has a chance to mount their own `<SplashScreen />` component.

Right now, I'm getting round this by overriding `SplashScreen._popEntry` to use a similar `requestAnimationFrame` before hiding the SplashScreen here: https://github.com/expo/router/blob/main/packages/expo-router/src/views/Splash.tsx#L92

Wondered if you have any thoughts about this?

**Comment by EvanBacon** [comment]
@Braden1996 this is essentially what we do in rc2 at the root-most splash screen component

**Comment by jjenzz** [comment]
we are having to apply a similar change to @Braden1996 even after installing rc3

**Comment by silberistgold** [comment]
I am still encountering this issue in 1.5.3 and think this should be reopened. Can anyone else confirm? @Braden1996 mind to share your workaround here?

**Comment by JoshBot-Debug** [comment]
I have the same issue expo-router version 1.5.3

Calling <SplashScreen /> does not keep the splash screen up. This is really bothersome...

@silberistgold take a look at the link @Braden1996 mentioned. I'm going to try it later today, let me know if you've found a way to persist the splashscreen. I'll let you know if I find a fix.

**Comment by silberistgold** [comment]
As @Braden1996 pointed out, wrapping `SplashScreen._popEntry` does prevent the splash screen from hiding to early.

As far as I can tell this works because it delays the removal of an entry from the global splash stack (which you can see in `Splash.tsx`) until rendering of the next frame, at which point another `SplashScreen` component further down in the rendering tree has had the chance to push its entry and prevent the splash from hiding.

Right now I am using `patch-package` to wrap the body of `SplashScreen._popEntry` in `requestAnimationFrame`. The patched code (in `Splash.tsx` in the expo-router package) looks like this:
```
SplashScreen._popEntry = (entry: string) => {
  requestAnimationFrame(() => {
  const index = globalStack.indexOf(entry);
  if (index !== -1) {
    globalStack.splice(index, 1);
  }
  if (globalStack.length === 0) {
    SplashScreen.hideAsync();
  }});
};
```

**Comment by JoshBot-Debug** [comment]
> As @Braden1996 pointed out, wrapping `SplashScreen._popEntry` in `requestAnimationFrame` does prevent the splash screen from hiding to early.
> 
> As far as I can tell this works because it delays the removal of an entry from the global splash stack (which you can see in `Splash.tsx`) until rendering of the next frame, at which point another `SplashScreen` component further down in the rendering tree has had the chance to push its entry and prevent the splash from hiding.
> 
> Right now I am using `patch-package` to wrap the body of `SplashScreen._popEntry` in `requestAnimationFrame`. The patched code (in `Splash.tsx` in the expo-router package) looks like this:
> 
> ```
> SplashScreen._popEntry = (entry: string) => {
>   requestAnimationFrame(() => {
>   const index = globalStack.indexOf(entry);
>   if (index !== -1) {
>     globalStack.splice(index, 1);
>   }
>   if (globalStack.length === 0) {
>     SplashScreen.hideAsync();
>   }});
> };
> ```

@silberistgold Thank you for replying so quickly! I tried this and it worked (saved my day). Thank you again!
