### ISSUE TITLE
Failing to properly bundle assets in Windows using Web

### ISSUE THREAD

**Issue by bencreynolds** [expo/router#213]
### Summary

I have been trying all day to get expo-router to work, with no luck. I am using a Windows PC on Windows 10 and I am attempting to run the app on the web using "expo start --web" or "yarn web".

I am following the tutorial directly. This is was mentioned and "fixed" in this issue: https://github.com/expo/router/issues/120

The error first presents itself when attempting to navigate to the "Details" screen. For a very tiny brief moment, I can see the LogBox error appear, but I am unable to make out what the error is before the screen flashes to white. I do not know what causes the initial error, but the app completely crashes once it attempts to load the LogBox error message and I believe this is because it is attempting to render an image inside the LogBox (probably the warning symbol).

In the web console, I see the following error: 
> Uncaught Error: Image: asset with ID "1" could not be found. Please check the image source or packager.

There are no errors before that one appears.

### Minimal reproducible example

package.json

```js
{
  "main": "index",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "47.0.13",
    "expo-constants": "~14.0.2",
    "expo-linking": "~3.3.0",
    "expo-router": "1.0.0-rc1",
    "expo-splash-screen": "~0.17.4",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9"
  },
  "resolutions": {
    "metro": "^0.73.7",
    "metro-resolver": "^0.73.7"
  },
  "name": "my-react-app",
  "version": "1.0.0",
  "private": true
}
```

app.json

```js
{
  "expo": {
    "scheme": "acme",
    "web": {
      "bundler": "metro"
    }
  }
}
```

bable.config.js

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "@babel/plugin-proposal-export-namespace-from",
      "react-native-reanimated/plugin",
      require.resolve("expo-router/babel"),
    ],
  };
};
```

index.js

```js
import "expo-router/entry";
```

app/index.js
```js
import { Text, View } from "react-native";
import { Link } from "expo-router";


export default function Home() {
    return (
        <View>
            <Text>Home Page</Text>
            <Link href="/details">Go to Details...</Link>
        </View>
    );

}
```

app/details.js

```js
import { View, Text } from "react-native";

export default function Details() {


    return (
        <View>
            <Text>
                Details Screen
            </Text>
        </View>
    );
}
```

app/_layout.js

```js
import { Stack } from "expo-router";

export default function Layout() {
    return <Stack />;
}
```

**Comment by SleeplessByte** [comment]
Can confirm the same thing happening. I think it's failing on the back arrow image.

**Comment by EvanBacon** [comment]
Does your copy of expo cli have the patch from https://github.com/expo/expo/pull/19935 ? Should be in `node_modules/@expo/cli/build/src/start/server/metro/withMetroMultiPlatform.js`

**Comment by SleeplessByte** [comment]
It does not. 

`@expo/cli` is provided by `"expo@npm:^47.0.13"`. It is fixed at version `"@expo/cli": 0.4.11`, which [the lastest published version (19 days ago)](https://www.npmjs.com/package/@expo/cli?activeTab=versions). This version according to the [explore tab on npm](https://www.npmjs.com/package/@expo/cli?activeTab=explore) also doesn't have the patch applied.

I then went ahead and ran the Yarn 3 equivalent of `patch-package`:
- `yarn patch`
- make the edit in
- `yarn patch --commit`

The following patch was generated:

```diff
diff --git a/build/src/start/server/metro/withMetroMultiPlatform.js b/build/src/start/server/metro/withMetroMultiPlatform.js
index fce6417d8f3fa72f92f195a4cd3a50dd4950b8fd..18651a9c3a5eac17cf86482592b754b7cc380226 100644
--- a/build/src/start/server/metro/withMetroMultiPlatform.js
+++ b/build/src/start/server/metro/withMetroMultiPlatform.js
@@ -4,6 +4,7 @@ Object.defineProperty(exports, "__esModule", {
 });
 exports.withWebResolvers = withWebResolvers;
 exports.withMetroMultiPlatformAsync = withMetroMultiPlatformAsync;
+exports.shouldAliasAssetRegistryForWeb = shouldAliasAssetRegistryForWeb;
 var _fs = _interopRequireDefault(require("fs"));
 var _path = _interopRequireDefault(require("path"));
 var _resolveFrom = _interopRequireDefault(require("resolve-from"));
@@ -108,12 +109,12 @@ function withWebResolvers(config, projectRoot) {
             }, moduleName, platform);
             // Replace the web resolver with the original one.
             // This is basically an alias for web-only.
-            if (platform === "web" && (result == null ? void 0 : result.type) === "sourceFile" && typeof (result == null ? void 0 : result.filePath) === "string" && result.filePath.endsWith("react-native-web/dist/modules/AssetRegistry/index.js")) {
+            if (shouldAliasAssetRegistryForWeb(platform, result)) {
                 // @ts-expect-error: `readonly` for some reason.
                 result.filePath = assetRegistryPath;
             }
             return result;
-        }, 
+        },
     ]);
 }
 async function withMetroMultiPlatformAsync(projectRoot, config, platformBundlers) {
@@ -144,4 +145,20 @@ function withMetroMultiPlatform(projectRoot, config, platformBundlers) {
     return withWebResolvers(config, projectRoot);
 }
 
-//# sourceMappingURL=withMetroMultiPlatform.js.map
\ No newline at end of file
+function normalizeSlashes(p) {
+    return p.replace(/\\/g, '/');
+}
+
+function shouldAliasAssetRegistryForWeb(
+    platform,
+    result
+) {
+    return (
+        platform === 'web' &&
+        result?.type === 'sourceFile' &&
+        typeof result?.filePath === 'string' &&
+        normalizeSlashes(result.filePath).endsWith(
+            'react-native-web/dist/modules/AssetRegistry/index.js'
+        )
+    );
+}
```

This can be placed in `.yarn/patches` as `@expo-cli-npm-0.4.11-db0f659386.patch`

Add the following to `"resolutions"` in the `package.json`. 
```json
    "@expo/cli@0.4.11": "patch:@expo/cli@npm%3A0.4.11#./.yarn/patches/@expo-cli-npm-0.4.11-db0f659386.patch"
```

Now apply the patch: `yarn install`
Cleared the metro cache using `yarn start -c`.

Now it works.

**Comment by bencreynolds** [comment]
Thank you for this information. Could we please get this patch pushed into the master branch? It's quite a headache to deal with at the moment.

**Comment by nikshirobokov** [comment]
Yes, please add this to the main branch. I don't really understand how to connect the patch to the project.

**Comment by SleeplessByte** [comment]
@nikshirobokov my instructions should be quite clear, if you don't want to wait for this to be fixed on the published package.

**Comment by bencreynolds** [comment]
> > @SleeplessByte  No idea how to get yarn patch. My version of yarn doesn't support it and I am 100% up to date.
> 
> I don't know what you mean with "how to get yarn patch".
> 
> You need to be on Yarn 3+, and because react-native doesn't support PnP you must use the node-modules nodeLinker.
> 
> If you're on the latest classic Yarn, you can use:
> 
> `yarn set version latest` to upgrade and then run `yarn install`. It will automatically use the correct nodeLinker. Finally, copy the contents i posted to the location i mentioned, add resolution, and then run install again.

Yeah, I just get:

```
>yarn patch
yarn run v1.22.19
error Command "patch" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by SleeplessByte** [comment]
> yarn run v1.22.19

You are not on the latest version.

**Comment by nikshirobokov** [comment]
Yes, @SleeplessByte right. I was missing a version update for yarn.

I used [this article](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-the-yarn-package-manager-for-node-js) to update yarn.
Then copied [the patch code that provided above](https://github.com/expo/router/issues/213#issuecomment-1399750501). 
![image](https://user-images.githubusercontent.com/40653060/216434613-8bac14f9-0532-4ed3-aaf6-9cc6f658c9a2.png)
![image](https://user-images.githubusercontent.com/40653060/216434778-b155e3da-e0ba-4a69-a565-d4a2075cf063.png)

Then I executed the `yarn install` command in project folder and this issue was fixed.

Thanks :)

**Comment by nikshirobokov** [comment]
@SleeplessByte How can I use yarn berry to build with EAS CLI ?  I get an error when trying to make a build `eas build`

**Comment by SleeplessByte** [comment]
@nikshirobokov that is a good question. 

You can first try to set the `yarn` version via the [yarn `eas.json` option](https://docs.expo.dev/build-reference/eas-json/#yarn) (documentation linked), and if that doesn't work, try it by switching (installing) version via [`eas-build-pre-install`](https://docs.expo.dev/build-reference/npm-hooks/) (documentation linked) hook. 

Can you let me know if either works? I'll be needing this soon.

**Comment by nikshirobokov** [comment]
@SleeplessByte 
> set the `yarn` version via the [yarn `eas.json` option](https://docs.expo.dev/build-reference/eas-json/#yarn)

There is fast answer: no. I tried it and this doesn't work. 
Build logs: 
```
Installing node v16.19.0
Downloading and installing node v16.19.0...
[stderr] Downloading https://nodejs.org/dist/v16.19.0/node-v16.19.0-linux-x64.tar.xz...
[stderr] #                                                                          2.3%
[stderr] ######################################################################    98.5%
[stderr] ###############################################################
[stderr] ######### 100.0%
[stderr] Computing checksum with sha256sum
[stderr] Checksums matched!
Now using node v16.19.0 (npm v8.19.3)
changed 110 packages in 6s
12 packages are looking for funding
  run `npm fund` for details
[stderr] npm notice 
[stderr] npm notice New major version of npm available! 8.19.2 -> 9.4.1
[stderr] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.1>
[stderr] npm notice Run `npm install -g npm@9.4.1` to update!
[stderr] npm notice
[stderr] 
Installing yarn@3.4.1
[stderr] npm ERR! code ETARGET
[stderr] npm
[stderr] ERR! notarget No matching version found for yarn@3.4.1.
[stderr] npm ERR! notarget In most cases you or one of your dependencies are requesting
[stderr] npm ERR! notarget a package version that doesn't exist.
[stderr] 
[stderr] npm ERR! A complete log of this run can be found in:
[stderr] npm ERR!     /home/expo/.npm/_logs/2023-02-05T18_16_21_504Z-debug-0.log
Failed to install Yarn 3.4.1
npm exited with non-zero code: 1
Error: Failed to install Yarn. Make sure you specified the correct version in eas.json.
```

> via [eas-build-pre-install](https://docs.expo.dev/build-reference/npm-hooks/)

I haven't tried it, but thanks a lot for the hint.

**Comment by SleeplessByte** [comment]
Yeah, yarn 2+ cannot be installed directly like that. EAS will need to change its infrastructure slightly to make that work via the prop.

Only the set version thing works I think, as that's what yarn says in their own documentation!

**Comment by nikshirobokov** [comment]
As for this current issue. @SleeplessByte @bencreynolds I just saw that the expo packages [have been updated](https://github.com/expo/expo/commit/1815e2eaad8c753588c7b1eb74420174a28e01f4). 

To solve #213, it is enough to resolve version 0.5.0 for @expo/cli in the "resolutions" block of your `package.json`:
```
"resolutions": {
	"@expo/cli": "^0.5.0"
},
```
![image](https://user-images.githubusercontent.com/40653060/216845644-9c1fc698-806a-4b48-8da7-f480ab85af3c.png)

**Please use it for your health.**

**Comment by SleeplessByte** [comment]
@nikshirobokov thank you; yes, that includes the patch I posted, so you're good to go!

FWIW, I did try out the build hooks solution myself, because Yarn 3, even with `node_modules` linker, is fast on my system. You can see the result here:

![Successful steps on EAS](https://user-images.githubusercontent.com/1964376/216868921-0001b6ca-3db7-46c6-94ec-be3c8ba0a7f1.png)

**Comment by EvanBacon** [comment]
SDK 48 is out and the fix is upstream.
