### ISSUE TITLE
[Breaking Change] `navigation.reset` no longer works

### ISSUE THREAD

**Issue by jjenzz** [expo/router#214]
### Summary

we were using `navigation.reset` previously (`v0.0.39`) to reset the stack but this no longer works in latest (`v1.0.0-rc1`).

i've seen [the following documentation regarding `resetRoot`](https://expo.github.io/router/docs/migration/react-navigation/navigation-container/#resetroot) but we have cases where we want to reset to something other than root.

https://user-images.githubusercontent.com/175330/213831337-ba16f250-9d23-4831-9851-f89dadcc8961.mp4

### Minimal reproducible example

```jsx
// index.js
import { View, Button } from "react-native";
import { useRouter } from "expo-router";

export default function HomeScreen() {
  const router = useRouter();
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Button title="Page two" onPress={() => router.push("/page-two")} />
    </View>
  );
}
```

```jsx
// page-two.js
import { View, Button } from "react-native";
import { useNavigation } from "expo-router";

export default function PageTwoScreen() {
  const navigation = useNavigation();
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Button
        title="Reset to Page Three"
        onPress={() => navigation.reset({ index: 0, routes: [{ name: "/page-three" }] })}
      />
    </View>
  );
}
```

**Comment by jjenzz** [comment]
sods law, i figure it out as soon as i post 🙈 

looks like the `name` format has changed. it used to include the segments e.g. `(app)/home` but `home` is all that's needed now.

**Comment by master429** [comment]
> sods law, i figure it out as soon as i post 🙈
> 
> looks like the `name` format has changed. it used to include the segments e.g. `(app)/home` but `home` is all that's needed now.

How do you write the parameters inside routes? Please describe it in detail. Thank you
