### ISSUE TITLE
When viewed on the web, @expo/vector-icons is not displayed in the nested router.

### ISSUE THREAD

**Issue by t0m0120** [expo/router#216]
### Summary

When I try to open the Nested URL directly on the web(http://localhost:19000/memo/1), 
I get the following error and the icon does not appear.

It seems to be going to the nested URL to look for the Icon file, any solution?

![image](https://user-images.githubusercontent.com/34805701/213897647-540e5920-7e70-4b9d-b3b7-dd7356dd2d09.png)

### Minimal reproducible example

You can reproduce the following by webbuilding the following and opening the URL(`localhost/nest/1` ).

https://github.com/t0m0120/expo-router-check-nested-icon

**Comment by EvanBacon** [comment]
Possibly related to https://github.com/expo/router/issues/131

**Comment by gorbypark** [comment]
I am facing the same issue.  Just to add some more context, this appears to only be related to vector-icons (or at least it doesn't happen with all assets) because the back icon arrow of a stack header loads fine from the correct assets folder without the extra path like vector-icons has.

**Comment by bencreynolds** [comment]
I have this issue as well. Digging a bit deeper it appears even if you preload the font assets in the root component it won't recognize that when reloading in a nested screen. 

For now I'm just dealing with this by only using Ionicons, which appears to be already pre-loaded elswhere by a dependency in my project (i think react-navigation uses these).

**Comment by AhmedrAshraf** [comment]
@gorbypark vector-icons not displaying in my side, is it working good in your side on web ?

**Comment by EvanBacon** [comment]
Fixed by https://github.com/expo/expo/pull/22094 which is in 49 alpha.
