### ISSUE TITLE
[v1.0.0-rc1] cannot go back after a `<Redirect />` in `(app)`

### ISSUE THREAD

**Issue by jjenzz** [expo/router#221]
### Summary

when trying to access a contacts screen in our `(app)` directory, we `<Redirect />` to a permissions screen if user hasn't granted permissions to access their contacts. if they decide to close this permissions screen, executing `router.back()` on close press throws the following error:

> The action 'GO_BACK' was not handled by any navigator

we expected that it would take them back to the screen prior to the redirect (in our case, the home screen).

the video below demonstrates that clicking "Send" takes you to a send screen that immediately redirects to a permissions page. clicking back from there, or after granting permissions throws the error.

https://user-images.githubusercontent.com/175330/214570466-d666e124-27dd-485b-9565-a3f864fb0b53.mp4

### Minimal reproducible example

https://github.com/jjenzz/expo-router-back-bug

**Comment by EvanBacon** [comment]
Thanks for the repro and detailed report, investigating possible solutions now.

**Comment by jjenzz** [comment]
i thought is was a bug given that the same setup outside the `(app)` directory behaves as we expected.

are there different assumptions made between `/_layout.tsx` and `(app)/_layout.tsx` stacks?

https://user-images.githubusercontent.com/175330/214864502-987868f8-83e7-4487-9d8b-beef749e1ae1.mp4
