### ISSUE TITLE
Ancestor search params are not available

### ISSUE THREAD

**Issue by Braden1996** [expo/router#224]
### Summary

Hey! I recently started migrating our app ([Attio](https://attio.com)) to `expo-router` but am running into a small issue.

Our app navigation tree looks something like this:
---
- (authed)
  - [workspaceId]
    - (bottom-tabs)
      - home.tsx
      - search.tsx 
    - _layout.tsx 
  - _layout.tsx 
  - workspaces.tsx 
- auth
  - sign-in.tsx 
- _layout.tsx
---

The file `/(authed)/_layout.tsx` navigates the user to `{pathname: "/(authed)/workspace-forbidden"}` if they have no existing stored selected workspace, and into `{ pathname: "/(authed)/[workspaceId]", params: {workspaceId: workspace.id} }` otherwise.

The problem now is that `useSearchParams` calls within components inside `/(authed)/[workspaceId]` don't always contain the param `workspaceId`. I'm not too sure why this is happening? Is it by design?

I found a similar issue here: https://github.com/expo/router/issues/203
In my project, `/(authed)/[workspaceId]/_layout.tsx` creates a `Stack` and `/(authed)/[workspaceId]/(bottom-tabs)/_layout.tsx` creates a Tab. However, I can't seem to solve this. Also, called `setParams` far down the hierarchy doesn't seem to bubble up as expected.

### Minimal reproducible example

Example is described above; not able to construct a repo demonstrating this but can do later if needed :)

**Comment by Braden1996** [comment]
In the meantime, I'm using this (which is pretty janky):

```ts
import {usePathname, useSegments} from "expo-router"
import {matchDynamicName} from "expo-router/build/matchers"
import * as React from "react"

import {RouterSegments} from "./useRouter"

export function useSegmentValues() {
    const pathname = usePathname()
    const segments = useSegments()
    const pathnameSegments = pathname.split("/")
    const segmentValues = React.useMemo<Record<string, string>>(
        () =>
            segments.reduce((acc, segment, i) => {
                const dynamic = matchDynamicName(segment)

                return dynamic ? {...acc, [segment]: pathnameSegments[i]} : acc
            }, {}),
        [pathnameSegments, segments]
    )

    return segmentValues
}

export function useSegmentValue(segment: RouterSegments) {
    const segmentValues = useSegmentValues()

    return segmentValues[`[${segment}]`] as string | undefined
}
```

**Comment by EvanBacon** [comment]
The intended behavior is to emulate a browser, where the params and current URL are global. This goes a bit against the [grain of React Navigation](https://reactnavigation.org/docs/nesting-navigators/#each-screen-in-a-navigator-has-its-own-params) so there do seem to be a few unexpected edge cases. I'll investigate further.

**Comment by bndkt** [comment]
Hey @EvanBacon, I've built a minimal reproducible example for this one, as I think it's quite a blocker. You can find the example here: [https://github.com/bndkt/expo-router-params](https://github.com/bndkt/expo-router-params). I took the "tabs" template from Expo 48 and basically renamed the `(tabs)` folder to `[id]`, to simulate that it's not just a group of tabs but tabs in a dynamic route.

So the nav structure is:

- index
- [id]
- - index
- - two

On the home screen, I added a link to `/foo/`:

![16B4B0B2-4637-41DB-B9B9-BDE834E7089B_1_102_o](https://user-images.githubusercontent.com/91166910/218299138-c3b60ccc-706d-48a2-9f69-8a3a5c8ed10e.jpeg)

Following the link brings you to `[id]/index`, and the `id` (foo) is correctly logged and displayed in the headline:

![799742A8-7F5A-4D44-A487-55369720254E_1_201_a](https://user-images.githubusercontent.com/91166910/218299163-6cfe6525-538f-4212-9bd2-2a7f2f2fc6af.jpeg)

Switching to the second tab (`[id]/two`), you see that `id` is lost (seen in the console.log and in the headline where id is empty):

![92736769-43C4-4D15-A7A5-FFD60F107AFB_1_201_a](https://user-images.githubusercontent.com/91166910/218299203-cd7b0887-ddd2-423b-b5f4-365978ef6744.jpeg)

Hope that helps with locating the problem, let me know when I can do more to help.

**Comment by bndkt** [comment]
@EvanBacon just tested with expo-router@1.0.0-rc7 and can confirm it works now! Thank you!!!
