### ISSUE TITLE
ReactDOM.render is no longer supported in React 18.

### ISSUE THREAD

**Issue by nikshirobokov** [expo/router#225]
### Summary

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

![image](https://user-images.githubusercontent.com/40653060/214861621-172f1951-c480-4f34-bdca-079bde274c7a.png)

This issue has already been discussed for the Expo SDK: https://github.com/expo/expo/issues/18485

For a temporary solution, a workaround was found with the creation of its own file index.js: https://github.com/expo/expo/issues/18485#issuecomment-1345574189 - this works for a regular Expo project. How to rewrite index.js for Expo Router so that it supports React 18 ?

### Minimal reproducible example

1. Create project with https://expo.github.io/router/docs#quick-start
2. Run `yarn start`
3. Open Web
4. Open "Console" in the DevTools

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/expo/expo/issues/18485
