### ISSUE TITLE
Typescript Link for expo-router

### ISSUE THREAD

**Issue by ScreamZ** [expo/router#229]
### Summary

Accessibility props are always required, shoudln't

<img width="627" alt="Screenshot 2023-01-29 at 12 29 50" src="https://user-images.githubusercontent.com/6640835/215323134-dc9c327d-a817-4893-be4e-1db7a978e189.png">
shouldn't

### Minimal reproducible example

Not needed here

**Comment by EvanBacon** [comment]
Can't reproduce this.
