### ISSUE TITLE
Replace does not replace

### ISSUE THREAD

**Issue by SleeplessByte** [expo/router#233]
### Summary

Using the [demo app](https://github.com/expo/router/tree/main/apps/demo) as a basis, if you run this on Android, you can only go back if you're logged out. This likely means that the `replace` doesn't actually replace, but still pushes.

This _also_ happens on web. I have not tested if this happens on iOS with back swipe.

### Minimal reproducible example

https://github.com/expo/router/tree/main/apps/demo (no changes)

- open the demo app
- press sign in
- press back (it redirects back to signed in, both on web and android)

This shouldn't happen as `replace` is supposed _replace_ the pushstate / url

**Comment by atanaskanchev** [comment]
+1 on this one, replace adds to the stack, rather than replacing the previous page
```
const { replace } = useRouter();

replace('/')
```

**Comment by skaionedev** [comment]
+1 same issue - can't implement proper authentication flow

**Comment by EvanBacon** [comment]
Given "repro" isn't directly applicable as the replace action here spans multiple navigators which [isn't supported](https://github.com/expo/router/blob/b3bd70e7305f31fc94d4a4f92645ebeeb3e27847/packages/expo-router/src/link/useLinkToPath.ts#L105-L106). From what I understand, React Navigation doesn't have good support for batching multiple actions. It shouldn't be impossible but it would be a new feature.

**Comment by SleeplessByte** [comment]
> [...] React Navigation doesn't have good support for batching multiple actions. It shouldn't be impossible but it would be a new feature.

Myeah. In non-expo-router world whenever I need this, I basically need to "craft" the entire state myself and then "reset" to that state, in order to do this correctly. Batching actions is finicky at best.

It would be in a very similar style to the code that's already in the file.

**Comment by buraks** [comment]
I am having the same problem. In my it's very simple, I have only one stack, not nested layouts.

_layout.tsx --- this has `<Stack />`
index.tsx --- home page
chat/[id].tsx --- chat page
[...unmatched].tsx --- does `router.replace('/');`

I have a dynamic link that opens the app if it's already installed. When I press the link, I used to get the default unmatched page, I have customized the unmatched page to redirect to home. First, I tried with `<Redirect href={'/'} />;` it didn't work either. Now when I go to the deep link, I get the Home page getting added to the stack instead of replace replacing the history. If I do that multiple times, I have multiple Home pages, I could go back and get the Home page again.

This happens on iOS.

**Comment by Reltik** [comment]
I was bite by this today! Replace doesn't replace! My users logged out and they can simple go back!

**Comment by Reltik** [comment]
> > I was bite by this today! Replace doesn't replace! My users logged out and they can simple go back!
> 
> Same thing here, is there any workaround?

I had to check in each screen if the user was still logged in, if not redirects them to the login screen. I have done this using a custom context which checks if there's any auth token setted, because sign off clears it.

**Comment by yonihod** [comment]
Any workarounds we are getting bitten by this as well

**Comment by Raduc4** [comment]
> Any workarounds we are getting bitten by this as well

I was getting this because I had a nested layout structure. Replace didn't want to work because of this. I had something like (home)/events/[event].tsx. Also try removing <Slot /> if you use it

**Comment by Raduc4** [comment]
This somehow helped me. Put it in /(tabs)/home
```
 const navigation = useNavigation();

  React.useEffect(
    () =>
      navigation.addListener("beforeRemove", (e) => {
        // Prevent default behavior of leaving the screen
        e.preventDefault();

        // Prompt the user before leaving the screen
      }),
    [navigation]
  );
```

**Comment by ahmamedhat** [comment]
Same here happening for me.

**Comment by ahmamedhat** [comment]
This little trick fixes it for me

**Comment by ahmamedhat** [comment]
This trick fixes it for me when you first login: </br> </br> `router.back();` </br> `router.replace(RouteNames.HOME);`
