### ISSUE TITLE
Link type should include className prop

### ISSUE THREAD

**Issue by johnslemmer** [expo/router#236]
### Summary

I'm trying to using NativeWind styling with `expo-router`.  And the `className` prop is used for that. The `Link` component provided by `expo-router` doesn't define `className` as a valid prop and so the type checking fails.

### Minimal reproducible example

<img width="404" alt="image" src="https://user-images.githubusercontent.com/18610918/215618761-920af67f-adbb-4285-beb8-97e81faf282c.png">

However, this actually still works.  The text in my app still shows up white.  It is just the type checking that fails.

**Comment by johnslemmer** [comment]
Made this quick component as a workaround  for now.

```js
import React from "react";
import { Link as ExpoLink } from "expo-router";

type Props = React.ComponentProps<typeof ExpoLink> & { className: string };

const Link: React.FC<Props> = (props) => {
  return <ExpoLink {...props} />;
};

export default Link;
```

**Comment by EvanBacon** [comment]
`className` is not a real property on `Link`.

**Comment by johnslemmer** [comment]
Hey @EvanBacon thanks for getting back to me.  I get that `className` isn't a real property on `Link`.  And I get my solution works for me and my setup.  But I also spent a little time digging around and trying to understand this more, and how nativewind is managing typescript with regard to merging in the `className` prop to certain react native components (see [here](https://www.nativewind.dev/getting-started/typescript) and [here](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/types.d.ts)).

However, what I notice is weird is the types emitted from `expo-router` will negate this merging that nativewind is trying to do.  Specifically this line in `expo-router/build/link/Link.d.ts` is the culprit:

```ts
export declare const Link: React.ForwardRefExoticComponent<Pick<Props, "children" | "replace" | "style" | "key" | "target" | "lang" | "tabIndex" | "href" | "allowFontScaling" | "ellipsizeMode" | "lineBreakMode" | "numberOfLines" | "onLayout" | "onTextLayout" | "onPress" | "onPressIn" | "onPressOut" | "onLongPress" | "testID" | "nativeID" | "maxFontSizeMultiplier" | "adjustsFontSizeToFit" | "minimumFontScale" | "suppressHighlighting" | "disabled" | "selectable" | "selectionColor" | "textBreakStrategy" | "dataDetectorType" | "android_hyphenationFrequency" | "accessible" | "accessibilityActions" | "accessibilityLabel" | "accessibilityRole" | "accessibilityState" | "accessibilityHint" | "accessibilityValue" | "onAccessibilityAction" | "accessibilityLabelledBy" | "accessibilityLiveRegion" | "importantForAccessibility" | "accessibilityElementsHidden" | "accessibilityLanguage" | "accessibilityViewIsModal" | "onAccessibilityEscape" | "onAccessibilityTap" | "onMagicTap" | "accessibilityIgnoresInvertColors" | "accessibilityLevel" | "hoverStyle" | "hrefAttrs" | "asChild"> & React.RefAttributes<Text>>;
```

I don't understand typescript enough to understand why this massive `Pick` is being generated from this codebase (because it isn't in [Link.tsx](https://github.com/expo/router/blob/main/packages/expo-router/src/link/Link.tsx) at all).  But I'm curious if this can somehow be transitioned to something less restrictive.  Which would allow nativewind's documented typescript workaround to be effective in this case.

Curious your thoughts, but obviously super low priority.

**Comment by johnslemmer** [comment]
nm, I think I answered my question.  This is the real culprit https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L784

And because `expo-router`'s types are being generated with rightfully no knowledge of nativewind's `className` addition then it will never end up in the `Pick` list.

**Comment by johnslemmer** [comment]
I opened up a discussion on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64163

**Comment by johnslemmer** [comment]
Hey @EvanBacon I got the @types/react package updated to allow for this to work https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64166.  Should I submit a PR to update the dependency in expo-router?  Or will this happen automatically with a dependabot sort of thing?

**Comment by johnslemmer** [comment]
Turns out this commit actually changed the outputting types enough to make this work: https://github.com/expo/router/commit/2650499f7fb74962149e5942ce64361401f90277#diff-143532969ec3c27780a566f06f654c4b2fa2e2edfda4c92a36ba1630d5e9125fR50

If something ever happens and this issue creeps back in then all that would need to happen is updating the @types/react package to 18.0.28 or above.
