### ISSUE TITLE
[v1.0.0-rc3] Cannot reset to `navigation.getState()` value

### ISSUE THREAD

**Issue by jjenzz** [expo/router#249]
### Summary

when we want our unlock screen to appear we reset the navigation stack to the unlock screen and preserve their previous navigation state using `navigation.getState()`. on successful passcode entry we reset the navigation back to their previous state.

this used to work for us in an older version of `expo-router` but we are unable to reset the navigation back to their previous state in the latest version. the following error occurs:

> The action 'RESET' with payload (omitted) was not handled by any navigator

here is a video of the minimal reproduction supplied below:

https://user-images.githubusercontent.com/175330/216452685-233ca47a-0583-4045-827e-4fb6616ef37a.mp4

### Minimal reproducible example

https://github.com/jjenzz/expo-nav-state

**Comment by jjenzz** [comment]
@EvanBacon i see you labelled this `React Navigation`. is this something i should be raising with that team instead?

**Comment by EvanBacon** [comment]
@jjenzz I can reproduce the error but I can't reproduce this desired behavior working with other versions. I'm not entirely sure how to proceed. Have you tried using the [recommended mechanism](https://reactnavigation.org/docs/navigation-actions#reset) for resetting the navigation state?

**Comment by jjenzz** [comment]
> I can't reproduce this desired behavior working with other versions. 

oh interesting! it looks like it might have something to do with nested stacks in that case, we introduced them recently. if i remove the `_layout.js` in `(app)` then it works as expected. 

some further poking around the react-navigation docs lead me to the following: 

- `navigation.getState`
    > This method returns the state object of **the navigator which contains the screen**
    > https://reactnavigation.org/docs/navigation-prop/#getstate
- `navigationRef.resetRoot`
    > Unlike the `reset` method, this acts on the root navigator instead of navigator of the currently focused screen.
    > https://reactnavigation.org/docs/navigation-container/#resetroot

so it sounds like the state we are preserving using  `navigation.getState()` doesn't include the state of all nested stacks which would explain why a nested stack broke it. 

in case anyone else stumbles across all this, getting the state from the root navigation via expo's `useRootNavigation` hook instead works.

will close 👍
