### ISSUE TITLE
modal deep link breaks all modals

### ISSUE THREAD

**Issue by trin4ik** [expo/router#27]
First, its great work! amazing tool. Modal from deep link opens like stack screen, like says in docs (https://expo.github.io/router/docs/guides/modals)
but after then:
1. this modal after close and try to open -- opens like stack screen.
2. all modals (if they be in one stack) opens like stack screens.

**Comment by EvanBacon** [comment]
Could you please provide a minimal reproducible example?

**Comment by trin4ik** [comment]
> Could you please provide a minimal reproducible example?

its reproducible in demo app, but yes, in one-two days, i provide example.

**Comment by trin4ik** [comment]
https://user-images.githubusercontent.com/839633/193445587-312d7f3c-32b5-40f7-9ab1-84ceeca3ecb9.MP4

https://github.com/trin4ik/expo-router-modal-bug

i use 0.0.19 version, because in next versions we have no nullsafe check `href.pathname` https://github.com/expo/router/blob/main/packages/expo-router/src/link/href.ts#L9 
and when opening app with deep, href is undefined

**Comment by trin4ik** [comment]
its not are `expo-router` bug/problem, its `react-navigation` feature. solution 4 my problem -- add `initialRouteName` to linking config. 
expo-router CAN render modal as modal on deep links. which means this statement is false:
https://expo.github.io/router/docs/guides/modals/#:~:text=Now%20we%27ll%20create%20a%20modal%20which%20adds%20a%20back%20button%20when%20the%20modal%20has%20lost%20its%20previous%20context%20and%20must%20be%20presented%20as%20a%20standalone%20page.

https://user-images.githubusercontent.com/839633/193453207-b778e757-eaf2-4875-bdd9-e7234f20a7e1.MP4

just need modify `treeToReactNavigationLinkingRoutes` in [/src/getLinkingConfig.ts](https://github.com/expo/router/blob/main/packages/expo-router/src/getLinkingConfig.ts), I will prepare PR

**Comment by trin4ik** [comment]
I think we're done here

**Comment by ws998116** [comment]
@trin4ik Can you please explain how to use `initialRouteName` to achieve this functionality? I am having the problem you described, where modals appear as a stack screen when opened from a deep link. I have tried setting `initialRouteName` in both the root `_layout.js` (tab nav) as well as the stack `_layout.js` but the results are the same.

**Comment by zRelux** [comment]
Same how did you get on fixing this?

**Comment by zRelux** [comment]
@ws998116 Managed to find a way to do this.
Basically the link open another route and then that route checks a param and redirects to the modal.

```
  const router = useRouter();
  const { join } = useLocalSearchParams();
  const navigationState = useRootNavigationState();
  const pathname = usePathname();

  useLayoutEffect(() => {
    const checkRoute = () => {
      if (join) {
        if (!navigationState?.key) {
          return;
        }

        if (!pathname.includes('join-trip')) {
          router.setParams({ join: '' });

          router.push(`/view/join-trip/${join}`);
        }
      }
    };

    checkRoute();
  }, [join, navigationState.key, pathname, router]);

```
