### ISSUE TITLE
`usePathname()` with deep nested routes

### ISSUE THREAD

**Issue by brunocrosier** [expo/router#277]
### Summary

i'm trying to use `usePathname()` inside a dynamic route (e.g. `app/blog/[...title].tsx`) and noticed that this hook will always return `/blog` in this scenario even if the href is `/blog/some/deep/nested/route`

### Minimal reproducible example

As per above

**Comment by EvanBacon** [comment]
Can't reproduce given the following:

`app/blog/[...rest].tsx`
```
import { usePathname } from "expo-router";
import { StyleSheet, Text, View } from "react-native";

export default function Page() {
  console.log("path", usePathname());
  return null;
}
```

**Comment by brunocrosier** [comment]
which route did you visit @EvanBacon ? was it deeply nested? was the value of usePathname correct? i can try to create a reproducible example of necessary

**Comment by EvanBacon** [comment]
@brunocrosier I visited `/blog/1/2/3` `/blog/1` and `/blog`

**Comment by brunocrosier** [comment]
Hey @EvanBacon sorry I should have created a repro. 

Here we go: https://github.com/brunocrosier/deep-nested-layout-pathname-repro

## Expectation
When I click on "Humpty", "Humpty Dumpty", or "Humpty Dumpty Sat", then `[...blog].tsx` would render `/humpty`, `/humpty/dumpty`, or `/humpty/dumpty/sat` (these are the `href`s used in `index.tsx`)

## Current behaviour
`[...blog].tsx` always sees the pathname as `/`


Apologies again, let me know if anything is unclear

**Comment by EvanBacon** [comment]
Thanks for the repro, I'll investigate.

**Comment by brunocrosier** [comment]
amazing, thank you!
