### ISSUE TITLE
1.0.0-rc6 package is missing the build folder

### ISSUE THREAD

**Issue by bndkt** [expo/router#280]
### Summary

The "build" folder is missing in the 1.0.0-rc6, hence making it unusable. Probably a problem while publishing?

### Minimal reproducible example

- Remove node_modules
- Install expo-router@1.0.0-rc6

**Comment by EvanBacon** [comment]
<img width="817" alt="Screen Shot 2023-02-14 at 11 25 08 AM" src="https://user-images.githubusercontent.com/9664363/218811820-136193cc-fbe9-44ce-9a5f-4833553b8668.png">

```json
{
  "name": "expo-router",
  "version": "1.0.0-rc6",
}
```
