### ISSUE TITLE
Android universal linking not working as expected

### ISSUE THREAD

**Issue by ak151997galaxy** [expo/router#282]
### Summary

hello!
in our app we have tab navigator and 5 stacks .
when i deeplink a url using http / https (npx uri-scheme open http://galaxycard.in/shopping --android) then it redirects to home. 
on the other side when using (npx uri-scheme open galaxycard.debug://shopping --android) it open the required screen.

**Comment by EvanBacon** [comment]
The issue is that we don't have a mechanism for setting the URL to handle incoming redirects from Android. We could possibly remove the requirement to have a hard-coded link and just parse whatever URL comes in.
