### ISSUE TITLE
Whenever i click on link to move to other page using stack navigation it gives me this erorr.

### ISSUE THREAD

**Issue by ShakeelKhalid1913** [expo/router#289]
Whenever i click on link to move to other page using stack navigation it gives me this erorr.
![image](https://user-images.githubusercontent.com/93911372/217561070-14f273b9-387d-4e2f-92ec-b822e41a96da.png)

![image](https://user-images.githubusercontent.com/93911372/217561284-587bcd92-40ee-4023-8821-68e2dd400d6e.png)
![image](https://user-images.githubusercontent.com/93911372/217561321-e924293b-c400-4e45-9138-2bd496d8f7ee.png)
![image](https://user-images.githubusercontent.com/93911372/217561374-c637759c-09a1-4af1-b64a-c06a09afac07.png)
![image](https://user-images.githubusercontent.com/93911372/217561421-cc41153c-92bb-41a1-a3ab-6bd0e81e7d48.png)

I dont know what the problem. **need help**

_Originally posted by @ShakeelKhalid1913 in https://github.com/expo/router/discussions/261_
      

anyone have  idea
?

**Comment by EvanBacon** [comment]
Can you please share the repro in a format that I can download

**Comment by ShakeelKhalid1913** [comment]
> Can you please share the repro in a format that I can download

Hi... 
[https://github.com/ShakeelKhalid1913/expo_demo](url) check this out

**Comment by EvanBacon** [comment]
Fixed in expo@48.0.0

**Comment by ShakeelKhalid1913** [comment]
> Fixed in expo@48.0.0

Thanks
