### ISSUE TITLE
expo-router/entry cannot be found

### ISSUE THREAD

**Issue by JClackett** [expo/router#29]
Hello!

Love this so much! Just tried following the docs exactly and got this when running "expo start"

```
error: Error: While resolving module `expo-router/entry`, the Haste package `expo-router` was found. However the module `entry` could not be found within the package. Indeed, none of these files exist:
```

any ideas?

**Comment by fristyr** [comment]
Can you try npx expo start --clear ?

**Comment by JClackett** [comment]
Same thing :( 

```
error: Error: While resolving module `expo-router/entry`, the Haste package `expo-router` was found. However the module `entry` could not be found within the package. Indeed, none of these files exist:

  * `/Users/jclackett/Apps/Examples/expo-router/entry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
```

**Comment by Albert-Gao** [comment]
you can try it out on my branch :)

https://github.com/Albert-Gao/expo-router-web-try-out/tree/web-auth-flow

might need to swap the wrapper in the layout component to nativeStack for mobile, but you can just clean the app folder and start from fresh :)

do NOT use the master branch

**Comment by agrittiwari** [comment]
![image](https://user-images.githubusercontent.com/51356497/193227480-959d937b-0d9c-4275-a5ed-dac8750e6f11.png)
What may be the work around ?!

**Comment by dennisgoncearuc-tomtom** [comment]
Are you guys sure you did not forget to follow this step ?
https://expo.github.io/router/docs/intro#configure-the-babel-plugin
I accidentally forgot about it and had the same error
And do not forget to start project with n**px expo start --clear**

**Comment by fristyr** [comment]
Are you guys sure you did not forget to follow this step ?
https://expo.github.io/router/docs/intro#configure-the-babel-plugin
I accidentally forgot about it and had the same error
And do not forget to start project with npx expo start --clear

**Comment by JClackett** [comment]
Definitely have this!

**Comment by EvanBacon** [comment]
Ensure the following:

- Using `"expo": "~46.0.13"` or greater.
- The file `node_modules/expo-router/entry.js` exists.
- You are starting your project with Expo CLI (npx expo start). React Native CLI won't work.

Workaround

- Try creating a file `index.js` which has `import 'expo-router/entry'`. Then set `"main": "./index"` in your `package.json`.

**Comment by JClackett** [comment]
Yeah weird, I definitely have all of those things!

The entry file is definitely in my node_modules so I don't understand how it can't find it

<img width="356" alt="Screenshot 2022-10-01 at 12 28 28" src="https://user-images.githubusercontent.com/12549124/193405312-89582266-850a-45d9-af54-012e164ce099.png">


Still just getting: 
```
error: Error: While resolving module `expo-router/entry`, the Haste package `expo-router` was found. However the module `entry` could not be found within the package. Indeed, none of these files exist:
 * `/Users/jclackett/Apps/Examples/expo-router/entry(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
```

It is trying to find the entry file in the root directory though...is that right? I think it might be something to do with metro? if I force it to load from node_modules:

```
import "./node_modules/expo-router/entry";
```
I then get: 

```
error: Error: While resolving module `expo-router/build/splash`, the Haste package `expo-router` was found. However the module `build/splash` could not be found within the package. Indeed, none of these files exist:
```

But I honestly have no idea how any of this stuff works...

**Comment by JClackett** [comment]
Here's the repo I'm using: https://github.com/JClackett/expo-router

**Comment by EvanBacon** [comment]
Ya, the `name` in the root `package.json` cannot be `expo-router` or any other node module name in the project. The root package.json takes priority over any other package installed in the node modules folder. After you're unblocked by that `app/index.tsx` will collide with `app/(tab)/index.tsx` as they both resolve to `/`.
