### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by DrMisQ** [expo/router#302]
### Summary

when using expo start --web everything works fine Icons show
<img width="189" alt="Screenshot 2023-02-22 at 10 06 51 AM" src="https://user-images.githubusercontent.com/37986642/220548551-5784556b-f1fe-47bb-be04-01b520ed1fbd.png">

After bundling using npx expo export -p web and deploying it,  Icons show as an empty square
<img width="189" alt="Screenshot 2023-02-22 at 10 07 03 AM" src="https://user-images.githubusercontent.com/37986642/220548524-c17548b4-b1bb-4c03-bf16-38b4e309f0b9.png">

### Minimal reproducible example

app.json
`{
  "expo": {
    "scheme": "acme",
    "web": {
      "bundler": "metro"
    },
    "name": "TestExpo",
    "slug": "TestExpo"
  }
}
`

index.js
`import "expo-router/entry";`

**Comment by EvanBacon** [comment]
This is not a valid reproducible demo.

**Comment by DrMisQ** [comment]
I'm using same exact code with  (npx create-expo-app@latest -e with-router) just import icons from '@expo/vector-icons'
build and deploy (web)

**Comment by thierryskoda** [comment]
I'm having the same issue. `dist/__node_modules/@expo/vector-icons` is empty

**Comment by sapjax** [comment]
same issue here.
I wonder whether it's caused by `metro-resolver` override.
