### ISSUE TITLE
useSearchParams()/useLocalSearchParams() and Tab navigator

### ISSUE THREAD

**Issue by bndkt** [expo/router#337]
### Summary

I'm still a bit confused about useSearchParams() vs. useLocalSearchParams(), and I am not sure they work as intended, especially in combination with the Tab navigator. I apologize that I'm unable to pinpoint the exact problem because I'm not sure what the intended behavior is. I hope we can clarify it and see if a fix is needed. I tried to make the example as simple as possible and compiled some screenshots of the observed behavior:

<img width="1063" alt="CleanShot 2023-03-02 at 08 58 50@2x" src="https://user-images.githubusercontent.com/91166910/222303557-1da9e1c8-e3ec-42db-ada4-b026fc576f62.png">

Nav structure is:

- index
- two
- two2
- countries
- - index
- - [country]
- - - index
- - - two

When I navigate from **index** to **countries** and from there to a country (e.g.**/countries/us**), both useSearchParams and useLocalSearchParams return **us** for **country**. When navigating to **countries/us/two** using the tab, useLocalSearchParams is empty. When navigating to this route directly (e.g. via direct link from the index page or via deep link), useLocalSearchParams is filled as well. When navigating to the route **/two2**, the screen from **countries/us/two** is still mounted but now gets undefined for **country** for both useSearchParams and useSearchParams (which I visualize with the alert). When navigating to **/two** from the first tab, at least useLocalSearchParams() is still available.

PS: The reason there are two routes **/two** and **/two2** is that I could not navigate from the tab navigator to **/two**, because there is also a route **two** within the Tab navigator and it would always go there and not to the root **/two**. This seems to be a separate issue?

### Minimal reproducible example

I created a repo here: https://github.com/bndkt/expo-mre

**Comment by EvanBacon** [comment]
I'm not sure I understand the issue. Would you be willing to replicate the flow using our new testing library, [example](https://github.com/expo/router/blob/0d2f0b2d952e34b1c297bfafdde1243a4f828f89/packages/expo-router/src/__tests__/navigation.test.tsx#L149-L185). This would help me better determine if the behavior you're describing is unexpected or not.

**Comment by erquhart** [comment]
@EvanBacon I'm seeing this consistently as well, a nested tab navigator always has empty local search params, unless I explicitly set the href on the screens (which causes state to reset when navigating away from the tab and returning to it).

**Comment by YKSing** [comment]
Same thing happens here, but if you set the `href` in every `Tabs.Screen`, somehow it works.

**Comment by hbriese** [comment]
Setting `initialParams` on the `Tabs.Screen` also works.
The issue seems to be related to the screen needing to be focussed for local params to work.
I've experienced screens rendering with empty params initially before re-rendering with the correct params, but global params always shows the correct params & href
