### ISSUE TITLE
Support web.favicon in Metro for web

### ISSUE THREAD

**Issue by blakevidebeck** [expo/router#348]
### Summary

After installing expo-router it appears app not longer reads from app.json and favicon and app title do not get used.

Before adding expo router: 
![Screenshot 2023-03-06 at 6 05 47 AM](https://user-images.githubusercontent.com/55563466/222975008-2777dfa8-2316-4ae7-a844-93237d3886e5.png)

After adding expo router:
![Screenshot 2023-03-06 at 6 10 32 AM](https://user-images.githubusercontent.com/55563466/222975229-49a73d09-354d-4a41-b501-e1be3c21936f.png)

### Minimal reproducible example

1. Create a new expo 48 project. 
2. Favicon and title is there
3. Follow installation steps for expo router
4. Favicon and title  is gone

Alternatively you can you use `npx create-expo-app@latest -e with-router` and the same issue is present

**Comment by EvanBacon** [comment]
favicon is not currently supported in metro web. You can use `public/favicon.ico` as a workaround.

**Comment by blakevidebeck** [comment]
Ah okay thanks and what would be the best approach to set the document title?

**Comment by rokebrand** [comment]
I also need to update the title, any update on a workaround to that?

**Comment by alexandre1921** [comment]
@rokebrand and @blakevidebeck a workaround for that was adding an index.html on the public folder and then I edited the title.

**Comment by EvanBacon** [comment]
Document title is a different issue. You can technically use a Stack navigator to set the title—the undocumented “expo-router/head” component will be the official system once it’s more refined. Just use it like you would any other web head component.

**Comment by blakevidebeck** [comment]
Awesome thanks for the answers! 
What we ending up doing is using the stack.screen "options" and setting title and headerTilte respectively. 

When reloaded it appears it does flash briefly and shows "undefined", but this should be fine for now until the official system is released and documented 👍

**Comment by EvanBacon** [comment]
expo/head and favicon support are both included in SDK 49
