### ISSUE TITLE
react-native-url-polyfill/auto is not applied

### ISSUE THREAD

**Issue by MaxAst** [expo/router#373]
### Summary

I use [react-native-url-polyfill](https://github.com/charpeni/react-native-url-polyfill), which is necessary to use `@supabase/supabase-js` for auth in react native. I import react-native-url-polyfill/auto at the top of my root `_layout.tsx` file, but it doesn't seem to be applied, as I keep getting a `URL.hostname is not implemented` error when running the app. This worked fine without expo-router

### Minimal reproducible example

```
import "react-native-url-polyfill/auto";

import { useState, useEffect } from "react";
import { Slot } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: AsyncStorage as any,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});

export default function RootLayout() {
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    supabase.auth.getSession().then((result) => {
      setSession(result.data.session);
    });

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });
  }, []);

  return (
      <Slot />
  );
}
```

**Comment by MaxAst** [comment]
it randomly started working, not sure what fixed it though. Maybe stale cache

**Comment by MaxAst** [comment]
correction: this issue exists once a session with supabase is established. The error doesn't appear when we're signed out

**Comment by lk11601** [comment]
@MaxAst hey mate, were you able to get supabase authentication to work with expo router?

**Comment by MaxAst** [comment]
hey @lk11601 , no unfortunately not

**Comment by EvanBacon** [comment]
Try adding to your index.js file. There’s no reason this should be an issue with Expo router. The only related thing I can think of is the import order changing.

**Comment by EvanBacon** [comment]
We've fixed this and added upstream built-in support for the URL in v50
