### ISSUE TITLE
Error: While resolving module `expo-router/entry`

### ISSUE THREAD

**Issue by TheEhsanSarshar** [expo/router#375]
### Summary

I got this error when running an expo router project

```Error: While resolving module `expo-router/entry`, the Haste package `expo-router` was found. However the module `entry` could not be found within the package. Indeed, none of these files exist:```

### Minimal reproducible example

I'm using expo-router template generated by

```npx create-expo-app@latest -e with-router```

**Comment by francisleigh** [comment]
@TheEhsanSarshar I'm getting something similar (see screenshot) when running my expo app within a turbo repo. 

What did you do to progress with your bug?

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-03 at 08 54 28](https://user-images.githubusercontent.com/10357801/229707314-cf4de9a9-7a24-4dbf-a178-2e61bbbe79f1.png)

**Comment by TheEhsanSarshar** [comment]
check if you have `app` directory with correct files.
