### ISSUE TITLE
@babel/plugin-proposal-export-namespace-from is not mentioned in documentation

### ISSUE THREAD

**Issue by nanyaDev** [expo/router#383]
### Summary

I recently tried converting an app over from `react-navigation` to `expo-router` by following the official documentation. When I tried to run my app I got the following error:

```
error: node_modules/react-native-reanimated/lib/index.web.js: ~/myapp/node_modules/react-native-reanimated/lib/index.web.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
```

I noticed the `@babel/plugin-proposal-export-namespace-from` mentioned in the error is present in the `babel.config.js` of the template created by `npx create-expo-app@latest -e with-router`. Adding this to my app fixed the build issues. However, it's not mentioned in the section on [Configure the Babel config](https://expo.github.io/router/docs/#configure-the-babel-plugin) in the docs.

### Minimal reproducible example

If you delete `@babel/plugin-proposal-export-namespace-from` from `babel.config.js` in the example app, it doesn't work.

**Comment by EvanBacon** [comment]
This is only required for Reanimated which is not required for expo-router, you can find the Babel setup in the reanimated guide.

**Comment by goltra** [comment]
Hi, I think this should be explained. For example, I tried to implement drawer and follow instructions from 
[web](https://expo.github.io/router/docs/migration/react-navigation/drawer)
In this web doesn't mention anytime you should have `@babel/plugin-proposal-export-namespace-from` and it should be in babel.config.js plugins section.

**Comment by nanyaDev** [comment]
**Update**: Expo SDK 49 seems to eliminate the need to add `@babel/plugin-proposal-export-namespace-from`. From the [blogpost](https://blog.expo.dev/expo-sdk-49-c6d398cdf740):

> If you have @babel/plugin-proposal-export-namespace-from in your package.json dependencies, you can remove it. It is now included in babel-preset-expo.
