### ISSUE TITLE
Tab options freezeOnBlur not preventing inactive tab from re-rendering

### ISSUE THREAD

**Issue by moxen-dev** [expo/router#384]
### Summary

I want to not trigger a new re-render of the inactive tabs users left behind. When user browser from Tab 1 to Tab 2, I do not want Tab 1 to render again. 

React Navigation presents an option for that that is named as [`freezedOnBlur`](https://reactnavigation.org/docs/bottom-tab-navigator#freezeonblur). Accordingly to their documentation: 

"Boolean indicating whether to prevent inactive screens from re-rendering. Defaults to `false`. Defaults to `true` when `enableFreeze()` from `react-native-screens` package is run at the top of the application."

So I tried to pass the aforementioned property to the Tab component of Expo Router but the inactive tab kept been re-rendered.

### Minimal reproducible example

```typescript
export default function TabLayout() {
  console.log("🖨️ rendering Tab Layout");

  useEffect(() => {
    return (() => {
      console.log("🗑️ TabLayout unmounted");
    });
  }, []);

  const screenOptions: BottomTabNavigationOptions = {
    title: "Title",
    tabBarLabel: "Label",
    tabBarShowLabel: true,
    tabBarLabelPosition: "below-icon",
    tabBarLabelStyle: { fontSize: 12 },
    tabBarIconStyle: { width: 24, height: 24 },
    tabBarBadge: 0,
    tabBarBadgeStyle: { backgroundColor: "tomato" },
    tabBarAccessibilityLabel: "Accessibility Label",
    tabBarTestID: "Test ID",
    tabBarButton: (props) => <Pressable {...props} />,
    tabBarActiveTintColor: "tomato",
    tabBarInactiveTintColor: "gray",
    tabBarActiveBackgroundColor: "white",
    tabBarInactiveBackgroundColor: "white",
    tabBarHideOnKeyboard: true,
    tabBarItemStyle: { backgroundColor: "white" },
    tabBarStyle: { backgroundColor: "white" },
    tabBarBackground: () => <></>,
    lazy: true,
    unmountOnBlur: false, // default is false !important
    freezeOnBlur: true, // default is false
  };

  const sceneContainerStyle = {
    backgroundColor: "transparent",
  };

  return (
    <Tabs
      initialRouteName="tab1"
      detachInactiveScreens={true}
      sceneContainerStyle={sceneContainerStyle}
      screenOptions={screenOptions}
    >
      <Tabs.Screen name="tab1" />
      <Tabs.Screen name="tab2/index" />
    </Tabs>
  );
};
```

**Comment by moxen-dev** [comment]
https://user-images.githubusercontent.com/93292309/225310772-eb3e4d87-f106-4615-a7fb-07f5bd594c5d.mov

**Comment by moxen-dev** [comment]
I can prevent it from re-rendering if I allow it to be unmounted by setting `unmountOnBlur: true` but this comes with a warning message from React Navigation docs:

"Normally, we don't recommend enabling this prop as users don't expect their navigation history to be lost when switching tabs. If you enable this prop, please consider if this will actually provide a better experience for the user."

**Comment by moxen-dev** [comment]
For now, I am switching modals to Gorhom's Bottom Sheet Modals to avoid this re-render.

**Comment by EvanBacon** [comment]
This repro doesn't work, I imagine something on the screens is forcing a rerender, perhaps `useGlobalSearchParams`? Feel free to re-open with a fully reproducible example and I'll try again.
