### ISSUE TITLE
`useFocusEffect` not working as expected in dev client

### ISSUE THREAD

**Issue by brunocrosier** [expo/router#390]
### Summary

`useFocusEffect` only runs once when running in Expo Go or development client

Possibly related? https://github.com/expo/expo/issues/20088

### Minimal reproducible example

https://github.com/brunocrosier/expo-test-app

**Comment by EvanBacon** [comment]
This cannot be fixed in this repo, I recommend tracking in https://github.com/expo/expo/issues/20088
