### ISSUE TITLE
Cannot load @expo-google-fonts

### ISSUE THREAD

**Issue by rborn** [expo/router#402]
### Summary

I'm trying to use the @expo-google-fonts package as per docs - https://expo.github.io/router/docs/guides/root-layout#loading-fonts -  but neither in dev or exported (local dist) is not working.

It somehow seems to try to load the fonts from node modules but is redirected to `/` ?

![Screenshot](https://user-images.githubusercontent.com/406409/226635439-c7baeb20-9f39-4add-9312-a6cf780df8a8.jpg)

Nothing special, I just follow the docs :)

Any idea? Thank you 🙏

### Minimal reproducible example

app/_layout.js

```
import { useFonts, Inter_500Medium } from '@expo-google-fonts/inter';

const Layout = () => {
    const [fontsLoaded] = useFonts({
        Inter_500Medium
    });

    if (!fontsLoaded) {
        return <Text>meh</Text>;
    }

    return <Text>It works!</Text>;   
};
```

**Comment by EvanBacon** [comment]
Are you using Expo 48? Also which OS are you running on?

**Comment by rborn** [comment]
Hi, I'm really sorry, I should have mentioned it.
Yes, Expo 48, router 1.3.0, every other module up to date.

It's web and it's in a monorepo. I tried to replicate it in a non-monorepo test and it seems to work. 
This is a  monorepo example that shows the issue: https://github.com/rborn/expo-router-google-fonts-issue

Maybe I'm doing something wrong? 🙏

**Comment by EvanBacon** [comment]
Fixed by https://github.com/expo/expo/pull/22094 which is part of Expo 49 alpha.
