### ISSUE TITLE
Multiple files match the route name "./(tabs)/_layout".

### ISSUE THREAD

**Issue by olalonde** [expo/router#405]
### Summary

I'm getting this error when building with webpack:

```
Multiple files match the route name "./(tabs)/_layout".
```

See https://github.com/olalonde/expo-bug-multiple-route-matches

It works when using `"bundler": "metro"` in `app.json`.

### Minimal reproducible example

https://github.com/olalonde/expo-bug-multiple-route-matches

**Comment by EvanBacon** [comment]
Webpack is not supported in Expo Router (only Metro), we have plans to add support and will instead continue to build out Metro for web.
