### ISSUE TITLE
Generated routes from showing in drawer

### ISSUE THREAD

**Issue by gigq** [expo/router#411]
### Summary

There was a fix for generated routes (sitemap, 404) not to show in tabs, but looks like the issue still exists in drawers.

<img width="766" alt="Screenshot 2023-03-22 at 8 51 17 AM" src="https://user-images.githubusercontent.com/64186/226925375-1907e0f4-eff9-4b39-93c0-352abe2a9286.png">

### Minimal reproducible example

[app.zip](https://github.com/expo/router/files/11040698/app.zip)

**Comment by EvanBacon** [comment]
React Navigation doesn't provide a prop to prevent rendering the drawer items like it does with tab bars

**Comment by gigq** [comment]
No worries, for anyone else dealing with this I found the best solution is to render your own drawer content so you can customize what shows.

```
export default function RootLayout() {
  const dimensions = useWindowDimensions()
  const router = useRouter()

  type Props = {}

  const Sidebar: React.FC<Props> = () => {
    return (
      <DrawerContentScrollView>
        <DrawerItem
          label="Index"
          onPress={() => {
            router.push("/")
          }}
        />
        <DrawerItem
          label="Second"
          onPress={() => {
            router.push("/second")
          }}
        />
      </DrawerContentScrollView>
    )
  }

  return (
    <ThemeProvider value={DarkTheme}>
      <Drawer
        id="drawer"
        screenOptions={{
          drawerStyle: {
            width: 240,
            height: dimensions.height,
          },
          drawerType: dimensions.width >= 768 ? "permanent" : "slide",
        }}
        drawerContent={Sidebar}
      ></Drawer>
    </ThemeProvider>
  )
}
```
