### ISSUE TITLE
[Layout children]: Too many screens defined. Route "x" is extraneous

### ISSUE THREAD

**Issue by hakanolgun** [expo/router#424]
### Summary

I'm getting the error in the title and I couldn't figure out how to handle it. 
Router works correctly. But the warning shows up on initial render and every time i navigate to a screen.

### Minimal reproducible example

This is my navigation structure:
```
app/
    _layout.js            <-- This is a Stack Navigator which has only one screen named "(tabs)"
    [...missing].js
    index.js               <-- This component only has a Redirect component to the episodes/ route
    (tabs)/
       _layout.js         <-- This is a Tab navigator which has two tabs in it. "episodes" and "favorites"
       favorites.js
       episodes/
           _layout.js    <-- This is a Stack navigator which has two screen in it.
           index.js
           episode.js   <-- This is the screen that error message indicates as extraneous.
```

    "expo": "~48.0.9",
    "expo-router": "^1.0.0-rc5",

**Comment by hakanolgun** [comment]
I've found the problem. Inside the tab navigation, there is another screen called episode. I forgot to delete it :)
Still, I think it would be helpful to keep this post because there wasn't much explanation for this error.

**Comment by Piyush903** [comment]
Hi, I am facing the same issue any updates on this cause I have no extra screen called on? Warning [Layout children]: Too many screens defined. Route "more/product" is extraneous. flow is like this 
app/
  (auth)
    login.js
    (tabs)
      _layout.js <- with Tabs
      home/
        index.js <- will be presented with tabs
       _layout.js <- with Stack
      more/
           item.js
           checkserial.js
           serialdata.js
           product.js
         _layout.js <- with Stack

**Comment by mwondhaf** [comment]
This happened to me as well but I noticed I wasn't exporting the screens as default

**Comment by mr-ryan-james** [comment]
> This happened to me as well but I noticed I wasn't exporting the screens as default

This fixed it for me :) thanks @mwondhaf

**Comment by jothamardel** [comment]
> This happened to me as well but I noticed I wasn't exporting the screens as default

This fixed it. It's flows Nextjs file-based routing. Thanks @mwondhaf .

**Comment by pammu453** [comment]
This fixed  :) thanks @mwondhaf
