### ISSUE TITLE
Folder APP

### ISSUE THREAD

**Issue by wtcosta** [expo/router#426]
### Summary

Is it possible to change the path and name of the default 'app' folder?

### Minimal reproducible example

![Captura de tela de 2023-03-24 23-52-52](https://user-images.githubusercontent.com/8378135/227684945-7bcb489d-c959-483a-8d9a-86f71f07b8c1.png)

**Comment by EvanBacon** [comment]
nope, cite https://github.com/expo/router/discussions/309

**Comment by wtcosta** [comment]
I was able to change it by including the following instruction in babel.config.js
process.env.EXPO_ROUTER_APP_ROOT = "../../src/container";

**Comment by SpecialAro** [comment]
> I was able to change it by including the following instruction in babel.config.js process.env.EXPO_ROUTER_APP_ROOT = "../../src/container";

On version 1.2.2 I'm able to do this suggestion but If I update to the latest (1.4.3) it doesn't work. Nevertheless, I'm finding real hard to find the changelog of this project (if there is any - please - link me the file).

**Comment by SpecialAro** [comment]
> On version 1.2.2 I'm able to do this suggestion but If I update to the latest (1.4.3) it doesn't work. Nevertheless, I'm finding real hard to find the changelog of this project (if there is any - please - link me the file).

After taking some time to find why this wasn't working, I noticed that this lines were removed from "entry.js" on PR #404:
```
// We add this elsewhere for rendering
const HeadProvider =
  typeof window === "undefined" ? React.Fragment : Head.Provider;

...

<HeadProvider>
   <ExpoRoot context={ctx} />
</HeadProvider>
 ```
 Once I put those back it works again for me. Of course, I've never contributed on this codebase so I don't now which implications this could have and why it was removed in the first place - maybe @EvanBacon can clarify it?

Nevertheless, I'll keep on trying to find a solution (or event make a PR to bring back those lines if @EvanBacon agrees).

Let me know if I should stop commenting on this close issue or even raise a new one, my sincere apologies if that is the case.
