### ISSUE TITLE
Can't bundle with Webpack

### ISSUE THREAD

**Issue by MLaidlawScott** [expo/router#429]
### Summary

I cannot bundle my app for deployment with Webpack. 

With the minimal setup created by following the [quickstart](https://expo.github.io/router/docs/#quick-start), changing the bundler to webpack, and adding @expo/webpack-config, the app will not work.

Initially, the following error is observed:

```
Module not found: Can't resolve '..\..\app'
  10 |   typeof window === "undefined" ? React.Fragment : Head.Provider;
  11 |
> 12 | const ctx = require.context(process.env.EXPO_ROUTER_APP_ROOT);
     |            ^
  13 |
  14 | // Must be exported or Fast Refresh won't update the context
  15 | export function App() {
```

Upon following the [troubleshooting](https://expo.github.io/router/docs/troubleshooting) advice and making the changes to index.js the app will display a blank screen and the error 

`Multiple files match the route name...`

Will persist.

[Here](https://github.com/MLaidlawScott/webpack-min-reproduce) is the minimum code needed to reproduce.

Is there a way to fix this? Or, Is there a way to bundle and deploy to Vercel or similar with Metro, as the app works fine when bundled with Metro.

Thank you.

### Minimal reproducible example

https://github.com/MLaidlawScott/webpack-min-reproduce

**Comment by marklawlor** [comment]
Expo Router only supports bundling with Metro. You will need to change your web bundler in`app.json` back to `metro`. See the docs for detailed setup instructions https://expo.github.io/router/docs/

**Comment by MLaidlawScott** [comment]
> Expo Router only supports bundling with Metro. You will need to change your web bundler in`app.json` back to `metro`. See the docs for detailed setup instructions https://expo.github.io/router/docs/

Hi Mark, thanks for getting back to me.

Would you be able to provide any more advice on how to deploy the bundle produced by metro? I tried using the vercel cli but I just get a blank screen. I have included the ./public/vercel.json file as mentioned in the docs. Is there a step I'm missing?

**Comment by marklawlor** [comment]
Running `expo export` will create a `dist` folder with your website assets (including the `index.html`) You should be uploading this folder to vercel

**Comment by MLaidlawScott** [comment]
> Running `expo export` will create a `dist` folder with your website assets (including the `index.html`) You should be uploading this folder to vercel

Hi  Mark.

I've got this working now thanks to your help. My problem was that I was trying to follow the [expo.dev docs](https://docs.expo.dev/distribution/publishing-websites/) for deploying the website that relied on Webpack. 

When running the same vercel cli command in the dist folder when bundling with metro I could not get this to work.

What worked best for me was running the vercel cli command in the root of my project and then changing the build command to `npx expo export -p web` and the output dir to `./dist`. I had also initially tried to use Webpack with expo-router as expo webpack is mentioned in the [hosting page](https://expo.github.io/router/docs/guides/hosting#netlify). 

I'm not sure how much of this was just my misunderstanding but do you think there would be a benefit to me opening a PR for the docs to add more context to deploying to Vercel? And perhaps removing the expo webpack reference under Netlify?
