### ISSUE TITLE
Document Usage in React Native Project with expo-modules

### ISSUE THREAD

**Issue by JustinRohweller** [expo/router#443]
### Summary

Expo router appears to work with a vanilla react native project that contains expo modules, but it's not very clearly documented.

Getting started does not reference having a project that works without running expo start.
Could be nice to add a line under troubleshooting that says, you can replace registerRootComponent with AppRegistry.registerRootComponent if you would like to use expo router within a vanilla react native project.

If expo router should not be used in this way it seems like it'd be good to document that as well. 
Something like:
Expo router is not intended to be used in a "bare" react-native environment.

### Minimal reproducible example

npx react-native init testVanilla
npx install-expo-modules@latest
follow getting started docs
Replace index.js with:
```js
import { ExpoRoot } from "expo-router";
import { AppRegistry } from "react-native";
import { name as appName } from "./app.json";

// Must be exported or Fast Refresh won't update the context
export function App() {
  const ctx = require.context("./app");
  return <ExpoRoot context={ctx} />;
}

AppRegistry.registerComponent(appName, () => App);
```
Expo router appears to work properly.

**Comment by EvanBacon** [comment]
Unclear what "vanilla react native project that contains expo modules (+ expo router)" means, what part of the stack are trying to not use?

> Getting started does not reference having a project that works without running `expo start`.

Expo CLI works with any React Native project, but React Native community CLI does not. It may technically be possible to use parts of Expo Router with `npx react-native start` but the entire scope of Expo Router includes Metro for web, which the community CLI does not support. This means we'd be documenting an incomplete workflow that has no clear advantages.

In an effort to further improve Metro, we have already landed at least three new features for Expo Router v2/SDK 49 which will also be incompatible with the community CLI. These changes are tied to SDK 49 as it will fully remove the need for `npx react-native` when building for production.

> `npx react-native init testVanilla` `npx install-expo-modules@latest`

This is how Expo is designed to be used on the native side, but the React side requires more articulate server middleware and therefore depends on Expo CLI.

**Comment by JustinRohweller** [comment]
Hey Evan, thanks for the reply and for everything you do to carry the Expo community.
I'm sorry it wasn't entirely clear what I was asking for.
>what part of the stack are trying to not use?

I would like to use expo-router with ```npx react-native run-android --variant=QADebug``` instead of ```expo run:android --variant QADebug```

Put more clearly,
My project fails to run with ```expo run:android --variant QADebug```.
But runs with ```npx react-native start --reset-cache``` + ```npx react-native run-android --variant=QADebug```

Specifically, I believe ```npx expo run:android --variant QADebug``` doesn't handle the ```applicationIdSuffix``` property within android/app/build.gradle:

https://docs.expo.dev/build-reference/variants/#example-configuring-development-and-production-variants-in-1
>Note: Currently, EAS CLI supports only the applicationId field. If you use applicationIdSuffix inside productFlavors or buildTypes sections then this value will not be detected correctly

Handling the applicationIdSuffix feels like an obscure advantage of using the react-native cli. 

On a brand new project, ```npx expo run:android``` with expo router runs fine. I'd expect dev-clients also work fine.

#### So all of that just to say that I understand that I have an obscure issue that does not need to be accommodated by the library.

That being said, it seems to me that having these comments would be a good improvement to the Troubleshooting page:

>It may technically be possible to use parts of Expo Router with npx react-native start but the entire scope of Expo Router includes Metro for web, which the community CLI does not support.
>we have already landed at least three new features for Expo Router v2/SDK 49 which will also be incompatible with the community CLI.
>Expo (Router) ...requires more articulate server middleware and therefore depends on Expo CLI.

I hear that as: 
>Expo router is not intended to be used with the React Native Community CLI

At the end of the day people can find this issue now anyway, without the docs.
Issue resolved, I'll stop commenting about it.

Thanks again for the details and all the great work you've done.
