### ISSUE TITLE
"Error: Maximum update depth exceeded..." occurs only in Web Browser (not in Android)

### ISSUE THREAD

**Issue by sawogus29** [expo/router#452]
### Summary

This error occurs when all 4 conditions are met.

1. Running Environment: **Web Browser** 
    * It works normally on Android

2. **in-app navigation** (\<Link\>, router.push(), ...) to more _nested path_
    * It works normally if typing url(deep link) directly in the address bar.

3. **initialRouteName** defined in the layout of  _nested path_

4. **<Stack.Screen>** in _nested path_ directly
    * It works normally if <Stack.Screen> is defined in layout of _nested path_

![image](https://user-images.githubusercontent.com/37795048/229305182-f558fa1a-7528-46e1-bb4b-7c2bdddc22c3.png)

### Minimal reproducible example

* environment: `npx create-expo-app@latest --example with-router`

* directory
```
/app
    _layout.jsx
    index.jsx    <---------- from here
    /main
        _layout.jsx    <------ initialRouteName defined
        index.jsx
        welcome.jsx    <----- to here
```

### code
* **\<Link\>** from `/app/index.jsx` to `/app/main/welcome.jsx`
* `/app/_layout.jsx` and `/app/main/index.jsx` do not matter (any typical code is ok)

```javascript
// /app/index.jsx
import { Link } from 'expo-router';
import { Text, View } from 'react-native';

export default function IndexScreen() {
  return (
    <View>
      <Text>Index</Text>
      <Link href="/main/welcome">welome</Link>       <======== CLICK THIS!!!
    </View>
  );
}
```
```javascript
// /app/main/_layout.jsx
import { Stack } from 'expo-router';

export const unstable_settings = {
  initialRouteName: 'index',
};

export default function MainLayout() {
  return <Stack initialRouteName="index" />;
}
```
```javascript
// /app/main/welcome.jsx
import { View, Text, Button } from 'react-native';
import { Stack } from 'expo-router';

export default function WelcomeScreen() {
  return (
      <View>
        <Stack.Screen options={{}} />
        <Text>welcome</Text>
      </View>
  );
}
```

**Comment by EvanBacon** [comment]
This happens because the `initialRouteName` points to a non-existent route.

**Comment by ansh** [comment]
Happened to me because I was trying to use `<Redirect href="" />` to redirect to a screen that was mounted in the layout that my `<Redirect />` was in

**Comment by Echelpoel** [comment]
Thanks @ansh, I had the same problem 😁
