### ISSUE TITLE
Navigation broken when adding a layout

### ISSUE THREAD

**Issue by remo87** [expo/router#453]
### Summary

I tried adding a layout to a folder with the following structure:

```
app
  blog
    _layout.jsx
    [blogId].jsx
    settings.jsx
```

The navigation was working fine for both `/blog/someId` and `/blog/settings`. But as soon as I added the `_layout.jsx` file I started getting an error for both: `The action 'NAVIGATE' with payload {"name":"blog/settings"} was not handled by any navigator`.

I tried adding both Slot and Stack to the layout

### Minimal reproducible example

Create a folder with a Page inside and verify navigation is working. Add a layout file with a slot and try navigating to the same path again.

https://github.com/remo87/expo-router-v01

**Comment by chhornponleu** [comment]
I've just tried your code. The navigation works fine. 

Maybe you need to reset cache by running `expo start -c`. If still not work, try to add the initial route to the stack config in blog/_layout.jsx.
