### ISSUE TITLE
Expo Doctor complaining main on package.json

### ISSUE THREAD

**Issue by psudocode** [expo/router#458]
### Summary

Expo doctor complaining main property on package.json

Issues:
[stderr] 
Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
[stderr] 
   • should NOT have additional property 'main'.
- Checking package.json for common issues...
✔ Checking package.json for common issues passed

### Minimal reproducible example

Create new app:

`npx create-expo-app@latest`

then follow instruction from [https://expo.github.io/router/docs#getting-started](Getting Started)

then run `expo-cli doctor`

**Comment by EvanBacon** [comment]
Use the new `npx expo-doctor` https://www.npmjs.com/package/expo-doctor `main` is obviously an allowed field.
