### ISSUE TITLE
expo router does not work on expo go.

### ISSUE THREAD

**Issue by joaofranciscogit** [expo/router#459]
### Summary

I'm using expo router and it works normally in the web emulator. But when I use it on expo go with my android, it doesn't work. This also happens with the expo gradient library

### Minimal reproducible example

I'm using expo router and it works normally in the web emulator. But when I use it on expo go with my android, it doesn't work. This also happens with the expo gradient library

**Comment by EvanBacon** [comment]
Cannot reproduce this behavior given the current information, Expo Router works as expected in Expo Router.
