### ISSUE TITLE
Screen re-renders when using router.back()

### ISSUE THREAD

**Issue by lluisandreu** [expo/router#460]
### Summary

If I try to go back to the last screen using router.back() the previous screen re-renders, repeating a fetch query or other functions I run in useEffect(() => {}, []). The previous screen should be stored in memory and only re-rendered if I do a router.push() event, shouldn't it?

### Minimal reproducible example

```
export default ScreenA = () => {

  useEffect(() => {
    // Do a query or load a one time function
    alert('query')
  }, [])

  return <Link href="screen-b">Screen AB</Link>

}

export default ScreenB = () => {

  const router = useRouter();
  return <Pressable onPress={() => router.back()}>Screen AB</Pressable>

}
```

**Comment by ansh** [comment]
I am facing this issue to using FirebaseRecaptcha via the `react-native-firebase` library.

**Comment by DevYuns** [comment]
@lluisandreu How about trying it like this?

```ts
export default ScreenB = () => {

  const {back} = useRouter();
  return <Pressable onPress={() => back()}>Screen AB</Pressable>
}
```

**Comment by JCharante** [comment]
Has anyone seen a reliable way to force a re-render?

**Comment by steveafrost** [comment]
> Has anyone seen a reliable way to force a re-render?

I haven't but this is a separate issue than what is in this thread. 

As far as the issue with `back()` re-rendering the current route, I've experienced this as well. For a temporary workaround, I am using `router.replace(route)` in each place where I actually need back. Using the `withLayoutContext` and React Navigation drawer if that is helpful. Pretty basic app with just a couple screens right now.

**Comment by marklawlor** [comment]
`main` has fixes that will prevent this from unintentionally occurring, but there are still cases where we expect this to occur.

```
one
/(two)
├── _layout // tabs
├── alpha
└── beta
```

For example your navigation history is `/one` -> `/alpha`. If you press back, one will be remounted. You can prevent this by nest `one` and `(two)` within in a stack layout.

Additionally, be aware that React will fire `useEffects` twice in development mode https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development 

@JCharante You can force a rerender by setting state within your component. If for some reason you need a controlled rerender you can do something like `const [,rerender] = React.useReduce(acc => acc + 1, 0)`, but this is normally a code smell and there is most likely a better way to control your state.

**Comment by marcel-mintouge** [comment]
Is this resolved in expo router V2?

**Comment by ogmzh** [comment]
I'm getting unintended sideeffects from navigating forward which is re-rendering my previous screen. So on the stack that has A->B->C, doing router.push("B") from screen A will re-render screen A while rendering screen B as well.

Not sure if this is intended?

**Comment by marcel-mintouge** [comment]
Personally to temporarily escape from this behaviour I'm persisting part of the state on a store (redux). @ogmzh maybe you could use redux with sagas to handle those side effects. I have in my backlog the task of moving out of expo router in the future, seems very limited.

**Comment by ogmzh** [comment]
@marcel-mintouge seems a bit too drastic to do that in my usecase.

as for sticking with expo router, i will as i'm also a fan of nextjs and the whole file based routing system. once you get the grasp of it - it's very efficient. too bad expo router still has some growing pains

**Comment by dannybit** [comment]
@ogmzh I am getting the same issue when calling `router.push`. Were you able to resolve it?

**Comment by sovetski** [comment]
Same problem here, I am using `react query` + `expo router`, and `router.push` to navigate and `router.back` to go back, but each time I go back, it re-renders the previous screen, so it refetch again the data, to avoid it, I added `staleTime` but the component itself continue to re-render.

I don't understand why this issue is closed, because @marklawlor's answer is not a solution (in my case and for others from what I see)

**Comment by elimau** [comment]
I think the solution is:
In your _layout, replace the `Slot` with `Tabs` like below.

```js
import { Link, Slot, Stack } from 'expo-router'
import { Tabs } from 'expo-router/tabs'

                  {/* <Slot /> */}
                  {/* <Stack screenOptions={{ headerShown: false }} /> */}
                 <Tabs
                    screenOptions={({ route }) => ({
                      headerShown: false,
                      tabBarStyle: {
                        // display: route.name === 'example' ? 'none' : 'flex',
                        display: 'none',
                      },
                    })}
                  />
```

The result will be similar to using `Tab Navigation` of the react-navigation.
In Tab Navigation it displays the route again (if mouted previously) without reloading/rerendering it.
It will use the previously rendered version of that route.

Comparing the different route rendering methods: 
- `Slot` always reloads the routes.
- `Stack` can display without reloading, however that only occurs in some certain circumstances for routes which are currently in the stack based on the LILO rules.
- So finally, we can use `Tabs` but just hide the header and the tab navigator menu. This will always use the previously rendered version of that route. Never reload.

**Comment by malbolged** [comment]
@marklawlor ?

**Comment by vendramini** [comment]
It doesn't even trigger re-rendering with react-query. I have a useQuery() on /page-1 then I push a modal /page-1/modal which modifies some content inside a query. The subscription on /page-1 does not work.

I've ended up with this workaround to re-render previous screen when I back from my modal:
```javascript
const [, rerender] = useReducer(acc => acc + 1, 0);
useFocusEffect(rerender);
```
However, I really don't like it. Any tips?

**Comment by alwyntan** [comment]
> It doesn't even trigger re-rendering with react-query. I have a useQuery() on /page-1 then I push a modal /page-1/modal which modifies some content inside a query. The subscription on /page-1 does not work.
> 
> I've ended up with this workaround to re-render previous screen when I back from my modal:
> 
> ```js
> const [, rerender] = useReducer(acc => acc + 1, 0);
> useFocusEffect(rerender);
> ```
> 
> However, I really don't like it. Any tips?

I think in your case you should look into invalidating the query, using `invalidateQueries` if you would like the updated content to show on your previous page after modifying/refetching the query.

**Comment by vendramini** [comment]
> I think in your case you should look into invalidating the query, using `invalidateQueries` if you would like the updated content to show on your previous page after modifying/refetching the query.

I don't understand why, do you? When changing a query's value (either manually or re/fetching) isn't it supposed to re-render? That's how it works on web. I would like to know the reason to not behave the same.

**Comment by alwyntan** [comment]
> > I think in your case you should look into invalidating the query, using `invalidateQueries` if you would like the updated content to show on your previous page after modifying/refetching the query.
> 
> I don't understand why, do you? When changing a query's value (either manually or re/fetching) isn't it supposed to re-render? That's how it works on web. I would like to know the reason to not behave the same.

hmm, not sure what you mean by manually. Afaik, when calling `refetch`, all associated queries with the same key should be updated with new data, but if the data is the same, nothing will be changed, and no rerenders will occur.

**Comment by vendramini** [comment]
Manually: https://tanstack.com/query/v5/docs/reference/QueryClient/#queryclientsetquerydata

I set a new value at /page-1/modal and when I get back to /page-1 it doesn't show the updated value, and the only solution that I've found is to force a re-render. Doing it since July 🤣

**Comment by Helaers** [comment]
@vendramini having the same issue here.

I have 2 pages:
- an overview page with a list of data. 
- a detail page where I can change some of the data

When navigating to the detail page, altering the data, invalidating the query via a mution and then "go back"... the data in the list isn't updated.

This is my setup in the overview page: 
```ts
  const { data, refetch, isStale } = useQueryMyData();

  useFocusEffect(
    useCallback(() => {
      if (isStale) {
        refetch();
      }
    }, [refetch, isStale]),
  );
  ```
  
I can remove the `isStale` flag and then it would work, but then the refetch is fired every time the component gets focus (defeating the purpose of using `useQuery`)
The overview component doesn't render indeed... your fix didn't work for me for some reason.

Have you found a solution since?

**Comment by vendramini** [comment]
@Helaers unfortunately I haven't. My fix is literally the same without the condition:
```
useFocusEffect(
    useCallback(() => {
      refetch();
    }, [refetch]),
  );
```
 It doesn't fire every time here. I think you might have another thing triggering the component re-render? Can you share your code?

**Comment by leandrocunha** [comment]
Hey,
What I usually do when I need force a re-render is:

1) Instead of use router.back(), I explicitly navigate with a new param value, for example:
```
router.navigate({
 pathname: "(your route)",
 params: { timestamp: new Date().getTime() }
})
```

2) Render the page with a timestamp as a dependency in useEffect hook. This will force the render  every time of the is render:
```
const { timestamp } = useLocalSearchParams()

useEffect(() => {
 // do something
 }, [timestamp])
 ```
 
 ps: example above, based on my app with expo router

**Comment by Andres6936** [comment]
Thanks very muchhhhh @elimau 

The complete example is: 

```jsx
import {Tabs} from 'expo-router/tabs'

export default function Layout() {
    return (
        <Tabs
            screenOptions={() => ({
                headerShown: false,
                tabBarStyle: {
                    display: 'none',
                },
            })}
        />
    )
}
````

**Comment by VariabileAleatoria** [comment]
I love how everyone went off topic in this thread.
So if I understood it correctly Slot navigator re mounts screens on back navigation while Stack navigator does not?
