### ISSUE TITLE
Tabs.Screen options not initialized until route is rendered once

### ISSUE THREAD

**Issue by FezVrasta** [expo/router#465]
### Summary

My routes render a Tabs.Screen component with the options property set to a title and a tabBarIcon.

My problem is that the tab bar doesn't use the correct title and icon until I click on the tab. Once I click, the correct icon and title are used.

### Minimal reproducible example

N/A

**Comment by EvanBacon** [comment]
If you want the options to be rendered sooner, add them to the layout. Otherwise options inside of lazy screens are loaded lazily.
