### ISSUE TITLE
Dynamic route params (useSearchParams) not preserved when using back button/swiping gesture

### ISSUE THREAD

**Issue by piotrski** [expo/router#474]
### Summary

When using the stack navigator in Expo Router, I have noticed that when I navigate back using the back button or swiping gesture, the screen consistently appears without dynamic route params (useSearchParams) until it is re-rendered. However, this behavior does not occur when I use the back function from the router context.

### Minimal reproducible example

https://github.com/piotrski/expo-router-search-params-issue

**Comment by EvanBacon** [comment]
Use `useLocalSearchParams`
