### ISSUE TITLE
App fully reload when using i18n and unstable_settings

### ISSUE THREAD

**Issue by wcastand** [expo/router#483]
### Summary

explained in the readme of the repo

You can see the app load but if you make a change to the `locales/en.json` or `locales/fr.json` the app will fully reload it doesn't show the splashscreen tho.

if you comment the unstable_settings it won't full reload and make a fast refresh like normal.

### Minimal reproducible example

https://github.com/wcastand/bug-i18n-unstable

**Comment by EvanBacon** [comment]
Fast Refresh is limited to React Components, all other changes fall under hot module reloading.
