### ISSUE TITLE
Unable to navigate to sub-route in the 2nd expo app

### ISSUE THREAD

**Issue by iambharath87** [expo/router#484]
### Summary

I have a mono-repo with the following structure.
```
|_apps
|     |____ native
|                |____home
|                |____credit-card
|     |____ web
```

Both of the "native" apps are expo apps using expo-router for navigation. Here are the routes defined for both the apps:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/6663930/231229240-a83c26ed-ec36-40ce-9488-739f6e4099cb.png">

The "home" app has two routes: `/` (index.tsx) and `/credit-card`.
The "credit-card" app has two routes: `/` (index.tsx) and `/details`.

The `/credit-card` screen from the home app is basically a wrapper around the `index.tsx` of the credit-card app.
I am trying to navigate from route `/` to `/credit-card/details` page but i'm getting a "Unmatched route" error.

Here is a video of this: https://user-images.githubusercontent.com/6663930/231235863-38f1acac-0029-4618-9cfe-cdb8d2568b12.mp4

Can someone please help me?

### Minimal reproducible example

Here is a sample repo that shows the problem: https://github.com/iambharath87/expo-monorepo
To start the app, go to `/apps/native/home` and run `yarn ios`

**Comment by paulvanbrenk** [comment]
As a workaround, consider exporting all pages from the credit-card app. But I can see how that can become tedious very quickly. (Unless there is a way to automate that)

**Comment by EvanBacon** [comment]
This is not a supported feature in Expo Router.
