### ISSUE TITLE
expo-router/entry

### ISSUE THREAD

**Issue by Victorcassiano** [expo/router#487]
### Summary

all i did was run npx create-expo-app@latest --example with-router

use:
NODEJS: 18.15.0

ERROR:
Android Bundling failed 13ms
Unable to resolve "expo-router/entry" from "index.ts"

### Minimal reproducible example

I was creating an application with expo router I just ran the cli command for creation with expo router

**Comment by AntoineKM** [comment]
Hey @Victorcassiano did you tried with `index.js` instead of `index.ts`, i'm not sure expo router support `.ts` for the index

**Comment by marklawlor** [comment]
I'm unable to replicate the issue with the description provided. Please provide a git repo if your still experiencing this issue.

**Comment by nirajkaushal** [comment]
Try putting `"main": "index.js"` in the package.json file if not present already.

**Comment by Victorcassiano** [comment]
> @Victorcassiano Try putting `"main": "index.js"` in the package.json file if not present already.

I tried to do that, however, errors occur, I solved it by getting a ready-made project

**Comment by nirajkaushal** [comment]
If someone still getting this error and using pnpm for the project, try this solution https://github.com/expo/expo/issues/21820#issuecomment-1506079581
