### ISSUE TITLE
Stack swipeEnabled is not working

### ISSUE THREAD

**Issue by keung7252** [expo/router#488]
### Summary

Stack swipeEnabled is not working. I don't want user swipe to back in expo-router Stack

### Minimal reproducible example

`import { useState, useEffect } from 'react';
import { Stack } from 'expo-router';
import { View } from 'react-native';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Provider } from 'react-redux';
import { store, persistor } from '@/utils/store';
import { PersistGate } from 'redux-persist/lib/integration/react';

const queryClient = new QueryClient();
export default function Layout() {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <QueryClientProvider client={queryClient}>
          <Stack
            screenOptions={{
              headerShown: false,
              headerMode: 'none',
              animationTypeForReplace: 'push',
              animation: 'slide_from_right',
              gesturesEnabled: false,
              swipeEnabled: false
            }}
          />
        </QueryClientProvider>
      </PersistGate>
    </Provider>
  );
}
`

**Comment by EvanBacon** [comment]
Cannot reproduce this error. This is more than likely unrelated to Expo Router, possibly a `react-native-screens` issue?
