### ISSUE TITLE
Tabs/Stack/Drawer configs from screens dont work, when app starts from deep link

### ISSUE THREAD

**Issue by trin4ik** [expo/router#49]
possibility modify change tabs/stack options from screen are beautiful. like 

```javascript
import { Tabs } from "expo-router";
import { View } from "react-native";

export default function Page() {
  return (
    <View>
      <Tabs.Screen options={{ title: "Home" }} />
      ...
```

but its not working, if app starts from deep link. for example, when i start demo app from `exp://127.0.0.1/--/settings` i got:

<img src="https://user-images.githubusercontent.com/839633/193698309-3f7daf1c-d5b2-4559-a160-acebf752a080.jpeg" width="400" />

the solution for now is to set the options for the tabs in the parents, like

```javascript
<Tabs>
  <Tabs.Screen name="settings" options={{ title: "Settings" }} />
  <Tabs.Screen name="index" options={{ title: "Home" }} />
</Tabs>
```

<img src="https://user-images.githubusercontent.com/839633/193698314-0043e650-63be-4830-a7fa-3aa06545f23b.jpeg" width="400" />

**Comment by EvanBacon** [comment]
This behavior is [documented](https://expo.github.io/router/docs/features/options). We won't be changing this because it would break our ability to add bundle splitting and lazy loading routes in the future. Please utilize the layout-level configuration for eager loading.

**Comment by trin4ik** [comment]
> This behavior is [documented](https://expo.github.io/router/docs/features/options). We won't be changing this because it would break our ability to add bundle splitting and lazy loading routes in the future. Please utilize the layout-level configuration for eager loading.

found another way, `lazy: false` for `screenOptions` like:
```javascript
<Tabs screenOptions={{ lazy: false }}>
  <Tabs.Screen name="settings" />
  <Tabs.Screen name="index" />
</Tabs>
```

https://reactnavigation.org/docs/bottom-tab-navigator/#lazy
but i agree, seems like layout-level configurations more safety
