### ISSUE TITLE
refresh not working with expo web 

### ISSUE THREAD

**Issue by alidcast** [expo/router#493]
### Summary

Followed setup instructions in docs.

I see the refresh notification appearing but the page does not refresh.

### Minimal reproducible example

There was a discussion started asking proper setup (https://github.com/expo/router/discussions/478) and @mackenziekira created a basic demo https://github.com/mackenziekira/metro-web-fast-refresh

**Comment by EvanBacon** [comment]
The `@expo/metro-runtime` import MUST be first. I've opened a PR into `expo/metro-config` to ensure this behavior. Static rendering will still not support Fast Refresh unless you resolve `"react-refresh": "0.14.0",`. I've pinged the React Native team to update react-refresh in the babel plugin.

**Comment by mackenziekira** [comment]
amazing, thx, evan! adding `"react-refresh": "0.14.0"` as a dep fixed the issue for me 🙏
