### ISSUE TITLE
iOS: <Stack.Screen/> options orientation and autoHideHomeIndicator not working

### ISSUE THREAD

**Issue by Jnforja** [expo/router#515]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Hey,

The option `orientation` of the Stack.Screen component is not having any effect on iOS (I tried it on an android device and it works). I'm using a physical iPhone 13. The option `autoHideHomeIndicator` also doesn't seem to have any effect as the home indicator still shows on my iPhone 13.

### Minimal reproducible example

File: app/index.js

```javascript
import { Stack } from "expo-router";
import { Text } from "react-native";

export default function Page(){
    return <>
        <Stack.Screen options={{ 
            orientation: 'landscape_right', 
            autoHideHomeIndicator: true, 
            navigationBarHidden: true }}/>
        <Text>Home Page</Text>
    </>
}
```

file: app/_layout.js

```javascript
import { Stack } from "expo-router";

export default function Layout() {
  return <Stack />;
}
```

I just ran npm install and here's the list of dependencies of the project:
```json
{
"dependencies": {
    "expo": "^48.0.7",
    "expo-constants": "~14.2.1",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.2.0",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9"
  },
}
```

**Comment by EvanBacon** [comment]
We pass the options through to React Navigation -> React Native Screens verbatim. This is more than likely an issue with those libraries. Closing as we're archiving this repo in favor of https://github.com/expo/expo/
