### ISSUE TITLE
Can't push a screen multiple times on a stack

### ISSUE THREAD

**Issue by jannikrl** [expo/router#519]
### Summary

I have tried to reproduce the following feature in expo router, but when doing so the current screen is just replaced by the new one. No new screen is pushed on the stack:
https://reactnavigation.org/docs/navigating#navigate-to-a-route-multiple-times

#### index.jsx
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1298449/234495767-ad4f31e8-05e0-405e-beb6-b5a451a33e16.png">

#### _layout.jsx
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1298449/234495819-f2d080a1-bae0-4bfd-8c63-9a4cb689f6a2.png">

**Comment by marklawlor** [comment]
Can you explain your use-case in more detail? As explained in the docs you linked, you typically navigate to the same route when you are pushing unique parameters. Expo Router's equivalent is [Dynamic Routes](https://expo.github.io/router/docs/features/routing#dynamic-routes).

**Comment by EvanBacon** [comment]
Expo Router has a default `getId` function which uses the dynamic props to determine if a screen should be pushed or not. You can create a [custom getId](https://reactnavigation.org/docs/screen/#getid) and pass a random value like the date to ensure a new screen is always pushed:

Put this inside the Layout:

```js
<Stack.Screen name="index" getId={() => Date.now()} />
```

**Comment by jannikrl** [comment]
I have tested with parameters and getId

**Parameters**
A new screen is pushed on the stack. But the current page rerender itself before transitioning with parameters for the next page (see video below). So screen with id 1 rerenders itself with id 2 before transitioning to the screen with id 2.

Also when pushing a new screen to the stack without parameters, the current screen rerenders itself without parameters.

**getId**
I used the below code example using params or date to generate a unique id, but I couldn't get it to push a new page. Maybe I don't understand fully how to use the getId.

https://user-images.githubusercontent.com/1298449/235608334-1f9a5774-43bf-4d53-8700-865892aa3e2e.mp4


### _layout.jsx
```
import { Stack } from "expo-router";

export default function Layout() {
  return (
    <Stack>
      <Stack.Screen name="index" />
      <Stack.Screen name="[id]" getId={({ params }) => params.userId} />
    </Stack>
  );
}
```
### index.jsx
```
import { Stack, useRouter, useSearchParams } from "expo-router";
import { Button, Text } from "react-native";

export default function App() {
  const router = useRouter();
  const params = useSearchParams();
  return (
    <>
      <Stack.Screen
        options={{
          fullScreenGestureEnabled: true,
        }}
      />
      <Text>Param id {params.id}</Text>
      <Button
        onPress={() =>
          router.push({
            pathname: "/[id]",
            params: {
              id: +params.id + 1,
            },
          })
        }
        title={`Push screen again with id ${+params.id + 1}`}
      />
      <Button
        onPress={() =>
          router.push({
            pathname: "/welcome",
          })
        }
        title="Push welcome"
      />
    </>
  );
}

```
### [id].jsx
```
import { useRouter, useSearchParams, useNavigation } from "expo-router";
import { Button, Text } from "react-native";

export default function App() {
  const router = useRouter();

  return (
    <>
      <Text>Home</Text>
      <Button
        onPress={() =>
          router.push({
            pathname: "/[id]",
            params: {
              id: 1,
            },
          })
        }
        title="Push screen with id 1"
      />
    </>
  );
}

```
### welcome.jsx
```
import { useRouter, Stack } from "expo-router";
import { Button, Text } from "react-native";

export default function App() {
  const router = useRouter();

  return (
    <>
      <Stack.Screen
        options={{
          fullScreenGestureEnabled: true,
        }}
      />
      <Text>Welcome</Text>
      <Button
        onPress={() =>
          router.push({
            pathname: "/[id]",
            params: {
              id: 1,
            },
          })
        }
        title="Push screen with id 1"
      />
    </>
  );
}

```

**Comment by EvanBacon** [comment]
Use useLocalSearchParams() to only update when the screen is active.

**Comment by jannikrl** [comment]
Worked perfectly. Thanks!

https://user-images.githubusercontent.com/1298449/236137537-db75cedd-aa77-44f9-b412-3fedfca3c30f.mp4

**Comment by awinograd** [comment]
I'm trying to copy this exact behavior but am unable to do so. `getId` is not a valid prop for `Stack.Screen` in typescript and the `getSortedChildren` is written such that it can never be picked up as a prop.

https://github.com/expo/router/blob/1da1d1e01ad683f19f8ecd0960a4c39dbbec1353/packages/expo-router/src/useScreens.tsx#L75

Am I missing something here?

**Comment by CodySwannGT** [comment]
I'm in the same boat as @awinograd `getId` is never called.

**Comment by jannikrl** [comment]
You can push a screen multiple times, if you push the screen with unique params.

And, if you need to use the params on the screen, then remember to use useLocalSearchParams().
