### ISSUE TITLE
Web useSearchParams bug. useSearchParams populated with first old values when moving from dynamic route to dynamic route

### ISSUE THREAD

**Issue by fuelkoy** [expo/router#523]
### Which package manager are you using? (Yarn is recommended)

pnpm (known issues due to Metro)

### Summary

Hey.

Using expo-router with web presents bug: useSearchParams populated with first old values when moving from dynamic route to dynamic route.

Example app structure: 
```
app/
  index.tsx
  test1/
    [id].tsx
  test2/
   [id].tsx
```

Explanation scenario:
  1. Moving from '/' to '/test1/1'

-  React.useEffect(() => { console.log(id) }, [id]), renders twice: first with "undefined", second with "1"
         
 2. Moving from '/test1/1' to '/test2/2'
-  React.useEffect(() => { console.log(id) }, [id]), renders twice: first with "1", second with "2"

This creates a problem for example when passed searchParam is used to fetch data according to the passed dynamic id. Now it will fetch two times,

Tried to search if this is expected or not and how to fix this but didn't find or understand there were prior issues/explanations covering this are in this package.

Thank you for this package and to whole Expo team! expo + expo-router has really been a blessing and joy in development.

### Minimal reproducible example

https://github.com/fuelkoy/useSearchParamsBug

**Comment by athenawisdoms** [comment]
Might be similar to https://github.com/expo/router/issues/320

**Comment by marklawlor** [comment]
You should be using `useLocalSearchParams` instead of `useSearchParams`.

**Comment by fuelkoy** [comment]
Works as expected. Thank you really much @marklawlor! I appreciate your help and guidance.
