### ISSUE TITLE
 ERROR  Error: Cannot find native module 'ExpoHead', js engine: hermes 

### ISSUE THREAD

**Issue by fruity4pie** [expo/router#525]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

 ERROR  Error: Cannot find native module 'ExpoHead', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### Minimal reproducible example

using yarn 3.5+

<img width="173" alt="image" src="https://user-images.githubusercontent.com/15814446/235370132-bc791618-ea82-4ca9-8256-9efa8d5b04d8.png">

index.tsx:

```
import { View } from 'react-native';
import { Link, Stack } from 'expo-router';

// import PlaceList from '../src/components/Delivery/PlaceLIst';
// import { restaurants } from '../src/data';

const MainScreen = () => {
  return (
    <Stack.Screen
      options={{
        animation: 'fade',
        headerShown: false,
      }}
    />
  );
};

export default MainScreen;
```

_layout.tsx:
```
import { Text } from 'react-native';
import { SplashScreen } from 'expo-router';

import {
  useFonts,
  Andika_400Regular as andika400r,
  Andika_700Bold as andika700b,
} from '@expo-google-fonts/andika';

const Layout = () => {
  const [fontsLoaded] = useFonts({
    andika400r,
    andika700b,
  });

  if (!fontsLoaded) {
    return <SplashScreen />;
  }

  return <Text>123</Text>;
};

export default Layout;
```

**Comment by fruity4pie** [comment]
Did https://expo.github.io/router/docs/troubleshooting/#expo_router_app_root-not-defined

and now getting this:

```
 ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `GestureHandler`.
    in GestureHandler (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
```

**Comment by fruity4pie** [comment]
Reverted to 1.4.3 and it works fine. 

What is the problem here in the new version?

**Comment by EvanBacon** [comment]
The `@next` version of `expo-router` (used for v2) has a new native module on iOS that requires a native rebuild. In Expo Go, Android, and web this is not an issue. To fix, simply `npx expo run:ios` or `eas build`.

**Comment by fruity4pie** [comment]
@EvanBacon doesn't help, getting the same issue

**Comment by budzHors7** [comment]
### Just Updated my project from Expo 48 to ^49.0.0, Today.

When I run my project on Expo Go, I get this error:

Error: Cannot find native module 'ExpoDevMenu', js engine: hermes

And, Yes I'm using Expo Router.

**Comment by shanoysinc** [comment]
same here

**Comment by shanoysinc** [comment]
> ### Just Updated my project from Expo 48 to ^49.0.0, Today.
> When I run my project on Expo Go, I get this error:
> 
> Error: Cannot find native module 'ExpoDevMenu', js engine: hermes
> 
> And, Yes I'm using Expo Router.

same here but am not using expo router

**Comment by VivekNeel** [comment]
Make sure you are not using development build. use expo go

**Comment by Jhon-Idrovo** [comment]
> Make sure you are not using development build. use expo go

You might say "make sure you're not using expo" as well

**Comment by perhapsubhan** [comment]
I'm having the same error:  ERROR  Error: Cannot find native module 'ExponentAV', js engine: hermes. I'm using dev build of expo with expo cli. What should I do?

**Comment by LMarcinkowski** [comment]
> I'm having the same error: ERROR Error: Cannot find native module 'ExponentAV', js engine: hermes. I'm using dev build of expo with expo cli. What should I do?

Same here...

**Comment by Emmanueldmlr** [comment]
Same here

> I'm having the same error: ERROR Error: Cannot find native module 'ExponentAV', js engine: hermes. I'm using dev build of expo with expo cli. What should I do?

**Comment by fimbres** [comment]
Same, any update?

**Comment by Acrylic125** [comment]
Running into a similar issue,
>  ERROR  Error: Cannot find native module 'ExponentAV', js engine: hermes 

After experimenting a bit more, it seems to be happening on my EAS install for dev mode (Have no tried prod). However, on the simulator and Expo Go, it seems to be fine.

EDIT: 
An update, I managed to resolve my issue. As it turns out, I had to rebuild my EAS dev build. Might be related, but when running `expo-doctor`, it warned me about the following:
> Check for common project setup issues

Upon further inspection, it turns out I was committing my `ios` and `android` folder so I had to remove that, and add both folders to my `.gitignore`. 

Then I rebuilt my EAS dev build, reinstalled the whole app from scratch again, then booted my dev server using `npm run ios` and it no longer yells at me about this issue.

**Comment by EClinick** [comment]
> Same, any update?

Same, Any update? Been trying to debug for the past 2 weeks

**Comment by jonoise** [comment]
What worked for me was to run `npx expo run:ios`. In my case i'm mainly developing for iOS. Also make sure your routes are set up correctly. Fix your <Link> with an `href` pointing to a non existing route.

**Comment by 0xhankoc** [comment]
I found a potential fix: 
1. Run `npx expo-doctor`
2. Check if there's a warning regarding a version mismatch between Expo SDK and `ExpoHead`
3. install the recommended version of the package.

Expo errors could be more definitive in this case.
