### ISSUE TITLE
process out of memory error when importing aws-amplify 

### ISSUE THREAD

**Issue by FlorianF21** [expo/router#535]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

I created a project with expo-router.
After I implemented aws-amplify, it throws the following error.
```
<--- Last few GCs --->

[14068:094E7508]   198174 ms: Mark-sweep (reduce) 490.1 (510.7) -> 490.1 (510.0) MB, 469.8 / 0.0 ms  (average mu = 0.830, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed 
- JavaScript heap out of memory
```
It took me days to figure out that just the Amplify import, without any use, already causes the error. 
I also tried this in an expo app **without** expo-router and the error didnt occurr.

### Minimal reproducible example

1.
`npx create-expo-app@latest --example with-router reproduceErrorApp`

2.
Open reproduceErrorApp in VS Code

3.
Add app folder in root
	Add _layout.js in app folder
	Add index.js in app folder
![image](https://user-images.githubusercontent.com/83139625/235936446-f2bb28fa-4e9c-4e07-9e69-52d011442101.png)

Add the following code to `_layout.js`
```
import { Tabs } from "expo-router";
import { FontAwesome } from "@expo/vector-icons";

const layout = () => {
  return (
    <Tabs>
      <Tabs.Screen
        name="index"
        options={{
          headerLeftContainerStyle: { marginLeft: 0 },
          tabBarIcon: ({ color }) => (
            <FontAwesome name="home" size={30} color={color} />
          ),
          title: "My App",
        }}
      />
    </Tabs>
  );
};

export default layout;
```
Add the following code to `index.js`
```
import { Text } from 'react-native'


const home = () => {
return (
    <Text style={{margin:10, fontSize: 24}}>Home</Text>
);
};

export default home;
```
4.
Open in Android Emulator (Tested with Android Studio Pixel 5 API 33 and Pixel 3a) 
Should work as expected !

5. 
Stop server and close the app on Emulator

6.
Install aws-amplify
`npm install aws-amplify @react-native-community/netinfo @react-native-async-storage/async-storage`
(https://docs.amplify.aws/start/getting-started/setup/q/integration/react-native/)

7.
Add `import { Amplify } from "aws-amplify";` to _layout.js

8.
 Start Server and open the app in Android Emulator again
** The error does not always occur. **

-----------------------

I have tested a little with the import and without the import and came to the following results:
(I started the app and **reloaded** minimum 3 times)

Without the `import  // import { Amplify } from "aws-amplify";`
0 Errors from 10 Tests (with 3 reloads each)

With the `import { Amplify } from "aws-amplify";`

**Results**:
  First Start/Reload1/Reload2/Reload3 crash?

1. n/n/n/n
2. n/y
3. n/n/y
4. n/y
5. n/y
6. n/y
7. n/y
8. y
9. n/y
10. n/n/n/y

**Comment by marklawlor** [comment]
I've tried to replicate your issue multiple times and have been unable to do so. I would consider using Android Studio Profiler to do a memory profile to check what is causing your issue.
