### ISSUE TITLE
<Tabs screenListeners={{ tabPress(e) =>  e.preventDefault,  }}> not working with custom href in <Tabs.Screen />

### ISSUE THREAD

**Issue by fuelkoy** [expo/router#541]
### Which package manager are you using? (Yarn is recommended)

pnpm (known issues due to Metro)

### Summary

Moving from another screen through bottom tab navigator should be prevented with following configuration
```
<Tabs
  screenListeners={{
        tabPress: (e) => e.preventDefault();
  }}
>
  <Tabs.Screen
        name="example"
        options={{ href: 'newHref ' }}
    />
</Tabs>
```

### Minimal reproducible example

I'm busy at work at the moment and just leaving to vacation so I will add this later if needed.

**Comment by edmbn** [comment]
I am working with pnpm also and don't have any issues using the exact same code you posted here.

**Comment by fuelkoy** [comment]
(Now returned from the vacation). Thank you for the information. I need to take closer look at the problem. I'll close this and open new issue with repo if needed
