### ISSUE TITLE
testing-library submodule not exported from expo-router

### ISSUE THREAD

**Issue by Tellefsonjr** [expo/router#551]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Hi all, 

Just getting started with a new Expo project and wanted to try the new expo-router. When adding in Jest, I was running into errors rendering my components due to them not being wrapped in a navigator. 

That lead me to [your testing guide](https://expo.github.io/router/docs/lab/jest/) which suggests to use 
`import { screen, renderRouter } from 'expo-router/testing-library'`

But TS gives me a warning: "Cannot find module 'expo-router/testing-library' or its corresponding type declarations."
Jest fails with: "Cannot find module 'expo-router/testing-library' from 'app/__tests__/app.test.tsx'"

And exploring your node_module I cannot find testing-library being exported in version: **"expo-router": "^1.5.3"**

Any help would be great, thanks! 

### Minimal reproducible example

**App: **

_package.json:_
` {
   "dependencies": {
      "expo-router": "^1.5.3",
      ...
   }
} `

_./index.tsx_
`import 'expo-router/entry';`

_./app/_layout.tsx:_ 

`import React, { useEffect } from 'react';
import { SplashScreen, Tabs, useRouter } from 'expo-router';
import { SafeAreaProvider } from 'react-native-safe-area-context';

export default function RootLayout() {
    const [isReady, setReady] = React.useState(false);
    const [isAuthenticated, setIsAuthenticated] = React.useState(true);
    useEffect(() => {
        // Perform some sort of async data or asset fetching.
        setTimeout(() => {
            setReady(true);
        }, 1000);
    }, []);

    const router = useRouter();
    useEffect(() => {
        //TODO: Setup Auth and route to signIn or Home
        if (isAuthenticated) {
            router.replace('/Home');
        }
    });

    return (
        <SafeAreaProvider testID="Root_Layout_Wrapper">
            {/* When all loading is setup, unmount the splash screen component. */}
            {!isReady && <SplashScreen />}
            <Tabs
                screenOptions={{
                    headerStyle: {
                        backgroundColor: 'blue',
                    },
                    headerTintColor: 'white',
                    headerTitleStyle: {
                        fontWeight: 'bold',
                    },
                }}
            >
                <Tabs.Screen
                    name="index"
                    options={{
                        // This tab will no longer show up in the tab bar.
                        href: null,
                    }}
                />
            </Tabs>
        </SafeAreaProvider>
    );
}
`

_./app/index.tsx_
`export default function Root() {
    return <></>;
}
`

**Test: **
_./app/__tests__/app.test.tsx_
`import React from 'react';
import { screen, renderRouter } from 'expo-router/testing-library';
import Root from '../index';

describe('App Root', () => {
    it('renders without errors', async () => {
        renderRouter(<Root />);
        expect(screen.findByTestId('Root_Layout_Wrapper')).not.toBeNull()    
    });
});
`

**Comment by Tellefsonjr** [comment]
Oops! I missed this PR: https://github.com/expo/router/pull/447 and saw that version 1.7.1 has this feature. 

For any coming across this

yarn add expo-router@^1.7.1 

and the import _for now_ looks like: 
`import { screen, renderRouter } from 'expo-router/src/testing-library';`

sorry for the false alarm. thx!

**Comment by marklawlor** [comment]
The `testing-library` feature has not been released and we have planned breaking changes. I would not recommend using it until it is stable

**Comment by NiklasEi** [comment]
> The testing-library feature has not been released and we have planned breaking changes. I would not recommend using it until it is stable

Is that still the case? The expo docs do not mention that this is not released yet and claim that `renderRouter` should be imported from `expo-router/testing-library`, which does not work for me, while importing from `'expo-router/src/testing-library'` works.

**Comment by marklawlor** [comment]
Ah sorry, looks like we forgot to add it to the npm allowlist :disappointed: You can use the `expo-router/src/testing-library` until get this PR merged https://github.com/expo/router/pull/876

**Comment by sauldeleon** [comment]
hello!

therefore, can we supose that the renderRouter is stable now?

thanks @marklawlor !
