### ISSUE TITLE
Ghost routes when using material bottom tabs

### ISSUE THREAD

**Issue by Patrick-web** [expo/router#554]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I am seeing the **sitemap** and **[...404]** routes appearing at the bottom tab on switching to material bottom tabs. This was not the case when I was using the default tab provider. 
 ![screenshot](https://user-images.githubusercontent.com/56973177/236899165-8d4d710e-0ee9-44e9-b657-a9bfdd5870dc.png)

I assume that is only an issue when using material bottom tabs at the root layout since it works perfectly in the [expo-router-layouts-example](https://github.com/EvanBacon/expo-router-layouts-example) repo which has it nested in another navigator.

Here is my app folder structure.
![image](https://user-images.githubusercontent.com/56973177/236899829-92606bcb-537f-45d5-ac6f-1f3e6e2f6fed.png)

Here is  a part of my __layout_ file 
![image](https://user-images.githubusercontent.com/56973177/236901065-5d3430a0-e649-4cfb-80a2-b4374f7ddabd.png)

### Minimal reproducible example

Insert in
**/app/_layout.tsx**

```ts
import {
  MaterialBottomTabNavigationOptions,
  createMaterialBottomTabNavigator,
} from "@react-navigation/material-bottom-tabs";
import { withLayoutContext } from "expo-router";

const { Navigator } = createMaterialBottomTabNavigator();

export const MaterialBottomTabs = withLayoutContext<
  MaterialBottomTabNavigationOptions,
  typeof Navigator
>(Navigator);

export default function Layout() {
  return (
    <MaterialBottomTabs
      safeAreaInsets={{ bottom: 0 }}
      }
    >
      <MaterialBottomTabs.Screen
        name="index"
        options={{
          tabBarLabel: "Route 1",
        }}
      />
      <MaterialBottomTabs.Screen
        name="second"
        options={{
          tabBarLabel: "Route 2",
        }}
      />
    </MaterialBottomTabs>
  );
}


```

**Comment by BoavistaLudwig** [comment]
Did you fix it?

I encountered something similar within Material Top Tabs when I set a title on the screen file itself ...
![image](https://github.com/expo/router/assets/95169251/4175136a-0633-4b22-92a6-10b99449e2c0)

**Comment by vargajacint** [comment]
I'am experiencing same behaviour with `Tabs`, but only in production mode🤯

**Comment by balloman** [comment]
Have you found a fix?

**Comment by EvanBacon** [comment]
When you set the root layout the other screens on the root (default catch-all, sitemap) are both visible. I recommend hiding or disabling the buttons. Alternatively you can create a root layout which exports `<Slot>` and move the material from the root into `app/(app)/_layout.js`.

This doesn't happen with the built-in navigators because we manually remove them internally.  This cannot be done with custom layouts since we can't know how to configure arbitrary views.
