### ISSUE TITLE
Component render before route validation

### ISSUE THREAD

**Issue by olivier-drieux** [expo/router#559]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I have encountered a bug in the [demo provided by the library](https://github.com/expo/router/tree/main/apps/demo). The issue arises when a user is not defined, and an attempt is made to access the route `(app)`. In this scenario, the App component `(app)/index` is rendered before the route validation is completed in the `useProtectedRoute` hook.

In addition to this issue, I have experienced a similar problem in my personal project. In my project, the component makes an API call during rendering. Ideally, this API call should not be executed if the user does not have the appropriate permissions to access the component. However, due to the premature rendering of the component, the API call is made regardless of the user's access rights.

To demonstrate the issue from the demo, I have created a [fork of the expo-router project](https://github.com/olivier-drieux/router/tree/main/apps/demo) and added console.debug statements to help explain the case. Here are the logs from the first launch of the application:
```
 DEBUG  App - render
 DEBUG  App - Simulating API call...
 DEBUG  useProtectedRoute - User is null and not on sign-in page, redirecting to sign-in
 DEBUG  useProtectedRoute - end of useProtectedRoute
 DEBUG  useProtectedRoute - end of useProtectedRoute
```

As seen in the logs, the first two entries pertain to the App component, while the remaining logs are related to the useProtectedRoute hook. The expected behavior is that the App component should not be rendered until the route validation is both completed and valid. This would also prevent any unauthorized API calls from being executed.

I would appreciate it if you could confirm whether this is the intended behavior or if I am misunderstanding how the library is supposed to function. If it is indeed a bug, I hope that this information can help you resolve the issue.

### Minimal reproducible example

git clone https://github.com/olivier-drieux/router.git
cd router
yarn
cd apps/demo
yarn start

**Comment by marklawlor** [comment]
What you are describing is possible, but its not a "feature" of this library. Rather you should just use normal React patterns to solve your issue. 

For example, the `AuthProvider` could simply not render its children if the user is not signed in. Or you could wrap App in a higher-order-component so the component will not render until the user has authenticated. Its hard to give an answer, as authentication isn't a one size fits all solution. What you see as a bug others may want as a feature (e.g. if you what to show placeholder elements).

**Comment by olivier-drieux** [comment]
I appreciate your reply. I implemented your suggestions and have encountered a new problem. When I choose not to display children while the route remains unvalidated, I encounter a "Cannot read property 'type' of undefined" error. You can find more information at https://github.com/expo/router/issues/349.

Any idea?
