### ISSUE TITLE
Dynamic routes not working as exact route

### ISSUE THREAD

**Issue by ak151997galaxy** [expo/router#564]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Hi,
i have an issue in dynamic routes. i have a list of products on home screen, when click on category **see all** button it navigates to category screen where I list products. when I click on product it navigate to product screen.
but when I press on product it loads my both URLs - "/shopping/category/[id]" , "/shopping/product/[id]". this should not be happens.

NOTE: [id].tsx in both cases are different.

for further my file structure please find Minimal reproducible example

### Minimal reproducible example

https://github.com/ak151997galaxy/expo-router-dynamic-routes

**Comment by EvanBacon** [comment]
I cannot reproduce this error in Expo Router v3. If you still believe this is an issue, please open an issue in the expo/expo repo: https://github.com/expo/expo/
