### ISSUE TITLE
useRouter relative paths don't work

### ISSUE THREAD

**Issue by WKampel** [expo/router#567]
### Which package manager are you using? (Yarn is recommended)

None

### Summary

I have the following pages:

```
app
    [var]
        services
            index.js
        promotions
            index.js
        test.js
```

Calling `router.push('services')` from test.js navigates to `/services` instead of `variable/services`. 

Caling `router.push('../services')` from promotions navigates to `/services` instead of `variable/services` as well.

I setup a custom component to generate absolute paths from relative, and it also does not work.
Calling `router.push('/variable/services/../promotions')` redirects to the correct URL, but the page says 404 until I refresh it. 

```
import { usePathname, useRouter } from 'expo-router'

const useNav = () => {
  const router = useRouter()
  const pathname = usePathname()

  const push = path => {
       router.push(`${pathname}/${path}`)
  }
  return { push }
}
export default useNav
```

### Minimal reproducible example

router.push('relative/path')

**Comment by WKampel** [comment]
./services from promotions appears to work, but only with push, not with replace. Anyone know what replace would have different functionality?

**Comment by WKampel** [comment]
I've also noticed that, in this example:
```
app
    [var]
        index.js
        test.js
```

`router.push('./test')` will NOT work from index.js. I can't figure out how to relatively navigate to siblings of index files. It seems that Expo Router is not production ready. I will switch back to React Navigation.

**Comment by WKampel** [comment]
So, what I want to do is just not possible?

**Comment by z1haze** [comment]
what is the correct way to navigate to a sibling route then? eg, in the above example, how do navigate from index to test?

**Comment by Arnaud-J** [comment]
> I've also noticed that, in this example:
> 
> ```
> app
>     [var]
>         index.js
>         test.js
> ```
> 
> `router.push('./test')` will NOT work from index.js. Instead of navigating to `/variable/test` it will navigate to `/test` I can't figure out how to relatively navigate to siblings of index files. It seems that Expo Router is not production ready. I will switch back to React Navigation.

@EvanBacon Could you please show a working code snippet of what @WKampel is trying to achieve here? I can't figure it out

**Comment by abumalick** [comment]
@EvanBacon It would be useful to have a solution for a relative navigation. When working with nested screens inside bottom navigation it is useful to be able to navigate relatively to the current screen.

**Comment by marklawlor** [comment]
@abumalick Relative navigation should be working, if you are having a problem can you please create a new issue.

**Comment by joshsmith** [comment]
@marklawlor afaict, relative navigation for dynamic paths is not working as expected, e.g. if I am on `[id]/index` and want to `router.push('./edit')` to `[id]/edit`, it will simply push to `[id]/index`. If I instead use ```router.push(`${usePathname()/edit`)```, then it works as expected. This does throw a TS error, but it does work.
