### ISSUE TITLE
Tabs.Screen options are ignored if route does not exist

### ISSUE THREAD

**Issue by d4rky-pl** [expo/router#569]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

If `Tabs.Screen` is accidentally configured with wrong name (for ex. `profile` instead of `profile/index`), the tab will be rendered and `screenOptions` will be passed but the `options` will be ignored and not passed to react-navigation properly, resulting in `MissingIcon` being rendered instead.

This is not necessarily a bug (since the route is definitely incorrect) but it results in poor developer experience as it's very hard to figure out why the issue happens (took me 2h to figure this out and I only realized by mistake when trying to prep a repro for this issue)

### Minimal reproducible example

```javascript
// app/_layout.js

import { Tabs } from "expo-router";
import { Text } from 'react-native';

export default function Layout() {
  return (
    <Tabs
      initialRouteName="index"
      screenOptions={{
        headerTitleAlign: "center"
      }}
    >
      <Tabs.Screen
        name="nonexistent-route"
        options={{
          title: "Test",
          tabBarIcon: () => <Text>Icon</Text>,
        }}
      />
    </Tabs>
  );
}
```

If you drop a debugger in `node_modules/@react-navigation/bottom-tabs/src/views/BottomTabBar.tsx:357` (`icon` prop of `BottomTabItem`) you will see that `headerTitleAlign` was passed correctly but `title` and `tabBarIcon` were ignored

**Comment by byCedric** [comment]
Thanks for reporting this issue! It seems that this is caused by [`useScreens`'s `getSortedChildren`](https://github.com/expo/router/blob/main/packages/expo-router/src/useScreens.tsx#L55-L59). If a route is not matched, we return an empty route without any options, and that will remove the `options` from your `Tabs.Screen`.

Have to discuss internally if we can solve it, and what would be the best way to fix it.

**Comment by EvanBacon** [comment]
There's a warning message about using invalid route names. My preferred fix would be to remove the screen configuration and auto tab-bar creation in favor of devs just creating tab bars manually:

```js
import { TabBar } from '...'

export default function Layout() {
  return (
    <>
      <Slot tabs />
      <TabBar>
        <TabBar.Item name="index" />
        <TabBar.Item href="/other-location" />
      </TabBar>
    </>  
  )
}
```

Less magic, a little bit more code.

**Comment by d4rky-pl** [comment]
@EvanBacon that's exactly how I ended up solving all my problems, just pass a custom tab component and handle everything manually 👍
