### ISSUE TITLE
headerStyle from screen overwrites the ones from navigator

### ISSUE THREAD

**Issue by d4rky-pl** [expo/router#572]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I'm not sure if this is a bug or just something that should be documented:

Overriding `headerStyle` on the `Tabs.Screen` level replaces the entire object, rather than extending the navigator values. This can be unexpected if we assume the styles passed to the navigator are defaults and we just want to override some of them from specific routes.

### Minimal reproducible example

```javascript
import { Tabs } from "expo-router";
export default function Layout() {
  return (
    <Tabs
      initialRouteName="Index"
      screenOptions={{
        headerStyle: {
          height: 100,
        },
      }}
    >
      <Tabs.Screen
        name="(index)/index"
        options={{
          headerStyle: {
            backgroundColor: '#aaa' // setting this will reset header height to 64px
          }
        }}
      />
    </Tabs>
  )
}
```

**Comment by EvanBacon** [comment]
This is standard behavior from React Navigation

**Comment by d4rky-pl** [comment]
My bad then! Thanks for confirming :)
