### ISSUE TITLE
Params are not encoded with encodeURIComponent

### ISSUE THREAD

**Issue by wcastand** [expo/router#577]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

as title is saying,

the params from the href (router.push,etc) are not using `encodeURIComponent` which lead to `querystring.parse` in `parseQueryParams` to remove them. In our use case it replaces the + with spaces but it could break on `&` or other special characters.

in the repo, just click on the link in Index, and you will see that the params are not encoded properly, we could let the dev encode every params but i feel like it's something the router should deal with since, i don't see a reason not to encode those because otherwise it would break the app/link by not parsing properly.

### Minimal reproducible example

https://github.com/wcastand/params-bug

**Comment by hbriese** [comment]
URL search parameters are automatically encoded, just like query parameters, but are not automatically decoded
