### ISSUE TITLE
[Suggestion] add "missing default export" error for pages / layouts

### ISSUE THREAD

**Issue by 0xAsimetriq** [expo/router#597]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

I've recently migrated an app to expo router (love it!) and got stuck on an issue for few hours trying to figure out why stuff in my root `_layout` file was not being applied. After some time I realised I forgot to `export default function...` instead of just `export function...`

This lead me to create this issue and perhaps see if it is possible to improve dev experience via:

1. If user tries to access rout that technically exists in file tree, but forgot to add `export default` hence breaking the app, give them descriptive error
2. If file like `_layout.tsx` exists but doesn't have default export warn or error?

### Minimal reproducible example

N/A

**Comment by EvanBacon** [comment]
This is part of async routes, coming in v2: https://github.com/expo/router/blob/91ac19c8685c0bdf13496ef7cea47aa1d5bdafe9/packages/expo-router/src/views/EmptyRoute.tsx#L12
