### ISSUE TITLE
Unable to resolve "../global.postcss" from "app/_layout.tsx"

### ISSUE THREAD

**Issue by 641mirhwl** [expo/router#611]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I'm trying to use the tailwind example provided in apps and this is what I'm getting after yarn android
```
Android Bundling failed 4ms
Unable to resolve "../global.postcss" from "app/_layout.tsx"
```

### Minimal reproducible example

``` shell
git clone https://github.com/expo/router
cp -r apps/tailwind expo-router-tailwind
cd expo-router-tailwind
yarn
yarn add expo-status-bar
yarn android
```

**Comment by marklawlor** [comment]
This feature has not been released yet and is not ready for use.
