### ISSUE TITLE
Presentation Modal not working if on a different layout

### ISSUE THREAD

**Issue by zRelux** [expo/router#630]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

I have this structure in my code:
 - (app)
     - _layout.tsx
     - explore
        - _layout.tsx 
        - index.tsx
     - poi
        - [poi].tsx
        - _layout.tsx

Now /explore can navigate to /poi/[poi] but I would like to show it as a modal. Seems that /poi/[poi] is presented as a stack screen and not as a modal screen.  I highly doubt this is not possible but I can't seem to figure it out

Here are my layouts:

### Minimal reproducible example

(app)/_layout.tsx
```ts
import { Stack } from 'expo-router';
import React from 'react';

export default function AppLayout() {
  return <Stack screenOptions={{ headerShown: false }} />;
}
```

explore/_layout
```ts
import { Stack } from 'expo-router/stack';
import React from 'react';

export default function ExploreLayout() {
  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="index" />
    </Stack>
  );
}
```

/poi/[poi]
```ts
import { Stack } from 'expo-router';
import React from 'react';

export const unstable_settings = {
  initialRouteName: '[poi]',
};

export default function PoiLayout() {
  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen
        name="[poi]"
        options={{ presentation: 'modal', gestureEnabled: true }}
      />
    </Stack>
  );
}
```

**Comment by SalmanK81099** [comment]
Facing the same issue, the first route to navigate to from another folder or layout is treated as a stack, but in the same layout other modals work fine. Any solution found yet?

**Comment by zRelux** [comment]
Given my situation for now I am just copying the route in all the places I need it, and then when I push I use pathname to prefix the push

**Comment by tuanthanh2067** [comment]
@zRelux 

> Given my situation for now I am just copying the route in all the places I need it, and then when I push I use pathname to prefix the push

Hello, is it possible for you to share your solution because I'm facing the same issue when trying to open a modal, I receive this error `screen presentation updated from modal to push error, this may likely result in a screen object leakage. If you need to change presentation style create a new screen object instead`

Thank you

**Comment by zRelux** [comment]
@EvanBacon @marklawlor any help with this?

**Comment by EvanBacon** [comment]
In your `app/_layout.js` present the screen as a modal:

```js
import { Stack } from 'expo-router';
import React from 'react';

export default function AppLayout() {
  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="poi" options={{ presentation: 'modal' }} />
    </Stack>
  );
}
```

You cannot modally present a screen from a different stack inside the current stack. Also consider using `<Slot />` more instead of nesting stacks inside of each other.

**Comment by dalley8626** [comment]
Similarly here, i am not using a modal while it's just a normal stack
![image](https://github.com/expo/router/assets/28380930/1c6ac838-b34e-4a4a-bcbb-13c21aac29ef)

However, i am unable to navigate to products screen at all `router.push(`${segment}/products/hello`);`

**Comment by ljukas** [comment]
Could you elaborate on this @EvanBacon ?

`<Slot />` isnt very well documented.

**Comment by oliviercperrier** [comment]
@EvanBacon Also with Slot, there is no screen transition animation..

**Comment by DeluxeOwl** [comment]
@EvanBacon so many weird behaviours, like you have to put this ONLY HERE for things to work, not intuitive at all

**Comment by alexgshaw** [comment]
Also running into this issue, but not even with different layouts. Even if you just make the router.push call inside a component nested in your screen it does not work. (This only affects presentation: "modal"). Really weird bug and not sure how to fix it.

**Comment by fimbres** [comment]
Same here

**Comment by iamsoltan** [comment]
used the official documentation : [https://docs.expo.dev/router/advanced/modals/](https://docs.expo.dev/router/advanced/modals/)
Nothing works !

**Comment by homocodian** [comment]
How to show modals in drawer navigator?

**app/_layout.tsx**
Returned by default export
```ts
function RootLayoutNav() {
  return (
    <SafeAreaProvider>
      <Material3ThemeProvider>
        <AuthProvider>
          <Slot />
          <SnackbarContainer />
        </AuthProvider>
        <Alerter />
      </Material3ThemeProvider>
    </SafeAreaProvider>
  );
}
```
**(root)/_layout.tsx**
```ts
export default function StackLayout() {
  return (
    <>
      <Stack>
        <Stack.Screen name="(home)" options={{ headerShown: false }} />
        <Stack.Screen
          name="account"
          options={{
            animation: "fade_from_bottom",
            presentation: "modal"
          }}
        />
        <Stack.Screen
          name="modal"
          options={{
            headerShown: false,
            presentation: "modal"
          }}
        />
      </Stack>
    </>
  );
}
```
**(home)/_layout.tsx**
```ts
export default function AppLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <Drawer
        screenOptions={{
          header: (props) => <NavigationBar {...props} />
        }}
        drawerContent={DrawerContent}
        initialRouteName="index"
      >
        <Drawer.Screen name="index" options={{ title: "Home" }} />
        <Drawer.Screen name="general" options={{ title: "General" }} />
        <Drawer.Screen name="important" options={{ title: "Important" }} />
        <Drawer.Screen name="shared" options={{ title: "Shared" }} />
      </Drawer>
      <AddNote />
    </GestureHandlerRootView>
  );
}
```
**AddNote component**
```ts
export function AddNote() {
  return (
    <Link href="/modal" asChild>
      <FAB icon="plus" className="absolute m-4 right-0 bottom-0" />
    </Link>
  );
}
```
**tree**
![Screenshot 2024-06-04 044510](https://github.com/expo/router/assets/76059899/ff10af4b-faea-4358-a9e3-85e4201e77cd)

**Comment by clool** [comment]
same question as [homocodian](https://github.com/homocodian), how do I open a modal with drawer navigation? thanks.

**Comment by masoomro16** [comment]
wondering the same too, how to open a modal from a folder with a drawer layout?

**Comment by monkemedia** [comment]
Has anyone found a solution for this?

**Comment by PaddaSecurity** [comment]
Same here no solution yet

**Comment by vinumzz** [comment]
Is this just abondoned? Modal is completely unintuitive to work with. It just shows as a normal screen even with presentation: 'modal'
