### ISSUE TITLE
How should I handle notifications?

### ISSUE THREAD

**Issue by zRelux** [expo/router#636]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Before migrating to expo router I had a subscribe and getInitalUrl in my navigation container, given I shouldn't override the linking config, how should I go on to read notification (expo-notifications) accordingly? Also the screen I open from the notification is a modal so it should open accordingly.

### Minimal reproducible example

```
  async getInitialURL() {
    const url = await Linking.getInitialURL();

    if (url != null) {
      return url;
    }

    const response = await Notifications.getLastNotificationResponseAsync();

    return response?.notification.request.content.data.url;
  },
  subscribe(listener) {
    const onReceiveURL = ({ url }: { url: string }) => listener(url);
    const eventListenerSubscription = Linking.addEventListener(
      'url',
      onReceiveURL,
    );
    const subscription = Notifications.addNotificationResponseReceivedListener(
      response => {
        const { url } = response.notification.request.content.data;

        // Let React Navigation handle the URL
        listener(url);
      },
    );

    return () => {
      // Clean up the event listeners
      eventListenerSubscription.remove();
      subscription.remove();
    };
  },
```

**Comment by EvanBacon** [comment]
Unclear why you'd be in a spot where the deep link and the notification launched the app at the same time, let's assume these pieces of logic are unrelated.

You probably want something like this:

```js

import { useRouter } from 'expo-router';
import React from 'react';
import * as Notifications from 'expo-notifications';

export function useRouterNotifications() {
  const router = useRouter();

  React.useEffect(() => {
    let isMounted = true;

    function processUrl(url: string) {
      // In case you need to modify the URL to make it relative.
      return url;
    }

    // Handle URL from expo push notifications
    Notifications.getLastNotificationResponseAsync().then((response) => {
      if (!isMounted) {
        return;
      }
      const url = response?.notification.request.content.data.url;
      if (url) {
        router.replace(processUrl(url));
      }
    });

    // Listen to expo push notifications
    const subscription = Notifications.addNotificationResponseReceivedListener(
      (response) => {
        const url = response.notification.request.content.data.url;
        router.replace(processUrl(url));
      }
    );

    return () => {
      isMounted = false;
      subscription.remove();
    };
  }, []);
}
```

Then inside of the root layout:

```js
// app/_layout.js

import { Slot } from 'expo-router';

export default function Layout() {
  useRouterNotifications()
  // ...
  return <Slot />
}
```

Simply observe the notifications, and redirect accordingly.

**Comment by janusqa** [comment]
@EvanBacon have you tried it in Android?
This does not seem to work.

**Comment by mvolonnino** [comment]
@janusqa - is this not working in Android because you don't get any listeners to fire with the payload when receiving notification?

**Comment by stefanahman** [comment]
I got the following error:
> Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.

This only occurs when the app has been killed and is launched for the first time. When the app is open in the background, it works as expected.

According to [Navigating without navigation](https://docs.expo.dev/router/reference/authentication/#navigating-without-navigation) the solution seems to be:
> add a group and move conditional logic down a level.

Has anyone had the same issues? If yes, how did you solve it?

**Comment by clemwo** [comment]
That's also not working on Android here but works with iOS. 
So I haven't tried using a <Slot> but this simple code works on iOS but not on Android when the app is open and I click on the notification

```
    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        const postId = response.notification.request.content.data.postId;
        router.replace(`/post/${postId}`);
      });
```

However adding a 1ms timeout makes the code work for me on Android

```
    responseListener.current =
      Notifications.addNotificationResponseReceivedListener((response) => {
        const postId = response.notification.request.content.data.postId;
        setTimeout(() => {
          router.push(`/post/${postId}`);
        }, 1);
      });
```

**Comment by caiofelipeam** [comment]
> That's also not working on Android here but works with iOS. So I haven't tried using a but this simple code works on iOS but not on Android when the app is open and I click on the notification
> 
> ```
>     responseListener.current =
>       Notifications.addNotificationResponseReceivedListener((response) => {
>         const postId = response.notification.request.content.data.postId;
>         router.replace(`/post/${postId}`);
>       });
> ```
> 
> However adding a 1ms timeout makes the code work for me on Android
> 
> ```
>     responseListener.current =
>       Notifications.addNotificationResponseReceivedListener((response) => {
>         const postId = response.notification.request.content.data.postId;
>         setTimeout(() => {
>           router.push(`/post/${postId}`);
>         }, 1);
>       });
> ```

I don't like setTimeout workarounds, but that was the only thing that worked for me, thank you! 

Note: Remember to set the timeout to 1000 because it's in MS, not seconds!
