### ISSUE TITLE
Unable to use react redux provider

### ISSUE THREAD

**Issue by iaman221b** [expo/router#637]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I am using react redux in my native app , I am using provider in layout but it is not working , I have to do it node modules entry file and its working

### Minimal reproducible example

diff --git a/node_modules/expo-router/entry.js b/node_modules/expo-router/entry.js
index 6c242f1..fc29c87 100644
--- a/node_modules/expo-router/entry.js
+++ b/node_modules/expo-router/entry.js
@@ -3,6 +3,8 @@ import "@expo/metro-runtime";
 import { ExpoRoot } from "expo-router";
 import Head from "expo-router/head";
 import { renderRootComponent } from "expo-router/src/renderRootComponent";
+import {Provider} from '../react-redux'
+import {store} from '../../redux/store'
 
 const ctx = require.context(
   process.env.EXPO_ROUTER_APP_ROOT,
@@ -14,9 +16,13 @@ const ctx = require.context(
 // Must be exported or Fast Refresh won't update the context
 export function App() {
   return (
+   
     <Head.Provider>
+      <Provider store={store}>
       <ExpoRoot context={ctx} />
+    </Provider>
     </Head.Provider>
+   
   );
 }

**Comment by marklawlor** [comment]
You should add the `<Provider />` to your root level `_layout` file, not the entry file.

**Comment by infederico** [comment]
> You should add the `<Provider />` to your root level `_layout` file, not the entry file.

That's right, it worked for me. Thank you! 

app/_layout.js

import { Stack } from 'expo-router'
import { useFonts } from 'expo-font'
import * as SplashScreen from 'expo-splash-screen'
import { useCallback } from 'react'

SplashScreen.preventAutoHideAsync()

import { Provider } from 'react-redux'
import { store } from '../redux/store'

export default () => {

    const [fontsLoaded] = useFonts({
        'Marcellus': require('../assets/fonts/Marcellus-Regular.ttf'),
    })

    const onLayoutRootView = useCallback(async () => {
            if (fontsLoaded) {
                await SplashScreen.hideAsync()
            }
    }, [fontsLoaded])
            
    if (!fontsLoaded) {
        return null
    }

    return (
        <Provider store={store}>
            <Stack onLayout={onLayoutRootView}>
                <Stack.Screen
                    name='(drinksTabs)'
                    options={{
                        headerShown: false,
                    }}
                />
                <Stack.Screen
                    name='(ticketsTabs)'
                    options={{
                        headerShown: false,
                    }}
                />
                <Stack.Screen
                    name='index'
                    options={{
                        headerShown: false,
                    }}
                />
                <Stack.Screen
                    name='landing'
                    options={{
                        //headerTitle:'Bienvenidx a My Night',
                        headerShown: false,

                    }}
                />
                <Stack.Screen
                    name='register'
                    options={{
                        headerTitle:'Registro',

                    }}
                />
            </Stack>
        </Provider>
    )
};

**Comment by faizanjafar** [comment]
what if I want to use dispatch and useSelectore in the rootLayout?
In my case, I have Themeprovider.

`import { useFonts } from "expo-font";
import { Stack, useNavigation } from "expo-router";
import * as SplashScreen from "expo-splash-screen";
import { useEffect, useState } from "react";
import "react-native-reanimated";
import Colors from "@/styles/variables";
import { DefaultTheme, ThemeProvider } from "@react-navigation/native";
import { Appearance, useColorScheme } from "react-native";
import Header from "@/components/header";
import { store } from "../redux/store";
import { Provider } from "react-redux";
import { darkTheme, lightTheme } from "@/utils/useTheme";

// Prevent the splash screen from auto-hiding before asset loading is complete.
SplashScreen.preventAutoHideAsync();

export default function RootLayout() {
  const [theme, setTheme] = useState(lightTheme);

  const [loaded] = useFonts({
    UrbanistRegular: require("../assets/fonts/Urbanist-Regular.ttf"),
    UrbanistMedium: require("../assets/fonts/Urbanist-Medium.ttf"),
    UrbanistBold: require("../assets/fonts/Urbanist-Bold.ttf"),
  });

  useEffect(() => {
    if (loaded) {
      SplashScreen.hideAsync();
    }
  }, [loaded]);

  if (!loaded) {
    return null;
  }

  return (
    <ThemeProvider value={theme}>
      <Provider store={store}>
        <Stack>
          <Stack.Screen name="index" options={{ headerShown: false }} />
          <Stack.Screen name="(auth)/signIn" options={{ headerShown: false }} />
          <Stack.Screen name="(auth)/signUp" options={{ headerShown: false }} />
          <Stack.Screen
            name="(auth)/forgotPassword"
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="(auth)/codeVerification"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Verification"
                    start={true}
                    center={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="customers"
            options={{
              headerShown: false,
            }}
          />
          <Stack.Screen
            name="createCustomer"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Create Customer"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="subscription"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Subscription"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="margin"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Set Margin"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="edit"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Edit Profle"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="profileSettings"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Profle Settings"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="paymentSettings"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Payment Settings"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="addCard"
            options={{
              headerTransparent: true,
              header: () => {
                const navigation = useNavigation();

                return (
                  <Header
                    navigation={navigation}
                    text="Add Card"
                    start={true}
                    center={true}
                    end={true}
                  />
                );
              },
            }}
          />
          <Stack.Screen
            name="(tabs)"
            options={{
              headerShown: false,
            }}
          />
        </Stack>
      </Provider>
    </ThemeProvider>
  );
}
`

**Comment by boMMba7** [comment]
> You should add the `<Provider />` to your root level `_layout` file, not the entry file.

this work for me. thanks
