### ISSUE TITLE
Nested modals lose their search params

### ISSUE THREAD

**Issue by zackify** [expo/router#638]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

If you have a structure like this:

- modal 1
- modal 2

If you open modal 1 with presentation modal, and attempt to push modal 2 on top, modal 1 loses its search params.

This sucks because you have to add checks like if(!params) return null inside of modal 1.

Now when the user sees modal 2 slide up, the content of modal 1 disappear. If you close modal 2, you see modal 1 content pop back in.

Only real solution is to useRef on the param data when you have nested modals, but its annoying and feels janky 

### Minimal reproducible example

app/modal1.tsx

```
import { Text, View } from "react-native";

const Modal1 = () => {
  const { someContent } = useSearchParams();

  return <TouchableHighlight className="flex-1" onPress={() => router.push({pathname: '/modal2', someContent: 'Here it is!'})}><Text>{someContent}</Text></TouchableHighlight>
 }
export default Modal1
```

app/modal2.tsx

```
import { Text, View } from "react-native";

const Modal2 = () => {
  const { someContent } = useSearchParams();

  return <TouchableHighlight className="flex-1"><Text>{someContent}</Text></View>
 }
export default Modal2

```

app/index.tsx

```
const Index = () => {
  const { someContent } = useSearchParams();

  return <TouchableHighlight className="flex-1" onPress={() => router.push({pathname: '/modal1, someContent: 'Here it is going to be removed when modal 2 opens'})}><Text>{someContent}</Text></View>
 }
export default Index

```

**Comment by marklawlor** [comment]
https://expo.github.io/router/docs/features/linking/#usesearchparams

`useSearchParams` has been renamed to `useGlobalSearchParams` to more reflect its behaviour. If you wish to keep the params of each screen individually, the hook you should use is `useLocalSearchParams`

**Comment by zackify** [comment]
Oh awesome thanks!
