### ISSUE TITLE
presentation: modal for Android

### ISSUE THREAD

**Issue by MatLish00010** [expo/router#646]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Currently, there is a major issue with expo-router and the presentation: modal option for Android. In **react-navigation**, you can achieve a modal-like appearance on Android by simply setting  **gestEnabled: true** along with **...TransitionPresets.ModalPresentationIOS**:

`<Stack.Screen
  options={{
    presentation: 'modal',
    gestEnabled: true,
    ...TransitionPresets.ModalPresentationIOS
  }}>`

However, expo-router completely ignores these settings for Android. As a temporary solution, you can use **Stack** and **Navigator** from **react-navigation/stack**, which should resolve the problem. But it seems strange that you would need to install a navigator that expo-router already uses under the hood.

The issue with this workaround is that on both Android and iOS, if you use a modal window with these settings inside stacks that are nested within bottom tabs, the tabs will appear on top of the modal window. In react-navigation, to avoid such issues, you can place all modal screens in the main navigator and access them through **navigation.navigate(...)**. However, in expo-router, if you try to navigate to a modal screen that is located in a different stack, it will open as a regular screen.

I hope that you will address this issue or provide a solution for it.

### Minimal reproducible example

Example how it works on react-navigation

https://reactnavigation.org/docs/modal/#:~:text=Try%20this%20example%20on%20Snack

Change 
`
<RootStack.Group screenOptions={{ presentation: 'modal' }}>
          <RootStack.Screen name="MyModal" component={ModalScreen} />
  </RootStack.Group>
` to ` <RootStack.Group screenOptions={{ presentation: 'modal', gestEnabled: true, ...TransitionPresets.ModalPresentationIOS }}>`
    
    And update import `import { createStackNavigator , TransitionPresets} from '@react-navigation/stack';`

**Comment by Kakad3v** [comment]
Hi @MatLish00010,I have been wrestling with the same issue. Initially, I thought there was an error on my code. I am glad that I stumbled on this. Let's wait and see what @EvanBacon and the maintainer will advise.

**Comment by MatLish00010** [comment]
@Kakad3v 

I already got an answer on discord.  It is cited that this library uses a "stripped down" version of react navigation, and therefore not all functionality is available. 
 And also that in android there are no such modals natively

**Comment by EvanBacon** [comment]
Expo Router uses all of React Navigation *and* extends it to support more expressive URLs. I already answer this question in your duplicate issue #640.
