### ISSUE TITLE
Production mode renders ghost tabs

### ISSUE THREAD

**Issue by vargajacint** [expo/router#647]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I'm making a pretty simple application, with Tab Navigator. I am using the following structure for rendering the Tab navigator.
![Screenshot 2023-06-08 at 13 38 38](https://github.com/expo/router/assets/42407460/0de21e80-c248-41bd-a99e-3f8770669ed5)

As you can see my first tab(home) has a separate `styles.ts` file witch is holds the home screen styling. 
In development mode, I only have 4 tabs (home, search, cart, and profile), but in production mode, I have 5 tabs (home, search, cart, profile, and style)

I will attach a screenshot, which presents the difference in the prod and dev build.

![production](https://github.com/expo/router/assets/42407460/5a169880-2718-451f-a7dc-b6154fedac60)

### Minimal reproducible example

(tabs)/_layout.tsx fie:
```javascript
export default function TabLayout() {
  return (
    <Tabs tabBar={MyTabBar}>
      <Tabs.Screen name="home/index" options={{ tabBarLabel: 'Kezdőlap' }} />

      <Tabs.Screen name="search" options={{ tabBarLabel: 'Keresés' }} />

      <Tabs.Screen name="cart/index" options={{ tabBarLabel: 'Kosár' }} />

      <Tabs.Screen name="profile/index" options={{ tabBarLabel: 'Profil' }} />
    </Tabs>
  );
}
```

I'm using this command for production build: `npx expo start --no-dev`

**Comment by MatLish00010** [comment]
Expo-roter check all your's files in app, and creates nav components. 
I recomend use all use support files like (utils, styles, components...) in another folder. 

For ex. i use routing just for routers and after call screens from another folder with my screens.


And you can hide your's styles.ts from tads, you need to add _layout for home folder, and inside create <Stack/> 
Or
 ```
<Tabs tabBar={MyTabBar}>
      <Tabs.Screen name="home/index" options={{ tabBarLabel: 'Kezdőlap' }} />

      <Tabs.Screen name="search" options={{ tabBarLabel: 'Keresés' }} />

      <Tabs.Screen name="cart/index" options={{ tabBarLabel: 'Kosár' }} />

      <Tabs.Screen name="profile/index" options={{ tabBarLabel: 'Profil' }} />
<Tabs.Screen name="home/styles" options={{ tabBarLabel: 'Profil', href: null }} />
    </Tabs>
```
https://expo.github.io/router/docs/guides/tabs/

**Comment by vargajacint** [comment]
@MatLish00010 Thank you!
