### ISSUE TITLE
Missing useScrollToTop hook

### ISSUE THREAD

**Issue by vargajacint** [expo/router#651]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I'm looking for same functionality as useScrollToTop hook provides in [React Navigation](https://reactnavigation.org/docs/use-scroll-to-top/)

Any advice?

### Minimal reproducible example

Nope

**Comment by gkasdorf** [comment]
Interested in this too. Was trying to see if I could set a custom button, like with headerLeft/headerRight, but not seeing any good way to do this especially since I'd need a ref to the scrollview or flashlist.

**Comment by EvanBacon** [comment]
Import from React Navigation and use as-is:

```js
import { useScrollToTop } from '@react-navigation/native';
```

**Comment by rijk** [comment]
Following the above instructions doesn't work, I get the following error: 

```
Error: Couldn't find a navigation object. Is your component inside a screen in a navigator?
```

I'm using expo-router@4.0.16.

**Comment by rijk** [comment]
My bad, I was on @react-navigation/native v5, upgrading to v7 solved the issue.
