### ISSUE TITLE
Set headerLeft:()=&gt; null: Invalid condition exists

### ISSUE THREAD

**Issue by Mickeygogo** [expo/router#673]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Set headerLeft:()=&gt; null, but jump from the other page to the set page with replace, set headerLeft:()=&gt; null pages still display the default return button

### Minimal reproducible example

![image](https://github.com/expo/router/assets/79964964/1b30f97a-2bbe-48a4-9abc-534cf9b1c3ca)
![image](https://github.com/expo/router/assets/79964964/98c69539-356e-4ddc-b1b1-218a4c7ef100)
The default return button still exists！！
i am chinese， quick help me! thanks!

**Comment by EvanBacon** [comment]
Please provide a minimal reproducible example.
