### ISSUE TITLE
Latest tag on npm is set to 1.5.3

### ISSUE THREAD

**Issue by d4rky-pl** [expo/router#687]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Even though the latest vresion of expo-router in 1.x is 1.7.7, the `latest` tag on npm is set to 1.5.3.

I'm not sure if this is on purpose or not.

### Minimal reproducible example

https://www.npmjs.com/package/expo-router?activeTab=versions

**Comment by EvanBacon** [comment]
The last stable release of v1 is 1.5.3, lerna has issues with rc versions so we published v2 alpha starting with 1.6.0. I've deprecated all unofficial v1 releases.
