### ISSUE TITLE
Navigating to details screen in a nested Stack requires full path

### ISSUE THREAD

**Issue by frankcalise** [expo/router#70]
# Problem

From `/tabs/schedule/index`, unable to Link to `details` or `/details` via href string or href `{{ screen: "details" }}`.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/374022/194773728-17956643-e88b-4998-9a8e-d9947f96a499.png">

```
| - app
| -- (root)
| --- tabs
| ---- schedule.js (stack w/ Index and Details)
| ---- schedule
| ----- index.js
| ----- details.js
```

# Solution

If I link directly to `/tabs/schedule/details` it screen will be pushed on the stack properly

Example here: https://github.com/frankcalise/expo-router-tabs-demo/blob/main/app/(root)/tabs/schedule/index.js

**Comment by EvanBacon** [comment]
This is [incorrect syntax](https://github.com/frankcalise/expo-router-tabs-demo/blob/02c75bec53d0a1d1be6f404a519fadf9df297345/app/(root)/tabs/schedule/index.js#L41-L44), I recommend using TypeScript to give hints on the expected type.

**Comment by frankcalise** [comment]
Ok thanks will check into that - syntax was acquired from the documentation here: https://expo.github.io/router/docs/guides/params

**Comment by frankcalise** [comment]
Even switching to the proper syntax here still is trouble unless I append to the currentHref (just giving me a full absolute path)

## Unmatched route
```
<Link
  href={{
    pathname: "/details",
    query: { itemId: 86 },
  }}
>
```

## The href must start with '/' or be a fully qualified url
```
<Link
  href={{
    pathname: "details",
    query: { itemId: 86 },
  }}
>

<Link
  href={{
    pathname: "./details",
    query: { itemId: 86 },
  }}
>

<Link
  href={{
    pathname: "../details",
    query: { itemId: 86 },
  }}
>
```

## Working
```
const currentHref = useHref();

<Link
  href={{
    pathname: `${currentHref}/details`,
    query: { itemId: 86 },
  }}
>
```

**Comment by WKampel** [comment]
Any updates on this?
