### ISSUE TITLE
ThemeProvider does not change anything

### ISSUE THREAD

**Issue by balloman** [expo/router#709]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

With React Navigation, changing the theme automatically updates the headers, buttons, and backgrounds to conform to the theme specified. This does not happen in expo router. I've followed the guide on Themes on the website: https://expo.github.io/router/docs/migration/react-navigation/themes and nothing is happening. No matter what theme I set in the theme manager the header is not changing at all, nor is the color of the text.

### Minimal reproducible example

```ts
import { DarkTheme, DefaultTheme, ThemeProvider } from "@react-navigation/native";
import { Stack } from "expo-router";

export default function Layout() {
  const colorScheme = useColorScheme();

  return (
      <ThemeProvider value={DarkTheme}>
        <Stack initialRouteName="index" />
      </ThemeProvider>
  );
}
```

**Comment by EvanBacon** [comment]
Just tested, the intended behavior works as expected in the base template https://github.com/expo/expo/blob/7c8f952fed0311110290a25b008bec934c970182/templates/expo-template-tabs/app/_layout.tsx#L49

I can't reproduce given the current information.

**Comment by balloman** [comment]
Pinpointed the issue to the version of react navigation, using version 6.1.6 for `@react-navigation/native` does not work, but using version 6.1.7 does. Hope this helps anyone else with a similar issue!

**Comment by JamesHemery** [comment]
Same issue on a pnpm monorepo, same code works great on a non monorepo app (https://github.com/byCedric/expo-monorepo-example)

**Comment by marklawlor** [comment]
@JamesHemery I would need more information to assist you and preferably a link to the actual repo so I can perform troubleshooting steps. I setup a MVP pnpm monorepo and was unable to reproduce the issue so its obvious issue. My hunch is its a problem with your dependency tree and you should use `pnpm list` to debug the tree-structure.
