### ISSUE TITLE
Routes not typed correctly on Windows 11

### ISSUE THREAD

**Issue by salman-ar-sar** [expo/router#719]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Routes are not typed correctly on Windows. Attaching a screenshot for clarity. Using the template create by `yarn create expo --template tabs@beta`. No changes whatsoever expect that I created a copy of two.tsx as three.tsx. Was just trying out the Link component.

![image](https://github.com/expo/router/assets/16640612/4b9f0a1a-9dcb-4539-a3e1-0d9b4f31dbb6)

Tried the same thing on a Mac OS device. The routes are fine, though (tabs) and related routes are coming. Is that correct?

A screenshot of the type generation. This should be the issue right?
![image](https://github.com/expo/router/assets/16640612/5fa27c3d-e9aa-42d0-90df-e391853c80f8)

### Minimal reproducible example

1. `yarn create expo --template tabs@beta`
2. Open in VSCode in Windows 11.
3. Run `expo start`
to start server and generate the types. 
4. Check the href of any Link component.

**Comment by Csierram96** [comment]
Getting the same issue on M1 mac 
<img width="709" alt="image" src="https://github.com/expo/router/assets/69860033/235e78d4-22a1-4747-8566-3537003b0a45">

**Comment by vlbezak** [comment]
I have the same issue on Windows. 
Do you have an estimation when this will be fixed ?
