### ISSUE TITLE
useFocusEffect TypeScript error

### ISSUE THREAD

**Issue by zackify** [expo/router#728]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

<img width="914" alt="image" src="https://github.com/expo/router/assets/449136/0d7af7ea-2015-431b-8026-20d72a1a8e4e">

<img width="436" alt="image" src="https://github.com/expo/router/assets/449136/d4bf689a-8ba6-4bce-8d9f-f977d32f8797">

seems this is typed incorrectly, not sure how nobody else has noticed this yet?

### Minimal reproducible example

install latest version in expo, have Typescript at 5.x, run tsc

**Comment by EvanBacon** [comment]
Unclear how to fix because this works with the package's tsconfig. 

> not sure how nobody else has noticed this yet?

Possibly your `tsconfig` is misconfigured? The types should be pointing to the build directory.

**Comment by zackify** [comment]
My tsconfig was using the default:

```
{
  "compilerOptions": {},
  "extends": "expo/tsconfig.base"
}

```

updating to 2.0.0 removes the error. But 2.0.0 also removes the ability to import:
```
import { getNavigationContainerRef } from "expo-router/src/NavigationContainer";
```
which is needed for this:

https://github.com/expo/router/discussions/508
