### ISSUE TITLE
Setting `headerBackground` broke Reanimated v3 layout animation

### ISSUE THREAD

**Issue by idrakimuhamad** [expo/router#737]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I noticed this when I upgraded to reanimated version 3—the reproduction repo in the link below.

My case is simple; I want to animate layout transition based on state. After moving to version 3.1, the transition seems to be broken. Animation doesn't work, and elements are mounted immediately.  It only works if the hot reload is triggered. After much tinkering, I found that it only happened if I set the `Stack.Screen` options for `headerBackground`. Once this is removed, the transition works.

This doesn't happen in reanimated 2.x.x, however, but that version start to be unstable with some iOS version so we decided to move to version 3.

I've tried to simulate this using React-Navigation vanilla, using the same animation and setting the Stack's options using `headerBackground` -- it doesn't happen. So I can only deduce to expo-router or reanimated.

Both run on below:

"react-native": "0.72.1"
"expo": "^49.0.0"
"react-native-reanimated": "~3.3.0"
"react-native-safe-area-context": "4.6.3"
"react-native-screens": "~3.22.0"

"expo-router": "2.0.0" (also happened in the previous version)

### Minimal reproducible example

Example using expo and expo router
https://github.com/idrakimuhamad/reproduction-repo

Example with react-navigation
https://github.com/idrakimuhamad/repro-react-navigation

Working example
https://github.com/expo/router/assets/1400323/a44181b7-1f11-414b-a2a9-cdf38b34ad84

Not working
https://github.com/expo/router/assets/1400323/d8e8047f-1e42-42ae-b118-7cc152e52e07

**Comment by EvanBacon** [comment]
No overlap with Expo Router, the React Navigation example is not the same as the Expo Router example. Porting the React Navigation version over using the analogous system works as expected:

In your Stack Layout (not inside the screen):
```js
 <Stack>
        <Stack.Screen
          name="index"
          options={{
            headerBackground: () => (
              <View
                style={{
                  flex: 1,
                  height: "100%",
                  backgroundColor: "#edf6ff",
                }}
              />
            ),
          }}
        />
      </Stack>
```

Maybe a bug in Reanimated/React Navigation(?).
