### ISSUE TITLE
Protected routes setup does not work with expo-router v2

### ISSUE THREAD

**Issue by whollacsek** [expo/router#745]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Following the documentation page to setup authenticated pages https://docs.expo.dev/router/reference/authentication/ in a brand new expo 49 project with expo-router v2 leads to this error on launch:

```
 ERROR  Error: Attempted to navigate before mounting the Root Layout component. Ensure the Root Layout component is rendering a Slot, or other navigator on the first render.

This error is located at:
    in Provider (created by RootLayoutNav)
    in RootLayoutNav (created by RootLayout)
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

Please suggest a way to implement protected routes with expo-router v2.

### Minimal reproducible example

1. `npx create-expo-app@latest --template tabs@sdk-49`
2. Follow the steps in the docs https://docs.expo.dev/router/reference/authentication/
3. `npm start`
4. App crash with the above error

**Comment by whollacsek** [comment]
Current workaround is to wrap the `router.replace("/page");` in a `setImmediate()`

**Comment by whollacsek** [comment]
> Current workaround is to wrap the `router.replace("/page");` in a `setImmediate()`

Correction it only works on Android, on iOS it needs to be `setTimeout(() => {}, 1)`

**Comment by blift** [comment]
I am not sure, that will help somebody but I had a similar problem of using router. As it is in the doc, I've imported just router. 

```
import { router } from 'expo-router';
```

but should be:
```
import { useRouter } from 'expo-router';
```

then I can assign router as variable to useRouter:

```
const router = useRouter();
router.replace('/somewhere');
```

**Comment by adesugbaa** [comment]
Hope this gets fixed

**Comment by joaofleao** [comment]
> I am not sure, that will help somebody but I had a similar problem of using router. As it is in the doc, I've imported just router.
> 
> ```
> import { router } from 'expo-router';
> ```
> 
> but should be:
> 
> ```
> import { useRouter } from 'expo-router';
> ```
> 
> then I can assign router as variable to useRouter:
> 
> ```
> const router = useRouter();
> router.replace('/somewhere');
> ```

The error was `Module '"expo-router"' has no exported member 'router'.`

I had the same issue, this happened because I was using expo-router version  `^1.5.3`, 
The original issue is regarding behavior on the expo-router `v2`.

**Comment by jordanful** [comment]
Longer thread here, with a workaround: https://github.com/expo/router/issues/740

**Comment by calebpanza** [comment]
Has anyone heard anything more about this? I've tried every single workaround and the only one that's worked so far is the `useTimeout`. I'm fine to use it for now, but it feels like code smell.

The documentation Expo provides _explicitly_ states: 
> Assume the navigation is always ready in for navigation events in Expo Router.

Do we know if the Expo team is aware of this? Is there a timeline to either fix this issue or update the documentation?

**Comment by marklawlor** [comment]
If you are still experiencing this issue on `2.0.4` can you please provide an reproduction using this repo as a template https://github.com/marklawlor/expo-router-authentication

**Comment by calebpanza** [comment]
This is working great in `2.0.4`! Thanks so much @marklawlor for the help. Really appreciate it!
