### ISSUE TITLE
Unable to pass image url inside Link params

### ISSUE THREAD

**Issue by ritmillio** [expo/router#757]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

When I created a detail page I wanted to pass the Feed item params via using Link params but I think due to the nature of how expo-router create routes It is not possible to pass any image URL if we are not cutting of the https://. I am not sure if it's truly a bug or a feature but It would be nice to solve this issue somehow so we won't need to create unnecessary splitting and adding functions in each component.

Here's the warning message:
`
Possible Unhandled Promise Rejection (id: 1):
Error: Unable to open URL: /banner/1?title=First%20Slide&description=This%20is%20the%20first%20slide%20description&image=https://miro.medium.com/v2 ... lBZw.png
`

### Minimal reproducible example

` <Link
              href={{
                pathname: '/banner/[id]',
                params: {
                  id: item.id,
                  title: item.title,
                  description: item.description,  
                  image: 'https://yourdomain.com/path_to_images/image1.jpg',
                },
              }}
              style={{
                width: viewportWidth * 0.8,
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 5 },
                shadowOpacity: 0.3,
                shadowRadius: 3,
                elevation: 1,
                marginRight: spacing,
              }}
              className="justify-center items-center bg-white rounded-2xl p-4"
            >
              <Text className="text-5xl font-bold">{item.title}</Text>
              <Text>{item.description}</Text>
            </Link>`
            
            This line ` image: 'https://yourdomain.com/path_to_images/image1.jpg',` is what causing the issue.

**Comment by EvanBacon** [comment]
Can't repro with `"expo-router": "2.0.0",`. We also test against this.
