### ISSUE TITLE
Link needs to be "as const" when using typedRoutes

### ISSUE THREAD

**Issue by switz** [expo/router#769]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

![image](https://github.com/expo/router/assets/990166/f6ad5367-58bc-43a8-b917-6484b5880d16)

![image](https://github.com/expo/router/assets/990166/27a59ba4-d6d6-40d9-baa6-5bfc3bc9bdbc)

my guess is this could probably be solved with typescript `const` parameters

### Minimal reproducible example

```javascript
<Link
            href={{
              pathname: '/(tabs)/artists/[artistUuid]/venues',
              params: {
                artistUuid: artist.uuid,
              },
            }}
            asChild
          >
```

**Comment by EvanBacon** [comment]
Fixed in the latest `expo@49.0.4`
