### ISSUE TITLE
useState

### ISSUE THREAD

**Issue by M0hamedAbdallah** [expo/router#771]
### Which package manager are you using? (Yarn is recommended)

None

### Summary

use State in tabs.screens don,t back to default but if you navigate to anther bag outside tabs screens and make the state value as " " and modify it by some code to be as "value" and back  the value if you navigate back to " " 

### Minimal reproducible example

const [name,setname]= useState(' ');

change it by some code to 

name == 'value'

it,s back to  ' ' if i back to the page that make me navigate to this page

**Comment by EvanBacon** [comment]
I can't make sense of this description.
