### ISSUE TITLE
OnLayout (or UseEffect) only runs once on the same route when navigating back and forth

### ISSUE THREAD

**Issue by michelecocuccio** [expo/router#775]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

When I navigate to a route where I have a component with `useEffect` or an `onLayout`, if I go back (either with `router.back()` or navigating using a bottom tab bar) and I go back to the same route again, the `useEffect` or the `onLayout` effect doesn't run anymore. It feels like the component is somehow "cached" but it shouldn't... for example I have an animation that I need to run whenever I land on that route and this is preventing it from working.

[video-19109873-85fb73a85a333a432cea3568bdbb7583.webm](https://github.com/expo/router/assets/8071249/7855cb1b-4870-44b3-8269-937e430d724a)

Using Expo SDK 49 (so Expo Router 2.0).

### Minimal reproducible example
```
import { View } from "react-native";

export const Picker = () => {
  const handleLayout = () => {
    console.log("ON LAYOUT");
  };

  return <View onLayout={handleLayout}></View>;
};
```
Simply try to put this component in a route and navigate back and forth. 
I have also tried to use them directly in a route (not in a component) but the result is the same

**Comment by EvanBacon** [comment]
Expected behavior. The screen doesn't re-render on native when using a stack. Use `useFocusEffect` from `expo-router` if you want a callback when the screen is navigated to.

**Comment by michelecocuccio** [comment]
> useFocusEffect

thanks a lot @EvanBacon and sorry if it was obvious. I always check documentation throughly before opening an issue but there is nothing in Expo Router docs that mention this. Yes I know it's on the React Navigation doc, but maybe you could add it to the Expo Router doc as well? Anyway sorry just a small feedback! Thank you for your great work :)
