### ISSUE TITLE
Can't dynamically set gestureEnabled in a presentation: "modal" screen

### ISSUE THREAD

**Issue by mozzius** [expo/router#778]
### Which package manager are you using? (Yarn is recommended)

pnpm (known issues due to Metro)

### Summary

I want to disable the swipe down gesture in a `presentation: "modal"` when I have unsaved changes in the screen. While I can set `gestureEnabled` in the layout, when I set it dynamically in a screen the setting does not work.

In fact, while I want to set it on the fly, I found it doesn't even work if you set it to false the whole time on the page using `<Stack.Screen>` in the screen's component.

I also tried to use `navigation.setOptions` in a `useEffect` but that didn't work either

### Minimal reproducible example

```js
// _layout.js
export default function Layout() {
  return (
    <Stack>
      <Stack.Screen title="example" options={{ presentation: "modal" }} />
    </Stack>
  )
}
```

```js
// example.js
export default function Screen() {
  return (
    <>
      <Stack.Screen options={{ gestureEnabled: false }} />
      <Text>You can swipe me down</Text>
   </>
}
```

**Comment by EvanBacon** [comment]
Seems like a `react-native-screens` issue.

**Comment by mozzius** [comment]
Ok I'll open an issue there, thanks

**Comment by mozzius** [comment]
@EvanBacon it was entirely a me problem, sorry. I had nested another `<Stack>` inside the modal so obviously the `gestureEnabled` prop was only applied to the inner `<Stack.Screen>`. Closing
