### ISSUE TITLE
Incorrect type issue with useSearchParams

### ISSUE THREAD

**Issue by dalley8626** [expo/router#788]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

I find it confusing as well, basically if i have sth like src/app/[...missing].tsx, and then src/app/product/[id].tsx in my

[id].tsx

import { Stack, useSearchParams } from "expo-router";
import { Text } from "react-native";

export const ProductScreen = () => {
  const searchParams = useSearchParams();
  const id = searchParams?.id

  return (
    <>
      <Stack.Screen name="ProductScreen" />
      <Text>ProductScreen {id}</Text>
    </>
  );
};

export default ProductScreen;
i got this error

Property 'id' does not exist on type 'RouteParams<"/product/[id]"> | RouteParams<"/[...missing]"> | Record<string, string>'.
  Property 'id' does not exist on type 'RouteParams<"/[...missing]">'.ts(2339)
and if i remove the [...missing].tsx, the typeerror goes away

### Minimal reproducible example

none

**Comment by EloB** [comment]
@dalley8626 I think you missed the migration guide.

https://blog.expo.dev/introducing-expo-router-v2-3850fd5c3ca1
> Update useSearchParams to useGlobalSearchParams or useLocalSearchParams [depending on your needs](https://docs.expo.dev/router/reference/search-parameters/#local-vs-global-search-parameters).
Update web document titles using <Head /> instead of React Navigation Stack titles.
Migrate navigation.canGoBack to the new router.canGoBack function.
All additional features can be incrementally adopted by following their respective guides:

**Comment by dalley8626** [comment]
Although i use `const searchParams = useLocalSearchParams();` 

i still got this error
```
Property 'id' does not exist on type 'RouteParams<"/[...missing]"> | RouteParams<"/product/[id]"> | Record<string, string>'.
  Property 'id' does not exist on type 'RouteParams<"/[...missing]">'.ts(2339)
  ```
