### ISSUE TITLE
No type error when using wrong path

### ISSUE THREAD

**Issue by MarchewkaMatthew** [expo/router#808]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Hi,

Thank you for maintaining this module. I have a question regarding the type-safety of the `<Link />` component using `expo-router` v2 and expo SDK 49. I've created a new project using the `npx create-expo-app@latest --template tabs@sdk-49` command. After the first run, I wanted to try typed hrefs, unfortunately, there is no TS error when I use the wrong path (type hints work well when I type, so TypeScript is able to read the `/.expo/types/router.d.ts` file). Is there any way to make it more secure and allow only registered routes?

Here are the related packages versions:
```
    "expo": "~49.0.5",
    "@react-navigation/native": "^6.0.2",
    "expo-router": "2.0.0",
    "typescript": "^5.1.3",
```

### Minimal reproducible example

1. Run `npx create-expo-app@latest --template tabs@sdk-49`
2. Run `npm start` to generate `/.expo/types/router.d.ts` file
3. Go to `/app/(tabs)/_layout.tsx` and change the link href to `/anything`
4. No typescript error about using the wrong path

<img width="863" alt="image" src="https://github.com/expo/router/assets/56259093/ba54388f-d441-42eb-b358-96f6bb93311c">

**Comment by marklawlor** [comment]
That example has a route `[...missing].tsx` which is a catch-all route on the top level - meaning all routes are "registered" from a types perspective.

This is an unfortunately side-effect while we are still exploring options to best represent 404 and/or error pages.
