### ISSUE TITLE
Router.push acts like navigation.navigate from react-navigation

### ISSUE THREAD

**Issue by snowdigital** [expo/router#810]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

When navigating to new instance of same page navigator going back instead of pushing next page

Expected
[user1] ->
[meeting1] ->
[user2]

Actual 
[user1]->
[meeting1] (going back to same page as user1)

That’s is the behaviour of navigation.navigate from react-navigation, but router.push is expected to push new route to history instead of navigating back to previously used route

### Minimal reproducible example

` router.push({ pathname: 'meeting/[id]', params: { id: item.id } });`

 `router.push({ pathname: 'user/[id]', params: { id } });`

**Comment by Tobjoern** [comment]
Yes! I'm facing the exact same issue, are there any solutions?
