### ISSUE TITLE
Android production build fails

### ISSUE THREAD

**Issue by croshim** [expo/router#823]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Android production build fails with newly initialized `tabs@49` expo. Trying to use `expo-dev-client` and `npx expo run:android --variant release`

![image](https://github.com/expo/router/assets/4670396/2dd8aa9c-18a5-4bac-abd4-0f877c08c12e)

Results for `npx expo-env-info`:
![image](https://github.com/expo/router/assets/4670396/1237c88d-a1ce-4d3c-9981-ae7e3bcfc7ec)

### Minimal reproducible example

`npx create-expo-app@latest --template tabs@49`
`cd expo-49-latest/`
`npx expo install expo-dev-client`
`npx expo run:android --variant release`

**Comment by EvanBacon** [comment]
Ensure you have tsconfig paths support setup and bundle with Expo CLI https://docs.expo.dev/guides/typescript/#path-aliases

**Comment by saravanakumargn** [comment]
Same issue i am facing. Only not working when i use `npx expo run:android --variant release`.
Not facing any issues on builds.
