### ISSUE TITLE
Dynaimc routes as mentioned in the documentation do not work

### ISSUE THREAD

**Issue by janusqa** [expo/router#827]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

In the documentation
```
import { Link } from 'expo-router';

export default function Page() {
  return (
    <View>
      <Link
        href={{
          pathname: "/user/[id]",
          params: { id: 'bacon' }
        }}>
          View user
        </Link>
    </View>
  );
}
```
I've tried this like this
```
<Link  asChild href={{
	pathname: "/appnav/m/profiles_details",
	params: { id },
}}>
...
</Link>
```
This gives the following error.

```
Type '{ pathname: string; params: { id: string; }; }' is not assignable to type 'Href<string>'.ts(2322)
router.d.ts(164, 5): The expected type comes from property 'href' which is declared here on type 'IntrinsicAttributes & LinkProps<string> & { children?: ReactNode; }'
```

### Minimal reproducible example

none.

**Comment by michalstruck** [comment]
Which part is a dynamic value in your `pathname`? I'll assume it's `m`, then you'd use the props like so:
`
<Link  asChild href={{
	pathname: "/appnav/m/profiles_details",
	params: { m: id },
}}>
...
</Link>
`

**Comment by marklawlor** [comment]
I'm going to close this issue as there isn't enough information for us to provide assistance. If you can reply with a reproducible repo, then we can reopen it and troubleshoot further
