### ISSUE TITLE
View does not extend beyond SafeAreaView in app/index.tsx.

### ISSUE THREAD

**Issue by addnsk** [expo/router#828]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

"expo": "~49.0.5",
"expo-router": "2.0.0",

mac os simulator 
iphone 13 ios 15.0

### Minimal reproducible example

```
import { StatusBar } from 'expo-status-bar';
import LoginScreen from './login';
import { View } from 'react-native';

export default function EntryPoint() {
    return (
        <View style={{ backgroundColor: 'green', flex: 1 }}>
            <StatusBar hidden />
            <LoginScreen />
        </View>
    );
}
```
The green color is only present within the SafeAreaView.
How can I change the background color outside the SafeAreaView?

Thanks

**Comment by devoren** [comment]
@addnsk can you send an image or video?

**Comment by animaonline** [comment]
Any updates on this? It's easy to reproduce this.

**Comment by animaonline** [comment]
<img width="406" alt="Screenshot 2023-10-21 at 16 21 06" src="https://github.com/expo/router/assets/1227586/f223a99c-35f1-4952-a95b-fb4d4d7f484f">

**Comment by animaonline** [comment]
Here's a way to make it fill the screen, but is that actually expected?

`<View style={[StyleSheet.absoluteFill]}>`

**Comment by marklawlor** [comment]
This is expected. Expo Router renders a default SafeAreaView to ensure the navigators render correctly. You can either override it with your own or modify your view styles to render outside the bounds.

**Comment by apetta** [comment]
For anyone else dealing with this, you can get the root view to fill the screen by using `useSafeAreaInsets` from `react-native-safe-area-context` 

Something like:
```
  const insets = useSafeAreaInsets();
  return (
    <View
      style={{
        marginBottom: -insets.bottom,
        marginTop: -insets.top,
      }}
    />
  );
  ```

**Comment by madhavgharmalkar** [comment]
@marklawlor you suggested that we could override it with our own, how would we do that?

**Comment by marcopolodesign** [comment]
@apetta thanks for that brilliant suggestion, works like a charm still

**Comment by kennydifiore** [comment]
> @marklawlor you suggested that we could override it with our own, how would we do that?

@madhavgharmalkar I believe the correct way to override it would be to define a root layout `_layout.jsx/tsx` at the top level of your app folder: (e.g., `app/_layout.tsx`).  If a root layout is defined, then the DefaultNavigator that has the SafeAreaView will not be used.  You could define your own SafeAreaView in a root layout and style it however you would like.
