### ISSUE TITLE
Layout in nested Slot causes <Link /> to not route in v2.

### ISSUE THREAD

**Issue by austin43** [expo/router#832]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

When converting a normal modal.tsx file to a modal folder with a _layout and index file, `<Link href="/modal" />` no longer works.

### Minimal reproducible example

https://github.com/austin43/expo-router-layout-routing

**Comment by austin43** [comment]
![image](https://github.com/expo/router/assets/12026053/17697e71-0108-4406-af61-eedeecfea3e6)

It shows up in the sitemap, and is routable by editing the url to `/modal`, but pressing a `<Link />` or `router.push` doesn't work.

**Comment by austin43** [comment]
Possibly related to https://github.com/expo/router/issues/768.  When I pull initialRouteName out, the routing works again as expected.

**Comment by louie-succio** [comment]
I'm seeing this too and I have a similar route structure to you where I have a parent route, a layout with a <Slot>, and then child routes.  If I'm on the child route, using router.push or <Link> to the parent route will not navigate for me.   My app does not use `initialRouteName` so your attempted fixed doesn't work for me.

<img width="264" alt="image" src="https://github.com/expo/router/assets/23384650/20b500f1-f7f1-41a8-afbb-0d20b92b63db">

The scenario I'm talking about attempts to go from `/benefit/support/faqs` to `/benefit/support`.  This used to work with the previous expo-router version.
