### ISSUE TITLE
[Web] Page title cannot be changed in v2

### ISSUE THREAD

**Issue by gaishimo** [expo/router#835]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

In v2 web, the `title` value in `options` of `Navigator.Screen` does not change the actual title.

```tsx
<Navigator>
  <Navigator.Screen name="index" options={{ title: "Title" }} />
  <Navigator.Slot />
</Navigator>
```

It worked on expo-router v1.

### Minimal reproducible example

https://github.com/gaishimo/expo-router-example

**Comment by cseelus** [comment]
See this discussion: https://github.com/expo/router/discussions/770

**Comment by EvanBacon** [comment]
Closing in favor of https://github.com/expo/router/discussions/770
