### ISSUE TITLE
On White Theme in android 13 no visible text on status bar 

### ISSUE THREAD

**Issue by disolaterX** [expo/router#836]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Not able to get the white theme status bar working works fine in Ios

### Minimal reproducible example

I use a typescript <> expo tabs 49 template to do this 
![Screenshot 2023-08-12 at 6 12 53 PM](https://github.com/expo/router/assets/42447408/20fbc1b6-fffd-40a7-ae01-ce4fbb1c9212)

**Comment by snowdigital** [comment]
here you are

[https://docs.expo.dev/versions/latest/sdk/status-bar/](https://docs.expo.dev/versions/latest/sdk/status-bar/)

**Comment by marklawlor** [comment]
Can you please create the issue on the Expo Status Bar repo https://github.com/expo/expo

I'd suggest including details if this is only happening in Expo Router projects or in an Expo app.
