### ISSUE TITLE
feat: bundle splitting

### ISSUE THREAD

**Issue by EvanBacon** [expo/router#84]
There are two types of bundle splitting in Metro:
- Development: this is useful for bundling much faster by skipping modules that aren't required for the initial load.
- Production: useful for web loading speeds. This will require a custom Metro serializer.

This is not blocking the v1 release.

**Comment by pang0018** [comment]
@EvanBacon can you share thoughts on when this feature will be released (are targeted Expo release). This is the only requirement holding my team back switching from react navigation to expo router. Thanks for any insight you can share!

**Comment by EvanBacon** [comment]
Development bundle splitting is coming to all platforms (experimentally) in Expo Router v2 (SDK 49) https://twitter.com/baconbrix/status/1656634378749968386?s=46&t=4GpE_iEDNlOGqhX9K_d56A

**Comment by EvanBacon** [comment]
Landed in v3 https://blog.expo.dev/expo-router-v3-beta-is-now-available-eab52baf1e3e#
