### ISSUE TITLE
Metro has encountered an error: While trying to resolve module stylis 

### ISSUE THREAD

**Issue by hyochan** [expo/router#863]
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Kindly note, I am raising this concern once more following issue #854. It appears to have been inadvertently closed even though the matter has not been addressed. I've been facing this challenge for over a month now. Your understanding and assistance would be greatly appreciated.

I would like to bring to your attention that the issue still persists in expo-router@^2.0.1 as mentioned in [this comment](https://github.com/expo/expo/issues/23412#issuecomment-1650882142). Additionally, as @marklawlor pointed out in [this comment](https://github.com/expo/router/issues/854#issuecomment-1691113444), it remains unresolved. Your guidance on this matter would be deeply appreciated.

### Summary

Originally posted related issue in https://github.com/expo/expo/issues/23412.

I am facing below error after installing `emotion` from `expo-router-49 template`.

<img width="930" alt="Screenshot 2023-08-23 at 10 27 26 AM" src="https://github.com/expo/router/assets/27461460/66a83abe-e839-4630-9906-71e0661c4dfe">

## Related Issue

I also posted issue in https://github.com/emotion-js/emotion/issues/3073 and doubt that this happens in `expo-router` 🤔

### Minimal reproducible example

I created a small repo in [commit](https://github.com/hyochan/expo-router-49-stylis-error-reproduction/commit/082a2d331f67b12545862125fe4ecad201e2138b) after `Generated by create-expo-app 2.0.3.
` in https://github.com/hyochan/expo-router-49-stylis-error-reproduction.

**Comment by marklawlor** [comment]
@hyochan Sorry if it wasn't clear, the fix for this issue is on its way https://github.com/expo/expo/commit/4e5f28ee19d60af09a7b45bbbcaa23eff37f693f https://github.com/expo/expo/commit/8816be9a63f4efe79274631d3c3041b914366dbf, and will be released in the next `@expo/metro-config` update. Until then, you can use the quick fix of forcing `.mjs` resolution by updating your `metro.config.js` with `config.resolver.assetExts.push("mjs");`.

**Comment by abumalick** [comment]
@marklawlor Which version of @expo/metro-config is impacted please?

**Comment by marklawlor** [comment]
`latest`, which is `0.10.x`.  The issue was resolved in `0.13.x`
