### ISSUE TITLE
Navigation between screens in different tabs does not work 

### ISSUE THREAD

**Issue by janusqa** [expo/router#865]
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Navigation between screens in different tabs does not work.
Clicking on a link in a screen in one tab does not navigate to a screen in another tab.
When I click on a link on a screen in one tab to go to a screen in another tab it should navigate. It does not.

### Minimal reproducible example

https://github.com/janusqa/rn-bare/tree/bug_navigation
npm install
npm start

1) click on the sign in button
2) click on the "Go to Tab 2 / Screen 1" link (it should navigate)
3) click on the first tab
4) click on the "Go to Tab 2 / Screen 1" link (it no longer works)

**Comment by marklawlor** [comment]
Can you please update your repo to be a minimal reproducible example. I cloned your repo and was unable to see a 'Sign in' button. There's also appears to be authentication / loading logic that I'm unsure is related to your issue?

**Comment by janusqa** [comment]
@marklawlor thanks for your feedback.
I've stripped it down to the very basics now I think.  The tabs should now load directly.

1. Click on the **Go to Tab2 / Screen 1**.  It should navigate.
2. Go back to **Tab 1** and click on **Go to Tab2 / Screen 1** again. It should no longer work 

Note they are three branches on this repo.  I am linking to the navigation bug one directly.
https://github.com/janusqa/rn-bare/tree/bug_navigation

**Comment by janusqa** [comment]
@marklawlor this issue seems to have been fixed in 2.0.4. 
I forced installed it for the time being "npm install expo-router@latest"
```
Some dependencies are incompatible with the installed expo version:
  expo-router@2.0.4 - expected version: 2.0.0
Your project may not work correctly until you install the correct versions of the packages.
```
2.0.4 seems to have fixed the issue I have been having.

**Comment by austin43** [comment]
@janusqa I believe that's a warning, rather than an error.  As near as I can tell the line is missing the `if (redirect != null)` so it'll throw deprecated regardless of whether the redirect prop is used or not.  Harmless warning and you should be able to use 2.0.4, however.

https://github.com/expo/router/blob/3dcd231e4c7006837e1b1f1461239a521ae9ddcb/packages/expo-router/src/views/Screen.tsx#L50

**Comment by austin43** [comment]
Submitted https://github.com/expo/router/pull/873 to fix the confusing warning.

**Comment by marklawlor** [comment]
Those are just warnings, its fine to upgrade to `2.0.4`. The `deprecated` message will be removed in `2.0.5`

**Comment by janusqa** [comment]
@marklawlor @austin43, thank you.
Note that the deprecated warning is still present in 2.0.5
