### ISSUE TITLE
useFocusEffect cleanup - This expression is not callable

### ISSUE THREAD

**Issue by GustavoBonfimS** [expo/router#906]
This problem seems to have been fixed in v3 but caused another problem when installing the ExpoHead Pod so I can't update. (SDK 49

![image](https://github.com/expo/router/assets/50304935/3f5c0a5e-03bb-4bbc-9aca-b4c2d2e367cb)

Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `expo-router@2.0.12` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/expo-router/src/useFocusEffect.tsx b/node_modules/expo-router/src/useFocusEffect.tsx
index 21dfe2c..d1174f1 100644
--- a/node_modules/expo-router/src/useFocusEffect.tsx
+++ b/node_modules/expo-router/src/useFocusEffect.tsx
@@ -92,7 +92,7 @@ export function useFocusEffect(
         return;
       }
 
-      if (cleanup !== undefined) {
+      if (cleanup !== undefined && typeof cleanup === 'function') {
         cleanup();
       }
 
@@ -101,7 +101,7 @@ export function useFocusEffect(
     });
 
     const unsubscribeBlur = navigation.addListener("blur", () => {
-      if (cleanup !== undefined) {
+      if (cleanup !== undefined && typeof cleanup === 'function') {
         cleanup();
       }
 
@@ -110,7 +110,7 @@ export function useFocusEffect(
     });
 
     return () => {
-      if (cleanup !== undefined) {
+      if (cleanup !== undefined && typeof cleanup === 'function') {
         cleanup();
       }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by GustavoBonfimS** [comment]
My tsconfig {
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "~/*": [
        "*"
      ]
    },
    "strict": false,
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "duplicateProperties": "warning",
          "validProperties": [
            "shadow-color",
            "shadow-opacity",
            "shadow-offset",
            "shadow-radius",
            "padding-horizontal",
            "padding-vertical",
            "margin-vertical",
            "margin-horizontal",
            "tint-color",
            "aspect-ratio",
            "elevation"
          ]
        }
      }
    ]
  },
  "extends": "expo/tsconfig.base",
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "dist",
    "web-build",
    "src/pages",
  ],
  "include": [
    "**/*.ts",
    "**/*.tsx",
    ".expo/types/**/*.ts",
    "expo-env.d.ts",
    "jest-setup-js"
  ]
}

**Comment by EvanBacon** [comment]
This is fixed in Expo Router v3
